### ISSUE TITLE
Icon of XtextEditor does not respect file extension

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/xtext-eclipse#1005]
My intention was to have different icons for different file extensions, in our case 'n4js' and 'n4jsd'. I changed the `plugin.xml` like so (mind the different icons):

```
<extension point="org.eclipse.ui.editors">
        <editor            class="org.eclipse.n4js.ui.N4JSExecutableExtensionFactory:org.eclipse.xtext.ui.editor.XtextEditor"
            contributorClass="org.eclipse.ui.editors.text.TextEditorActionContributor"
            default="true"
            extensions="n4js"
            id="org.eclipse.n4js.N4JS"
            icon="platform:/plugin/org.eclipse.n4js.ui/icons/file_n4js.png"
            name="N4JS Editor">
        </editor>
        <editor
            class="org.eclipse.n4js.ui.N4JSExecutableExtensionFactory:org.eclipse.xtext.ui.editor.XtextEditor"
            contributorClass="org.eclipse.ui.editors.text.TextEditorActionContributor"
            default="true"
            extensions="n4jsd"
            id="org.eclipse.n4js.N4JS"
            icon="platform:/plugin/org.eclipse.n4js.ui/icons/file_n4jsd.png"
            name="N4JS Editor">
        </editor>
```

The result is that the package explorer will show the different icons according to the specification in the `plugin.xml`. However, the title image of the editor will show the icon of the last entry for all of the file extensions; in this case, it will always show the icon `file_n4jsd.png`.

<img width="634" alt="screen shot 2019-03-07 at 13 09 25" src="https://user-images.githubusercontent.com/20560257/53955889-76b2fa80-40da-11e9-825d-bbe377fcfb36.png">

**Comment by cdietrich** [comment]
do you have any idea what causes this?

**Comment by mmews-n4** [comment]
> do you have any idea what causes this?

I debugged and came to
`org.eclipse.ui.internal.e4.compatibility.CompatibilityPart` line 340:
```java
WorkbenchPartReference reference = getReference();
```
which seems to return an instance with the wrong field `reference.descriptor` of type `EditorDescriptor`. The instance `reference.descriptor.imageDesc` has the value "URLImageDescriptor(platform:/plugin/org.eclipse.n4js.ui/icons/file_n4jsd.png)" which is the last entry of the plugin.xml. From there on, I didn't know who to continue.

> org.eclipse.xtext.ui.editor.XtextEditor.getDefaultImage()

I checked that method in the XtextEditor and it will always return the same icon, in our case `file_n4jsd.png`. In other words, it will not respect the file extension of `XtextEditor#getEditorInput().getName()`.

> com.verigy.itee.ui.iconmanager.IconManager.getDescriptorForFileExtension(String)

Where can I find this class `IconManager`? I appreciate if you elaborate on what I could test here.

**Comment by cdietrich** [comment]
sorry thats an internal class that does query the registry

ImageDescriptor descriptor = getImageRegistry().getDescriptor(some custom name);
        if(descriptor == null){
            return getImageRegistry().getDescriptor(prefix + defaultName);
        }

**Comment by cdietrich** [comment]
=> its just a workaround and not a solution

**Comment by cdietrich** [comment]
ps: how does a non xtext editor class behave e.g. abstracttexteditor subclass?

**Comment by cdietrich** [comment]
that org.eclipse.n4js.N4JS is used as id for both looks bogus to me

**Comment by mmews-n4** [comment]
> getImageRegistry().getDescriptor(some custom name);

The registry does contain all icons that are mentioned in the plugin.xml. So yes, as a workaround I can set the title image manually to the correct one depending on the file extension
(e.g. `if (XtextEditor#getEditorInput().getName().endsWith(".n4jsd")) {...}`).

> how does a non xtext editor class behave e.g. abstracttexteditor subclass?

I did not test that.

**Comment by cdietrich** [comment]
i want to find out if this is a xtext problem or a platform problem.
and again: please double check the editor id

**Comment by mmews-n4** [comment]
Thanks so far for your help. Regarding the editor id:
Right, using individual ids would solve this but introduce other issues. Sharing the id works in all other use cases (package explorer, open resource dialog) out of the box except for the editor icon. Using individual ids would make it necessary to list all these ids at several other locations of the plugin.xml and maybe the code as well.
I'll check again regarding the platform behavior.

**Comment by mmews-n4** [comment]
Regarding the platform behavior:
I just found the following Java-Doc at `org.eclipse.ui.texteditor.AbstractTextEditor#initializeTitle(IEditorInput)` (line 4064):
> Note: We use the editor's image instead of the image from the editor input to distinguish situations where the same editor input is opened in different kinds of editors.

That means that the icon of the input file is deliberately ignored in favor of the editor icon. (_It's not a bug, it's a feature._)
