### ISSUE TITLE
No XtextDocument/Highlighting in Compare With Index

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1009]
1. create a git repo
1. create a xtend file in it and commit it
1. do some changes to the xtend file, dont commit it
1. add the git repo to eclipse without project import
1. open git repo instaging view and do a compare with index.
the left side of compare wont have highlighting
(cce was prevented via https://github.com/eclipse/xtext-eclipse/commit/2c2b7512e348eb974df40595f106a3a02f112b76)

**Comment by cdietrich** [comment]
i dont know why we do get a xtext document for the right, but not for the left side

**Comment by cdietrich** [comment]
cc @qdagans

**Comment by cdietrich** [comment]
i already tried to debug this multiple times in the past but i am rather clueless.
@iloveeclipse @trancexpress maybe you have help us analyzing this

**Comment by cdietrich** [comment]
trace where the "wrong" doc is created

```
TextMergeViewer$ContributorInfo.createDocument() line: 809	
TextMergeViewer$ContributorInfo.internalSetDocument(MergeSourceViewer) line: 682	
TextMergeViewer$ContributorInfo.setDocument(MergeSourceViewer, boolean) line: 645	
DefaultViewerCreator$1(TextMergeViewer).updateContent(Object, Object, Object) line: 2991	
DefaultViewerCreator$1(DefaultMergeViewer).updateContent(Object, Object, Object) line: 95	
DefaultViewerCreator$1(ContentMergeViewer).internalRefresh(Object) line: 790	
DefaultViewerCreator$1(ContentMergeViewer).inputChanged(Object, Object) line: 698	
DefaultViewerCreator$1(ContentViewer).setInput(Object) line: 289	
CompareContentViewerSwitchingPane(CompareViewerSwitchingPane).setInput(Object) line: 268	
CompareContentViewerSwitchingPane.setInput(Object) line: 190	
GitCompareFileRevisionEditorInput(CompareEditorInput).internalSetContentPaneInput(Object) line: 804	
GitCompareFileRevisionEditorInput(CompareEditorInput).lambda$8(ISelection) line: 745	
2073453012.run() line: not available	
BusyIndicator.showWhile(Display, Runnable) line: 72	
GitCompareFileRevisionEditorInput(CompareEditorInput).feed1(ISelection) line: 740	
GitCompareFileRevisionEditorInput(CompareEditorInput).feedInput() line: 718	
GitCompareFileRevisionEditorInput(CompareEditorInput).createContents(Composite) line: 542	
CompareEditor.createCompareControl() line: 448	
CompareEditor.access$6(CompareEditor) line: 408	
CompareEditor$1.lambda$0(boolean, int[]) line: 366	
```

**Comment by cdietrich** [comment]
i wonder why org.eclipse.xtext.ui.compare.DefaultMergeViewer.updateAsDocument(Object)
says it is a shared document
whilest org.eclipse.compare.contentmergeviewer.TextMergeViewer.ContributorInfo.createDocument()
cannot connect to it.

@szarnekow do you have any dejavues?

**Comment by iloveeclipse** [comment]
May be relevant? 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543146#c4

**Comment by cdietrich** [comment]
yes it looks so

**Comment by miklossy** [comment]
I can also reproduce the problem
![screenshot](https://user-images.githubusercontent.com/20393472/54015301-9819f200-417f-11e9-84b1-91603a39f069.png)

**Comment by miklossy** [comment]
I also noticed an exception
```
java.lang.AssertionError: '_new!=null && old!=null && !old.getURI().equals(_new.getURI())' constraint violated, old was platform:/resource/Foo/src/foo/Foo.xtend new was: revision:/Foo.xtend
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionDelta.<init>(DefaultResourceDescriptionDelta.java:35)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager.createDelta(DefaultResourceDescriptionManager.java:69)
	at org.eclipse.xtext.ui.editor.DirtyStateResourceDescription$Manager.createDelta(DirtyStateResourceDescription.java:85)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.haveEObjectDescriptionsChanged(DirtyStateEditorSupport.java:626)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.announceDirtyState(DirtyStateEditorSupport.java:536)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:211)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:185)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:90)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:450)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:430)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:364)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:434)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:167)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:361)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

 while editing an Xtend file in the compare view:
![screencast](https://user-images.githubusercontent.com/20393472/54016198-73734980-4182-11e9-8ebb-e3e2e7b8de4e.gif)

**Comment by cdietrich** [comment]
@miklossy  please move this to a separate issue

**Comment by miklossy** [comment]
Separate issue https://github.com/eclipse/xtext-eclipse/issues/1010 created

**Comment by trancexpress** [comment]
> i already tried to debug this multiple times in the past but i am rather clueless.
> @iloveeclipse @trancexpress maybe you have help us analyzing this
> 
> (e.g. arround org.eclipse.xtext.ui.compare.DefaultMergeViewer.updateAsDocument(Object)) / ISharedDocumentAdapter
> org.eclipse.xtext.ui.compare.DefaultMergeViewer.updateContent(Object, Object, Object)

> May be relevant?
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=543146#c4

@iloveeclipse do we have a ticket for this on our tracker? I don't find one. I don't think we'll keep track of this without such a ticket.

**Comment by iloveeclipse** [comment]
We have no ticket in our tracker. I guess this must be done by XText committers / gurus.

**Comment by cdietrich** [comment]
@iloveeclipse @trancexpress i mentioned it in our company bugtracker.

**Comment by tomaswolf** [comment]
Which EGit version and which Xtext version? Note that we made quite a few changes in this area in EGit 5.3.0.

I can reproduce the CCE mentioned in commit 2c2b751 with EGit 5.2.0 (Eclipse 2018-12, Xtext 2.16.0), using the steps given by Christian in the initial comment here (i.e., doing a "Compare with Index" on a non-workspace xtend file).

Upgrading to EGit nightly fixes the CCE for me, and I cannot reproduce any of these problems with Xtext 2.16.0:

* commit 2c2b751  is not in Xtext 2.16.0, but doesn't seem to be needed either. (Could never reproduce the CCE when comparing a text file against an xtend resource, with either EGit version -- unsurprisingly since EGit isn't involved in that case.)
* eclipse/xtext-eclipse#1009 (this very bug report) does not occur with EGit nightly
* eclipse/xtext#2446 (AssertionError when editing in a "Compare With Index") does not occur with EGit nightly; editing works flawlessly for both the local and the index version.

Using Eclipse 2019-03RC1 (Xtext 2.17.0, EGit 5.3.0) I also cannot reproduce any of these problems.

**Comment by cdietrich** [comment]
@tomaswolf this issue is based on Xtext 2.17 and the CCE is catched there. the problem is: how to get a Xtext document. i always get a normal document produced which then leads to the CCE

**Comment by tomaswolf** [comment]
I cannot reproduce on Eclipse 2019-03RC1 (which includes Xtext 2.17.0 and EGit 5.3.0). What EGit version are you using?

**Comment by cdietrich** [comment]
let me see. indeed with 5.3 i get the highligting back.

**Comment by cdietrich** [comment]
with 	Eclipse EGit	Git integration for Eclipse - UI	5.3.0.201901162155-m1	org.eclipse.egit.ui
the problem was still there

**Comment by tomaswolf** [comment]
No surprise; the EGit changes got committed on February 17. See Gerrit change [135417](https://git.eclipse.org/r/#/c/135417/).

**Comment by tomaswolf** [comment]
Especially my first comment in that Gerrit change might interest you: "This is not good enough yet. The Eclipse framework somehow uses the wrong document provider for LocalNonWorkspaceTypedElements, which later causes trouble if a non-workspace Xtext resource is being compared." :-)

**Comment by tomaswolf** [comment]
BTW, also of interest in this respect: Gerrit change [136612](https://git.eclipse.org/r/#/c/136612/). This makes sure that the right document provider (in this case the one from xtend) is chosen by the compare framework for non-workspace files (i.e., FileStoreEditorInput). EGit 5.3.0 has a special work-around/hack in LocalNonWorkspaceTypedElement that works even on platforms older than 2019-03.

**Comment by cdietrich** [comment]
works ok enhough for us
