### ISSUE TITLE
Can't to find org.eclipse.xtext.ui.testing for 2.12.0

### ISSUE THREAD

**Issue by q12321q** [eclipse/xtext-eclipse#1013]
Hi,
I'm trying to implement some unitary code tests to validate our content assist enrichment implementation.
In order to do that I need to extends my test class with this one: `org.eclipse.xtext.ui.testing.AbstractContentAssistTest` (ref: https://www.eclipsecon.org/france2015/sites/default/files/slides/presentation.pdf).
My problem is that I can't find any public package for my gradle build to pull it.

I've found `AbstractContentAssisTest` in [org.eclipse.xtext.xbase.junit(https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.junit/2.10.0/org.eclipse.xtext.xbase.junit-2.10.0.jar) but unfortunately it's only available for version before 2.10.

Is there any exists package repo where I can pull this class for 2.12.0?
Thanks for your help

**Comment by cdietrich** [comment]
there is no eclipse content assist test in gradle.
can you explain what you exactly do with gradle (web, lsp, ...)

**Comment by q12321q** [comment]
I'm building a language with Xtext and I give some code completion to a code mirror plugin.
I enrich the code completion proposals with some keywords by implementing a class that extends `IdeContentProposalProvider`. So far so good :)

I would like to implement some junit tests that validate this implementation: e.g. validate the code completion suggestion with a given language expression with the cursor at this position.

I found this ppt https://www.eclipsecon.org/france2015/sites/default/files/slides/presentation.pdf (page 29 _Testing the Content Assist_) that describe pretty well what I want to achieve but unfortunately it looks outdated. it tells to add the dependency `org.eclipse.xtext.common.types.ui` to get access and use `AbstractContentAssistTest` as base class but unfortunately I can't find a dependency for the version 2.10 that contains this class.

**Comment by cdietrich** [comment]
i fear there is no content assist testing infrastructure for that. maybe you can ab/resuse 
https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/CompletionTest.xtend

**Comment by q12321q** [comment]
Thanks a lot @cdietrich.
I manage to make my use case work by adpating an example found on the forum:
https://www.eclipse.org/forums/index.php?t=msg&th=1096739&goto=1800400&#msg_1800400
