### ISSUE TITLE
Optimize the usage of the 'while (Display.getDefault().readAndDispatch()) {}' invocation.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1018]
The invocation of the `while (Display.getDefault().readAndDispatch()) {}` ensuring that all UI events are processed is cluttered all over the Xtext code base, e.g.

[org.eclipse.xtext.ui.editor.quickfix.TextualMultiModificationWorkbenchMarkerResolutionAdapter#processUIEvents(int)](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/TextualMultiModificationWorkbenchMarkerResolutionAdapter.java#L169)

[org.eclipse.xtext.ui.testing.AbstractHighlightingTest#waitForEventProcessing()](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend#L119)

This kind of functionality should be offered by a utility method and the code should be refactored to use that utilty method. See also [discussion in comment](https://github.com/eclipse/xtext-eclipse/pull/1014#discussion_r266307298).

**Comment by cdietrich** [comment]
there are other tests that do a readAndDispatch too

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
