### ISSUE TITLE
XtextGrammarQuickfixProviderTest randomly fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1020]
XtextGrammarQuickfixProviderTest randomly fails

https://ci.eclipse.org/xtext/job/xtext-eclipse/job/cd_oomph_412/1/testReport/junit/org.eclipse.xtext.xtext.ui.editor.quickfix/XtextGrammarQuickfixProviderTest/testFixKeywordWithSpaces/

@szarnekow is it possible we miss your injector fix somewhere?

**Comment by cdietrich** [comment]
```
@RunWith(Suite.class)
@SuiteClasses({
	XtextTemplateContextTest.class,
	XtextOutlineTreeProviderTest.class,
	XtextGrammarQuickfixTest.class,
	XtextGrammarQuickfixProviderTest.class,
})
public class DullySuite {

}
```

**Comment by miklossy** [comment]
See also https://github.com/eclipse/xtext-eclipse/pull/1000/commits/a0a6ef14dcd68408d92085e59db58011d7690a4b

**Comment by cdietrich** [comment]
there is also the problem that
there might be multiplequickfixes

expected:<Re[move empty keyword]> but was:<Re[place empty keyword with rule name]>

that might occur in random order

**Comment by szarnekow** [comment]
Fixed
