### ISSUE TITLE
DefaultRefactoringDocumentProvider should use getAdapter as a fallback to retrieve the editor

### ISSUE THREAD

**Issue by lsotnk** [eclipse/xtext-eclipse#1027]
Hi.

I use the XtextEditor in a MultiPageEditorPart. When retrieving the editor for the current input _DefaultRefactoringDocumentProvider_ uses _instance of ITextEditor_, which doesn't work in this case.

It would be great it there was a fallback _getAdapter(XtextEditor.class)_, similar to _org.eclipse.xtext.ui.editor.utils.EditorUtils.getXtextEditor(IEditorPart)_.

Btw. not sure why you test for _ITextEditor_ instead of _XtextEditor_.

**Comment by riederm** [comment]
is there a reason why EditorUtils calls 
`openEditor.getAdapter(XtextEditor.class);` instead of `org.eclipse.core.runtime.Adapters.adapt(Object, Class<T>, boolean)` to also cover registered AdapterFactories?

**Comment by cdietrich** [comment]
i have doubts anyone who could answer this still reads here....

@szarnekow do you have any idea?

**Comment by szarnekow** [comment]
I don't think there is any reason to not use `Adapters.adapt(..)` nowadays. EditorUtils was like this in 2010 whereas `Adapters.adapt(..)` is from 2015. So that might be the reason.
We should also check for other places where we use `IAdaptable.getAdapter(..)`

**Comment by cdietrich** [comment]
same problem in ```org.eclipse.xtext.ui.refactoring2.ChangeConverter.findOpenEditor(IFile)```

**Comment by riederm** [comment]
i gave it a try but it is much more than expected.

I'll check all the files again tomorrow, for now all the adapter-calls begin to blurr.

I created two pull requests, but maybe we discuss if we really want all these changes?
I think it makes the code better, but it definetly needs a couple of eyes to check the changes. 

https://github.com/eclipse/xtext-eclipse/pull/1347 (27 files)
https://github.com/eclipse/xtext-xtend/pull/1009 (1 file)

**Comment by szarnekow** [comment]
Thank you very much for your work on this @riederm. Greatly appreciated!
