### ISSUE TITLE
[Formatter2] FormattableDocument renderToTextReplacements performance is very slow

### ISSUE THREAD

**Issue by moayman** [eclipse/xtext-eclipse#1047]
For a **10000** Lines document:
`renderToTextReplacements` takes about **240** seconds to finish. This is really unacceptable.

More insight into what I am doing:
- I am trying to achieve autowrap by doing executing the following `.append[autowrap]` on all the document's `SemanticRegions`. I do so to be 100% sure that the document doesn't exceed the `maxLineWidth`.
- Without `.append[autowrap]` on all `SemanticRegions` but on commas only for example. The result is `renderToTextReplacements` taking about **0.3** seconds which is good. However the performance is still bad due to `TextEdit apply` found in `ContentFormatter` format function. `TextEdit apply` takes about 25 seconds in both cases. **Note:** autowrapping on commas only leaves my document with lines still exceeding the `maxLineWidth` which is not what I am after.

Further investigation shows that **230** seconds were spent in `needsAutowrap` function during calculation of `getLeadingCharsInLineCount` I have been looking at this function and I feel like it can be enhanced by using some kind of dynamic programming if possible.

**Comment by cdietrich** [comment]
@moayman can you please provide a sample grammar, formatter and unit test

**Comment by moayman** [comment]
@cdietrich Unfortunately, I have tried to reproduce that on a sample grammar but I couldn't. I will now settle for autowrapping only specific tokens. Which adds up to about **30** seconds in case of a 10000 lines file. **25** out of those **30** are spent in `TextEdit.apply()`.

I will close the issue.

**Comment by moayman** [comment]
I would like to add the following statistics though.
  | Autowrap Enabled on all SemanticRegions | Autowrap on full list | Autowrap on , ; | NoAutowrap
-- | -- | -- | -- | --
ContentFormatter exec | 242.97 | 9.06 | 3.42 | 2.42
\|-- ContentFormatter Init | 0.94 | 0.90 | 1.02 | 0.97
\|-- ContentFormatter format | 242.03 | 8.15 | 2.39 | 1.45
\|** MyDSLFormatter Format | 1.38 | 1.09 | 1.41 | 1.27
\|** renderToTextReplacements | 240.63 | 7.04 | 0.97 | 0.16
\|-- ContentFormatter createTextEdit | 0.00 | 0.01 | 0.01 | 0.00
TextEdit Apply | 20.11 | 23.51 | 23.13 | 22.79
Total | 263.08 | 32.57 | 26.55 | 25.21

**Comment by moayman** [comment]
| Autowrap Enabled on all SemanticRegions | Autowrap on full list | Autowrap on , ; | NoAutowrap
-- | -- | -- | -- | --
ContentFormatter exec | 242.97 | 9.06 | 3.42 | 2.42
\|-- ContentFormatter Init | 0.94 | 0.90 | 1.02 | 0.97
\|-- ContentFormatter format | 242.03 | 8.15 | 2.39 | 1.45
\| ** MyDSLFormatter Format | 1.38 | 1.09 | 1.41 | 1.27
\| ** renderToTextReplacements | 240.63 | 7.04 | 0.97 | 0.16
\|-- ContentFormatter createTextEdit | 0.00 | 0.01 | 0.01 | 0.00
TextEdit Apply | 20.11 | 23.51 | 23.13 | 22.79
Total | 263.08 | 32.57 | 26.55 | 25.21

I would like to add those statistics though.
"Autowrap on full list" refers to a list that is bigger than ", ;" with around **15** elements to autowrap at.

**Comment by cdietrich** [comment]
as indicated before: without any help to reproduce this is hard to tacle.
working with 10000 lines files is not a std usecase though

**Comment by moayman** [comment]
10000 lines is kinda standard in my case for big projects.

**Comment by moayman** [comment]
@cdietrich Umm, the apply method now consumes most of the time while executing `updateDocumentStructures` Do you think this is related to eclipse/xtext#2439 ?
![image](https://user-images.githubusercontent.com/8499385/55727939-652f7c00-5a13-11e9-85b6-2ec5d0f8c091.png)

**Comment by cdietrich** [comment]
cannot tell that per se.

**Comment by moayman** [comment]
Is it normal to have the following as text replacers:
```
465  1 " ": space=' ';autowrap
467  0 "": space='';autowrap
468  1 " ": space=' ';autowrap
470  0 "": space='';autowrap
471  1 " ": space=' ';autowrap
473  0 "": space='';autowrap
474  1 " ": space=' ';autowrap
476  0 "": space='';autowrap
477  1 " ": space=' ';autowrap
479  0 "": space='';autowrap
480  1 " ": space=' ';autowrap
482  0 "": space='';autowrap
483  1 " ": space=' ';autowrap
485  0 "": space='';autowrap
486  1 " ": space=' ';autowrap
488  0 "": space='';autowrap
489  1 " ": space=' ';autowrap
491  0 "": space='';autowrap
492  1 " ": space=' ';autowrap
494  0 "": space='';autowrap
495  1 " ": space=' ';autowrap
497  0 "": space='';autowrap
498  1 " ": space=' ';autowrap
500  0 "": space='';autowrap
501  1 " ": space=' ';autowrap
503  0 "": space='';autowrap
504  1 " ": space=' ';autowrap
506  0 "": space='';autowrap
507  1 " ": space=' ';autowrap
509  0 "": space='';autowrap
510  1 " ": space=' ';autowrap
512  0 "": space='';autowrap
513  1 " ": space=' ';autowrap
515  0 "": space='';autowrap
516  1 " ": space=' ';autowrap
518  0 "": space='';autowrap
519  1 " ": space=' ';autowrap
521  0 "": space='';autowrap
522  1 " ": space=' ';autowrap
524  0 "": space='';autowrap
525  1 " ": space=' ';autowrap
527  0 "": space='';autowrap
528  1 " ": space=' ';autowrap
530  0 "": space='';autowrap
531  1 " ": space=' ';autowrap
533  0 "": space='';autowrap
534  1 " ": space=' ';autowrap
536  0 "": space='';autowrap
537  1 " ": space=' ';autowrap
539  0 "": space='';autowrap
540  1 " ": space=' ';autowrap
542  0 "": space='';autowrap
543  1 " ": space=' ';autowrap
545  0 "": space='';autowrap
546  1 " ": space=' ';autowrap
548  1 " ": space=' ';autowrap
550  1 " ": space=' ';autowrap
560  1 " ": space=' ';autowrap
563  1 " ": space=' ';autowrap
```
Why aren't they all in one TextReplacer with more spaces?
