### ISSUE TITLE
Refactoring(2): Temp data are kept in memory after renaming

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-eclipse#1048]
The temporary resource sets created and populated during rename or move refactorings are kept in memory for too long, potentially for whole life of the application. That may happen if the language injectors are initialized in a `ModalContextThread`, which transitively holds the refactoring data, because Guice 3.0 injectors hold the `creatingThread` objects [for their entire lifes](https://github.com/google/guice/blob/77727a73c2addaffd388faacc99a76b61b7bd4c2/core/src/com/google/inject/internal/Initializer.java#L38), see

![MemoryLeak](https://user-images.githubusercontent.com/8513883/55795475-2a3b5000-5ac8-11e9-92bb-4708d466f7f8.png)

![MemoryLeak2](https://user-images.githubusercontent.com/8513883/55795534-5787fe00-5ac8-11e9-89c6-5b3eb9869b75.png)

IMO the observed scenario is hardly avoidable without changing the implementation `ModalContext`,  modifying Guice, or significantly changing the initialization of the involved injectors. However, at least the `ChangeSerializer` instances with their temporary data should be disposed once the text changes have been prepared.

**Comment by cdietrich** [comment]
@sailingKieler can you please describe what is left open and what is already solved by your pr?

**Comment by sailingKieler** [comment]
The problem described in the title
> Temp data are kept in memory after renaming

is fixed, so the issue can be closed.
An open question is whether that aspect could be improved:
> because Guice 3.0 injectors hold the creatingThread objects for their entire lifes

I saw that with Guice 4.1 that part changed significantly but I don't know wether it would be desirable or even possible to update Guice. Maybe a change of `ModalContextThread` should be proposed that adds dropping of the operation data once the thread is terminated.

**Comment by cdietrich** [comment]
that would be https://github.com/eclipse/xtext-core/issues/393
