### ISSUE TITLE
Provide context actions in Find References search result

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#1050]
The search result view for the Find References action could be enriched with some context actions, like they are offered for Java/Text results for example.

The context menu should offer a Copy and a Remove Selectected Matches action in a first step. Other actions may be addressed here or in later issues.

**Comment by kthoms** [comment]
![screenshot 83](https://user-images.githubusercontent.com/265597/56034087-8b605f00-5d26-11e9-9389-ec9638714c78.png)

**Comment by cdietrich** [comment]
Fixed in 2.18

**Comment by kthoms** [comment]
I have created follow-up issue #1080 with the enhancement idea from @szarnekow .
