### ISSUE TITLE
refactoring2: Progress reporting is bad/check for cancelation is missing on 'Rename...'/'Move...' resources

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-eclipse#1053]
The implementation in https://github.com/eclipse/xtext-eclipse/blob/ab4a08bd8f066876a708ca1007635425b04c1f68/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.xtend#L65-L80 doesn't forward the progress monitor to the employed `changeSerializer` object, which shamelessly prevents cancelation of refactorings.

Besides, the progress reporting in [ChangeSerializer#applyModifications(...)](https://github.com/eclipse/xtext-core/blob/540b8ecc86797a832dd724f0d7d32e7152ca3a9c/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java#L72-L94) is bad, as currently the parts requiring the most effort are not individually tracked (calls of `beginRecording` in the second loop).

I'll provide some PRs.

**Comment by cdietrich** [comment]
@sailingKieler see also https://github.com/eclipse/xtext/issues/1403

**Comment by sailingKieler** [comment]
jep

**Comment by cdietrich** [comment]
@sailingKieler this is done function wise correct?

**Comment by sailingKieler** [comment]
Yep, I think so.

**Comment by cdietrich** [comment]
ok thus i mark this as fixed in 2.18
