### ISSUE TITLE
Bogus Version Numbers in Domain Model Example POMs

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1063]
Bogus Version Numbers in Domain Model Example POMs:

The Domain Model example uses the same versioning scheme as is used for Xtext itself.
I wonder why we dont use a neutral scheme like 1.0.0-SNAPSHOT

**Comment by kthoms** [comment]
I think one of the reasons to align it with Xtext's version scheme is that it can be identified with which version it was created. We do frequent updates on the examples.

But I understand your point, it is also valid. Let's discuss.

**Comment by cdietrich** [comment]
ok. will close as wontfix
