### ISSUE TITLE
[Embedded Editor] support rename refactorings

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1078]
Given is the following EmbeddedXtextEditor project referencing the domainmodel example project:
[EmbeddedXtextEditor.zip](https://github.com/eclipse/xtext-eclipse/files/3210804/EmbeddedXtextEditor.zip)

Currently, there is no Rename Refactoring support offered on the Embedded Xtext Editor:
![screenshot](https://user-images.githubusercontent.com/20393472/58234137-27c24c00-7d3e-11e9-8f66-e0b4d68839c6.png)

It would be nice if the `Rename Element` context menu would be offered and also if the keybord shortcut `Alt+Shift+R` would trigger the rename refactoring.

**Comment by kthoms** [comment]
I assume there are also context actions that might be interesting here also.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
