### ISSUE TITLE
Reference Search Results: Copy text additionally in other formats (RTF/HTML)

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#1080]
With #1050 the reference results can be copied to the clipboard as plain text. Eclipse does allow to copy the text in other formats additionally (see RTFTransfer, HTMLTransfer).

TODO: Extend functionality in `org.eclipse.xtext.ui.editor.findrefs.ReferenceSearchViewPageActions.Copy`

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
