### ISSUE TITLE
Replace the IResourcesSetupUtil class by an injectable utility.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1092]
The `org.eclipse.xtext.ui.testing.util.IResourcesSetupUtil` class should be deprecated and replaced by an injectable utility, as suggested by @szarnekow in his [comment](https://github.com/eclipse/xtext-eclipse/pull/1000#pullrequestreview-209867244).

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
