### ISSUE TITLE
Extend the Content Assistant test infrastructure to test proposals from several resources.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1093]
Currently, the Xtext UI Content Assistant test infrastructure provides utilities to test proposals coming from a single resource. This test infrastructure should be extended to provide a comfortable testing of proposals coming from several resources.

**Hint:** The [StatemachineContentAssist2Test.xtend](https://github.com/itemis/itemis-blog/blob/combining-emf-models-with-xtext-dsls/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineContentAssist2Test.xtend) test case contains such a scenario.

CC @hannesN

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
