### ISSUE TITLE
Launch Action for generator on *.xtext gone

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-eclipse#110]
During testing the beta I noticed that the action for launching the generator from a *.xtext file is not there.

**Comment by cdietrich** [comment]
seems to have todo with how we package. i cannot reproduce this when starting from eclipse runtime

**Comment by cdietrich** [comment]
i cannot reproduce this with the lasted version from http://services.typefox.io/open-source/jenkins///job/xtext-eclipse/job/master/129/artifact/build/p2-repository/ as well

**Comment by cdietrich** [comment]
@svenefftinge i tried a fresh installation from the milestone update site and still cannot reproduce

**Comment by cdietrich** [comment]
@svenefftinge any feedback on this?

**Comment by svenefftinge** [comment]
Haven't tried again, but if it works for you, let's close and reopen if it happens again :)
