### ISSUE TITLE
[wizard] eclipse launch - set "Clear Configuration" to true

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#1102]
If set to false, new xtext plugins may not be activated because ui extension points are not reloaded

<img width="316" alt="Bildschirmfoto 2019-06-17 um 09 50 34" src="https://user-images.githubusercontent.com/454322/59589680-c6965a00-90ea-11e9-8966-9d76990961a8.png">

**Comment by cdietrich** [comment]
hint:

```
-<booleanAttribute key="clearConfig" value="false"/>
+<booleanAttribute key="clearConfig" value="true"/>
```

**Comment by kthoms** [comment]
I don't like this. I usually do not set this option until absolutely necessary. This also wipes out projects from the runtime workspace. IMHO this should not be active by default!

**Comment by cdietrich** [comment]
Clean workspace is a different option please check again

**Comment by kthoms** [comment]
Oh, sorry for that, you are right. Then it's fine.

**Comment by cdietrich** [comment]
Fixed
