### ISSUE TITLE
Strange positioning of warnings/errors in wizard

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1108]
Strange positioning of warnings/errors in wizard:
am not sure if this happens on mac and windows too

![Bildschirmfoto vom 2019-06-19 21-31-54](https://user-images.githubusercontent.com/238736/59794689-d2943e80-92d9-11e9-8535-64a0b8c7a5e8.png)

**Comment by cdietrich** [comment]
=> seems to be connected to low resolution

**Comment by cdietrich** [comment]
resizing helps. so it looks there is a redraw missing or something like that

**Comment by cdietrich** [comment]
i wonder why we have a status widget on page 2 and use the header on page 1

**Comment by cdietrich** [comment]
fixed

**Comment by miklossy** [comment]
I still observe a problem regarding the layouting on my computer:
![screencast](https://user-images.githubusercontent.com/20393472/60487340-fb381300-9c9f-11e9-8ef3-956f8b47347f.gif)

**Comment by cdietrich** [comment]
can you please analyze and debug this on windows?

**Comment by miklossy** [comment]
The layouting looks properly (at least on my computer) when setting the `widthHint` of the image layoutdata and the `heighHint` of the link layout data. After merging the PR I will test this on several computers.

**Comment by miklossy** [comment]
Fixed in 2.19
