### ISSUE TITLE
EmbeddedEditor: add API to configure the foregroundcolor/backgroundcolor of the linenumbers column

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1126]
The EmbeddedEditor currently uses the default colors for the foreground (black) and for the background (white) of the line numbers column.

![screenshot](https://user-images.githubusercontent.com/20393472/60766456-3c6a6180-a0aa-11e9-8fa5-80fb6c6022b6.png)

The EmbeddedEditorFactory should provide an API to be able to customize these colors (e.g. to use a gray color for the foreground/background of the line numbers column).

**Comment by cdietrich** [comment]
Fixed in 2.19
