### ISSUE TITLE
[oomph] Target platform incomplete

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#116]
Some projects from xtext-eclipse have dependencies on bundles which are not part of the SDK. This becomes visible when the Xtext setup is executed with the "Eclipse Support" without xtext-core and xtext-extras.

The missing plugins are:
- org.eclipse.xtext.testlanguages
- org.eclipse.xtext.testlanguages.ide
- org.eclipse.xtext.purexbase
- org.eclipse.xtext.testing
- org.eclipse.xtext.xbase.testing
- org.eclipse.xtext.tests

To make these projects compilable without the need to set up the dependent subprojects, the mentioned plugins have to be available in a p2 repository.

**Comment by spoenemann** [comment]
I don't think we need to support this case. If someone wants the tests to work locally, he has to check out core and extras, too.

**Comment by kthoms** [comment]
For the user it looks a bit disturbing when projects have compile problems and they have to figure out what's wrong until they eventually figure out the reason.

I agree that this is not the normal case and we may expect that xtext-eclipse is not selected without the others, or the user has to expect these errors.

We could organize the projects that might have compile errors into different working sets. I would find it disturbing if the "main" working set shows errors after set up. What do you think?

![screenshot 85](https://cloud.githubusercontent.com/assets/265597/20060839/61d166ae-a4fd-11e6-9172-9afad1e7e3be.png)

**Comment by kthoms** [comment]
It's not only the examples, but also o.e.x.purexbase.ui and o.e.x.testlanguages.ui

**Comment by LorenzoBettini** [comment]
Isn't this scenario related to dependencies among setups? I mean, if one checks out xtext-eclipse, shouldn't also the xtext-core and extras be checked out as well? I don't think this is currently supported by Oomph right now.

**Comment by svenefftinge** [comment]
Long term we should either get rid of the dependencies or have them included in SDK. I think org.eclipse.xtext.testing and org.eclipse.xtext.xbase.testing should be included for instance.

**Comment by svenefftinge** [comment]
For now, requiring checkout of upstream repositories seems to be the most practical solution.

**Comment by kthoms** [comment]
Where should this be documented? I think the contribution guide should not be polluted with this corner case, but maybe there could be some extended guide to explain more details?

**Comment by svenefftinge** [comment]
I added a note to https://github.com/eclipse/xtext-eclipse/blob/master/README.md

**Comment by svenefftinge** [comment]
Let's do it likewise in other cases.

**Comment by kthoms** [comment]
Agreed. This is just a corner case and documentating it should be enough.
