### ISSUE TITLE
domainmodel example should use variable for xtext version

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1171]
domainmodel example should use variable for xtext version

(currently it uses project.version all over the place)

**Comment by miklossy** [comment]
@cdietrich what is the state of this issue? As far as I can see, you prepared some commits in a branch that have not been merged into master.

**Comment by cdietrich** [comment]
dont have time to verify

**Comment by cdietrich** [comment]
Fixed in 2.20
