### ISSUE TITLE
Domainmodel Example: Add duplicated property validation rule

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1202]
Currently, the Domainmodel validation does not catch duplicated properties that results to invalid generated code:
![screenshot](https://user-images.githubusercontent.com/20393472/65891247-8199e900-e3a4-11e9-9f88-83ad40469c7a.png)
The Domainmodel validator should be extended by the duplicated properties validation rule.

**Comment by cdietrich** [comment]
@miklossy anything left?

**Comment by miklossy** [comment]
Fixed in 2.20
