### ISSUE TITLE
Performance: repeated computation of identical Ecore mapping

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/xtext-eclipse#1214]
During an Xtext build in Eclipse the EcorePlugin is repeatedly asked for the same information `EcorePlugin.computePlatformURIMap(false)`. See
https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/JavaProjectResourceSetInitializer.java#L60

In a local clean build of mine that amounts to 79 seconds. Without really knowing what that Ecore call does, it looks to me like the information can be calculated once, and reused for every other invocation (during the same clean build at least).
![image](https://user-images.githubusercontent.com/406876/66657418-140d7880-ec40-11e9-817e-2d163ef1a307.png)

**Comment by cdietrich** [comment]
@Bananeweizen I don’t get that.
This method in called only once for the build isn’t it?

**Comment by cdietrich** [comment]
Maybe you are on a system with antivirus running amok as described here
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543742

**Comment by Bananeweizen** [comment]
I must admit I have not measured the number of calls (since it slows down the profiler by a factor of 10 typically, and that is really slow for a huge workspace), but I can do that. In the case of just 1 call there would be no potential for optimization on your side, but only on the emf side. It seems that EMF reads and parses a huge amount of files (but I don't know which yet).
I've disabled the virus scanner for eclipse installations and workspaces, therefore I suspect this is actually real. I report back once I have more details.

**Comment by cdietrich** [comment]
You know you can do call counting only in yourkit which is fast too?

**Comment by cdietrich** [comment]
Please also check what is taking so long in the emf method

**Comment by cdietrich** [comment]
You might also observe if antivirus is doing stuff in task manager or so

**Comment by cdietrich** [comment]
@merks do you see any chance to cache computePlatformURIMap properly?

**Comment by cdietrich** [comment]
@Bananeweizen this is a build of the complete xtext workspace. the 10s are ca 1% of the build time.
=> i am sure you have a antivirus problem

**Comment by merks** [comment]
Of course the general problem with any kind of cache is the question of cache consistency, i.e., when would the cached result be different from the recomputed result?  That would be the case when the workspace state changes, e.g., changes to the registrations in plugin.xmls, or the target platform state changes.   One would need to add listeners for such things.  

Of course the method name itself suggests this computes the result for each call and there are two forms.  I would have though you should call EcorePlugin.computePlatformURIMap(true).

I imagine you could cache the result of one call and throughout a single build phase.

**Comment by cdietrich** [comment]
my assumtion is that this is already the case.
=> if you do a clean build you will get `2 * numberOfProjects` calls

here is a example with 2 projects

![Bildschirmfoto vom 2019-10-14 09-48-43](https://user-images.githubusercontent.com/238736/66735858-d723ca80-ee67-11e9-82ce-85c9408b730b.png)

**Comment by cdietrich** [comment]
@szarnekow do you remember why we call `org.eclipse.emf.ecore.plugin.EcorePlugin.computePlatformURIMap(boolean)` with `false` here
https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/JavaProjectResourceSetInitializer.java#L60

**Comment by szarnekow** [comment]
For historical reasons (tm) some languages may have referred to installed EPackages in addition to the packages available in the TP. The TP content is added to the resulting map in the subsequent code of this method along with all other kinds of package fragment roots (e.g. m2 containers, gradle containers).

**Comment by cdietrich** [comment]
=> i dont see any chance to cache "more" in a proper way

**Comment by cdietrich** [comment]
@Bananeweizen any update ?

**Comment by Bananeweizen** [comment]
@cdietrich After close inspection I found that my company managed laptop actually had the virus scanner enabled (for unknown reasons) when doing those tests. Unfortunately it may take another 3 days until I have the rights to disable it, due to a heavy process for that. 
I will take another measurement when that is possible.

**Comment by cdietrich** [comment]
@Bananeweizen any update?

**Comment by cdietrich** [comment]
will close this for now as we cannot do anything beyond the new extension point
