### ISSUE TITLE
Xtext Wizard Fragment: no file headers are generated

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1228]
When using the Xtext project wizard / file wizard fragments in the mwe2 workflow, the generated `Messages.java` class does not contain any file headers, even if it is configured previously.

When extending the Xtext FowlerDsl Example by the 
```
projectWizard = {
	generate = true
}
```
configuration, the generated `Messages.java` class does not contain the configured file header
```
/*
 * generated by Xtext
 */
```
![screenshot](https://user-images.githubusercontent.com/20393472/67143212-5995fb00-f269-11e9-84bf-9bcba1ac7898.png)

@ArneDeutsch Could you please take a look? Thanks a lot in advance!

**Comment by cdietrich** [comment]
@ArneDeutsch i have no idea where this is generated. maybe some eclipse magic?

**Comment by cdietrich** [comment]
ahh its the ProjectTemplateProcessor
which is an active annotation processor

**Comment by ArneDeutsch** [comment]
I have an solution but am not sure if we should implement.
The "Messages.java" is not generated by the generator but by an ActiveAnnotation in the generated code. In result it is not possible to read the configured value from the mwe2 file. The usesr could also place the ActiveAnnotation at some other class that is not linked to mwe2 at all (just to make it clear that there is really no connection possible).

A solution/workaround would be to copy the file header comment from the original Xtend file. In our case this would be the desired effect, the generated "Messages.java" would contain the configured file header comment. Implemented this and it works. But there is a drawback. The generated "Messages.java" is potentially generated from two or more classes (FileTemplateProvider and ProjectTemplateProvider in our case). If the user modifies the comment in one of these classes the "Messages.java" would contain this modified comment. And if the user then modifies the other file, the comment in "Messages.java" would toggle. This might lead to unwanted dirty flags in version control. I tend towards accepting the missing header comment and do not implement this. Your opinion?

**Comment by cdietrich** [comment]
for me this would not be a workaround but the correct solution. we might also add a string param with the header to the aa which would be another option

**Comment by cdietrich** [comment]
@szarnekow @miklossy  what do you think

**Comment by szarnekow** [comment]
The `Messages.java` should get the header of the class that contains the processed annotations. So I'm on the same page with Christian and Arne's proposal

**Comment by ArneDeutsch** [comment]
Not sure if you get my comment completely. Just to make this crystal clear:
"Messages.java" is NOT generated by only ONE file. Multiple files of the same package contribute to the contents. If the file comments in these classes are not identical, the comment in the generated "Messages.java" will be "random" (the commment from the last edited xtend file).

**Comment by szarnekow** [comment]
Understood. Let's not make it random but use a sorted list (by compilation unit path) and use the first docComment that's found.

**Comment by miklossy** [comment]
I am agree with @szarnekow

**Comment by ArneDeutsch** [comment]
I think accessing all the classes that contribute would complicate the code a lot. Because I have only the one class that I currently process in hand. It reads the existing file and adds/updates his own strings but rewrites the rest of the file from scratch. I could potentially scan the existing file (if any) using regex magic and avoid touching the comment this way, but that also would be quite briddle.

If you want to have a look the relevant code is in `org.eclipse.xtext.ui.wizard.template.TemplateProcessor` (especially `generatePropertiesFile` and `generateMessagesClass`).

**Comment by ArneDeutsch** [comment]
Thinking more about this, I guess that reading the old file, if it is there reading the header comment from that using regex and only write the new comment if there is no existing file would probably be the best way.

**Comment by szarnekow** [comment]
:+1: Sounds good to me

**Comment by ArneDeutsch** [comment]
Surprising: old implenmentation of getDocComment was like this:

```
	override getDocComment() {
		throw new UnsupportedOperationException("Auto-generated function stub")
	}
```

**Comment by miklossy** [comment]
Nice work @ArneDeutsch ! I have just tested it with the Xtext Statemachine example and your fix works like a charm! Thanks a lot!
