### ISSUE TITLE
Xtext Wizard Fragment: add file extension combo box to the New File Wizard

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1231]
Currently, there is no possibility to select the file extension on the generated New File Wizard.

![screenshot](https://user-images.githubusercontent.com/20393472/67157082-2ca81d80-f327-11e9-95a2-e6311589d043.png)

However, some languages (e.g [GEF DOT](https://github.com/eclipse/gef/wiki/DOT-User-Guide) support more than one file extensions (e.g `*.dot`, `*.gv`). 

I suggest to extend the New File Wizard page by a combo box containing all the file extensions to enable the user to select the appropriate one. The primary file extension should be selected by default.

@ArneDeutsch Could you please take a look? Thanks a lot in advance!

**Comment by szarnekow** [comment]
The combobox should be hidden, if the language has only one file extension.

**Comment by miklossy** [comment]
I think it would be better to show the combobox even if the language has only one file extension. In such cases the combobox will contain only one element, so it will not be possible to select an other one. In such way we would make the file extension more visible (transparent) on the wizard page. Otherwise the user will see the file extension only after the file has been created.

**Comment by szarnekow** [comment]
I don't buy this. Would you expect the 'New Java Class' wizard to show a combobox with a file extension to make it more transparent that a Java class has the file extension java?

**Comment by cdietrich** [comment]
there is also the question: do you want have 1 wizard for n extensions or n wizard for 1 file extension each

**Comment by ArneDeutsch** [comment]
I would suggest to add the combobox specific for DOT (and other projects that need it) by using a parameter. Should be quite easy. And change nothing in the general case. Because in many scenarios the user ust don't care.

**Comment by ArneDeutsch** [comment]
Will not be done in the framework but on langauge specific extensions.
