### ISSUE TITLE
Outline view's context menu doesn't show

### ISSUE THREAD

**Issue by joeseibel** [eclipse/xtext-eclipse#1252]
When working with multiple files, the outline view enters a state in which the context menu will not show for certain files. I am able to reproduce this behavior for any Xtext language.

Steps to reproduce:

1. Open any Xtext file such as an Xtend file.
2. Open another file.
3. Switch back to the first file and right-click in the outline view. The context menu will NOT show.
4. Switch back to the second file and right-click in the outline view. The context menu will show.

In general, the context menu will only show for the most recently opened file. A workaround is to close the file and reopen it. This behavior is reproducible with 2.19 and Eclipse 2019-09, but not with 2.17 and Eclipse 2019-03. I did not test with 2.18.

**Comment by cdietrich** [comment]
i can confirm that, i have no clue what could cause this.

**Comment by cdietrich** [comment]
testing with

Version: 2019-12 (4.14)
Build id: I20191102-1800

it seems to work again
@joeseibel could you retest with 2019-12 M2
?

**Comment by joeseibel** [comment]
I can confirm that it works again in 2019-12 M2.

**Comment by cdietrich** [comment]
Thus I will close this issue
