### ISSUE TITLE
Clean up project org.eclipse.xtext.releng

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#129]
The project contains some files which are obsolete with the new project structure and changes to the build.

All files that are not relevant for the current releng process should be removed.

**Comment by cdietrich** [comment]
hmmm any idea what still needs to be removed?

**Comment by kthoms** [comment]
There are quite some candidates left.
- Is Buckminster still relevant? Don't think so. => *.cquery,*.mspec,*.rmap,*.def
- releng/ant
- launch configs

Let's leave this up to @dhuebner to throw away what is not used for releng anymore.

**Comment by cdietrich** [comment]
ill delete the crap.

**Comment by cdietrich** [comment]
fixed in 2.18
