### ISSUE TITLE
Open Model Element Dialog: label for matches is cut

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1317]
Open Model Element Dialog: label for matches is cut

![Bildschirmfoto vom 2020-01-14 16-05-16](https://user-images.githubusercontent.com/238736/72355447-c9404880-36e7-11ea-9d4c-1ecd8a5caa4a.png)

**Comment by miklossy** [comment]
On Windows it looks like fine:
![image](https://user-images.githubusercontent.com/20393472/72420846-b6795280-377f-11ea-9c7e-affb0f57a9bf.png)

**Comment by cdietrich** [comment]
hmm i see the problem on different linux machines. will check on mac in the evening

**Comment by miklossy** [comment]
Fixed in 2.21.
