### ISSUE TITLE
Xtext Arithmetics Example: Add CodeMining Support

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1330]
The Xtext framework already provides API for CodeMining, see [Code Mining Support in Xtext](https://blogs.itemis.com/en/code-mining-support-in-xtext).

This feature should also be added to the Xtext Arithemtics Example.

**Comment by cdietrich** [comment]
isnt domain model example enhough?

**Comment by miklossy** [comment]
Fixed in 2.22.
