### ISSUE TITLE
Potential IndexOutOfBounds in org.eclipse.xtext.ui.editor.findrefs.ReferenceSearchResultContentProvider.expandToFirstChild()

### ISSUE THREAD

**Issue by riederm** [eclipse/xtext-eclipse#1336]
https://github.com/eclipse/xtext-eclipse/blob/783a40e6f7acb26d9cffdd58d9c377f55f587f3a/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java#L216

While updating some of my company's code to a newer Xtext-Version my collegue found a Bug in a contribution that I did couple of weeks ago.
In fact the check of course needs to be

`firstChildren.length > 0`, not `>= 0`. 
The next line will access firstChildren[0] whic leads to a IndexOutOfBounds-Exception.

Most implementations will not face this problem, we're lazy initialization of the node's children, which can lead to this situation where we see no children.

**Comment by miklossy** [comment]
Thanks for the bug report @riederm ! Would be nice if you could cone up with a PR containing the fix.

**Comment by riederm** [comment]
wow you're fast :-D

**Comment by riederm** [comment]
PR is here: https://github.com/eclipse/xtext-eclipse/pull/1337

**Comment by miklossy** [comment]
Thank you Matthias for the bug report and for the fix!

Fixed in 2.21.
