### ISSUE TITLE
Editor-Search in undo operation cannot handle multiple editors for same input

### ISSUE THREAD

**Issue by rytina** [eclipse/xtext-eclipse#1340]
The Xtext Editor Undo operation throws an ClassCastException when the same input of an Xtext editor is also opened in a non-text editor (i.e. MultiPageEditorPart instead of ITextEditor). The following video  shows how to to reproduce this bug with two simple DSL's and a EMF model editor
https://drive.google.com/file/d/1hg1693KhNRG1VbFajCZ70Ecmt26yx7Eb/view

**Comment by cdietrich** [comment]
@rytina this is the issue fixed by https://github.com/eclipse/xtext-eclipse/pull/1335 correct?

**Comment by rytina** [comment]
Yes correct

**Comment by cdietrich** [comment]
fixed in 2.21
