### ISSUE TITLE
Full build because of a class path reorder

### ISSUE THREAD

**Issue by lsotnk** [eclipse/xtext-eclipse#1362]
Hi.

I'm not sure whether this is a bug.

We experience sporadic full builds of all xtext projects on startup of eclipse. Because of a classpath change ProjectClasspathChangeListener is triggered, which then schedules a build. The classpath change is just a reordering of two dependent plug-ins (flag IJavaElementDelta.F_REORDER).

org.eclipse.xtext.ui.util.JavaProjectClasspathChangeAnalyzer.isRelevantPackageFragmentRootChange(IJavaElementDelta) considers a reordering as relevant. Is this correct behavior?

**Comment by szarnekow** [comment]
Generally speaking it is correct behavior. The classpath is order dependent. If you have two jars on the CP that contain the same packages in different versions, the order matters.
However, there is certainly room for improvement. Question is: how often do you change the order of classpath entries?

**Comment by lsotnk** [comment]
Ok, thanks.

I have to investigate why a reordering is happening in the first place.

The issue can be closed.

**Comment by lsotnk** [comment]
The source of the reordering was a bug in PDE: https://bugs.eclipse.org/bugs/show_bug.cgi?id=560822
