### ISSUE TITLE
Field names in TokenTypeDefDetailsPart are not localizable

### ISSUE THREAD

**Issue by masofcon** [eclipse/xtext-eclipse#1382]
I am using Eclipse Babel project to localize Eclipse plugins.
But there is no opportunity to localize syntax coloring preference page, generated by Xtext, because TokenTypeDefDetailsPart has non localizable field names

**Comment by cdietrich** [comment]
Contributions are welcome

**Comment by masofcon** [comment]
@cdietrich OK, I will try to make a patch

**Comment by cdietrich** [comment]
Fixed in 2.22
