### ISSUE TITLE
Consolidate proposal provider API and adjust it to the generic IDE one

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#139]
Currently, if one would like to support the same content proposal logic for both Eclipse IDE and a generic IDE (for instance Web), then one would have to maintain the same logic in two different places.

Based on the current state of Xtext, the Eclipse one is available at `MyLanguageProposalProvider` in the `*.ui` bundle while the generic IDE one is located at `MyLanguageIdeContentProposalProvider` (extending the `IdeContentProposalProvider` class)  in the `*.ide` bundle.

Although the two APIs seem to be very similar, there are no easy, or convenient ways to use and maintain the same logic at one place.

Preferably, there should be an adapter, and the Eclipse-based implementation could only just delegate in the generic IDE one. In a nutshell; we need an API with a unified content assist context and a generic acceptor for the completion proposals. Other API changes might be required as well.

**Comment by chetanladdha** [comment]
Do we have any plan for this consolidation? 
Xtext generates LSP based on IDE module, it would be great to have one consolidated logic instead of migrating similar logic from UI module to IDE module ?

**Comment by tivervac** [comment]
I suppose this can be closed now @kittaakos ? see #287

**Comment by kittaakos** [comment]
Closed via #287. Thanks for the PR!
