### ISSUE TITLE
Xtext Editor: 'Create rule' quickfix adds Linux line separator even on Windows.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1391]
When applying the `Create Rule ` quickfix on Windows, the newly created rule contains Linux line separators on Windows. Reproducible with the Xtext MyDsl example:
![screencast](https://user-images.githubusercontent.com/20393472/78471993-c4fb5880-7735-11ea-943c-8085cdfe1daa.gif)

**Comment by miklossy** [comment]
Fixed in 2.22

**Comment by szarnekow** [comment]
It’s unfortunately not correct to use the system line delimiter.

**Comment by miklossy** [comment]
Thanks for the feedback @szarnekow ! I created the corresponding PR to use the `document.getLineDelimiter` instead of the `System.lineseparator`.

**Comment by miklossy** [comment]
Fixed in 2.22
