### ISSUE TITLE
Xtext Outline View - Return type styling

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1399]
Currently, the styling of the rule's return types is not very aesthetic (at least on Windows)
![screenshot](https://user-images.githubusercontent.com/20393472/79064355-79522d00-7ca8-11ea-80bf-2b02c3b1f524.png)

@cdietrich Could you upload a screenshot how it currently looks like on Mac?

I would suggest to use the same styling for the rule's return types as JDT does for the method's return type
![screenshot2](https://user-images.githubusercontent.com/20393472/79064376-b3233380-7ca8-11ea-9869-6c3f9f8d2f33.png)

**Comment by cdietrich** [comment]
linux

![Bildschirmfoto_2020-04-12_10-44-19](https://user-images.githubusercontent.com/238736/79064610-a43d8080-7caa-11ea-9d9c-6b0623f0cf11.png)

**Comment by cdietrich** [comment]
mac

![Bildschirmfoto 2020-04-12 um 10 46 06](https://user-images.githubusercontent.com/238736/79064641-dea71d80-7caa-11ea-8b3a-f0f8f006362c.png)

**Comment by miklossy** [comment]
Fixed in 2.22
