### ISSUE TITLE
Make Content Assist tests work with Oracle and OpenJdk

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#14]
Some Content Assist tests currently fail with Oracle JDK cause then JavaFix Types will be availaible and found by Content Assist

**Comment by kthoms** [comment]
This issue is adressed in eclipse/xtext-eclipse#150, by 57563c72fe24963c79a8ae3a08e92c4bdf08d6b1

**Comment by kthoms** [comment]
Fixed via bdb0427f8d7171a58b3d99cd7bbf8f7da7fd9bff
