### ISSUE TITLE
Mark the entire org.eclipse.xtext.junit4 project as deprecated

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1430]
The `org.eclipse.xtext.junit4` project has been superseded by the `org.eclipse.xtext.testing` and `org.eclipse.xtext.ui.testing` projects. However, not all classes/interfaces are marked as deprecated in the deprecated project. Moreover, some element of the deprecated `org.eclipse.xtext.junit4` project is still in use in the Xtext code-base, e.g:
<img width="894" alt="Screenshot 2020-05-05 at 09 22 40" src="https://user-images.githubusercontent.com/20393472/81047513-d82b5080-8eba-11ea-964f-16268850d32e.png">

- [ ] Eliminate the usages of the to-be-deprectated code from the Xtext code-base to show that the "new" solution is working at least as good as the old one. 
- [ ] Add a package-info to all the packages in the deprecated bundle, and mark the entire package as deprecated with a hint that points to its new equivalent.
- [ ] We should also figure out a migration path for the tests, though. 

See also https://github.com/eclipse/xtext-eclipse/pull/1424#discussion_r419921910

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
