### ISSUE TITLE
Move `CopyQualifiedNameService` and its default implementation to core

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#145]
Currently, the `CopyQualifiedNameService` and its default implementation (`DefaultCopyQualifiedNameService`) are in the `org.eclipse.xtext.ui.editor.copyqualifiedname` package although it does not use anything from the UI. When one would like to reuse this service from the core or the generic IDE plug-in, it is not possible. I would recommend to move it to the core. If my recommendation is accepted, I am happy to create a PR with the changes.

The other benefit of moving the service to the core would be to be able to test it as a pure `JUnit Test` instead of a `JUnit Plug-in Test`.

To not to break any APIs, we could create a new service in the core and just delegate into it from the UI. But I am more than open to any other approaches.

**Comment by cdietrich** [comment]
What about subclassing as we did for IResourceClusteringPolicy

**Comment by kittaakos** [comment]
I do not understand that. Maybe I gave insufficient information what I would like to achieve:

I would like to test my custom `CopyQualifiedNameService` implementation as a pure `JUnit Test` instead of the `JUnit Plug-in Test`. When I run a `JUnit Test`, I cannot use the UI injector provider, but my custom service implementation has its binding in the UI module. Does that clarify my problem? If no, or you still think your previous recommendation should still work, then please give some more details about your proposal. Thanks!

**Comment by cdietrich** [comment]
Introduce a new interface and impl and let the old ones extend the new ones

**Comment by cdietrich** [comment]
Instead of delegating

**Comment by kittaakos** [comment]
Ah, OK. Even better. If you thing that would make sense, I could create the PR.

**Comment by cdietrich** [comment]
For me it would be ok what do others think?

**Comment by kittaakos** [comment]
OK, then I prepare it, and then others can look into the PR as well. Thanks for the advice!

**Comment by kthoms** [comment]
Sounds good as proposed!

**Comment by ArneDeutsch** [comment]
Created two push requests:
- https://github.com/eclipse/xtext-core/pull/599
- https://github.com/eclipse/xtext-eclipse/pull/512

Implemented the move as suggested. Target package for new classes is "org.eclipse.xtext.naming".  Not sure how to test this propertly, open for suggestions.

**Comment by ArneDeutsch** [comment]
I've renamed the Interface as requested and avoid internal usage of deprecated classes wherever possible without breaking API compatibility. Tested that eclipse "Copy Qualified Name" actions continue to work as expected. Documented API. Have left package at "org.eclipse.xtext.naming" (making API public) as suggested by Sebastian.

**Comment by ArneDeutsch** [comment]
Added a third related pull request: https://github.com/eclipse/xtext-xtend/pull/339

**Comment by kthoms** [comment]
All PR's approved and merged. Thanks, Arne!
