### ISSUE TITLE
XtextBuilder might miss OperationCanceledException

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1476]
If the build is cancelled in the last `BuilderParticipant` in `RegistryBuilderParticipant` after the doGenerate call and e.g. Parallel Generation is used for that one, then it might happen that the Parallel Build is actually cancelled (after check for last element in `org.eclipse.xtext.builder.ParallelBuilderParticipant.doBuild(List<Delta>, Map<String, OutputConfiguration>, Map<OutputConfiguration, Iterable<IMarker>>, IBuildContext, EclipseResourceFileSystemAccess2, IProgressMonitor)`) , but the main/autobuild thread is not 
then some generation might be missed but build is flagged as completed on XtextBuilder side

i propose to do an additional check for cancellation at end of 
org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(IBuildContext, IProgressMonitor)

@szarnekow what do you think?

**Comment by szarnekow** [comment]
> an additional check for cancellation at end

Yes, that sounds correct to me.

**Comment by cdietrich** [comment]
Fixed in 2.23
