### ISSUE TITLE
Update Eclipse Help projects from website documentation

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-eclipse#149]
The HTML content of the doc projects is generated with Jekyll from the Markdown sources of the website.

**Comment by cdietrich** [comment]
maybe this could address https://github.com/eclipse/xtext/issues/1091

**Comment by spoenemann** [comment]
Done.

**Comment by cdietrich** [comment]
@spoenemann will you do the same for xtend?

**Comment by spoenemann** [comment]
Done.
