### ISSUE TITLE
DirtyStateEditorSupportIntegrationTest does not work on Mac/(Sometimes)Windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1490]
DirtyStateEditorSupportIntegrationTest does not work on Mac

@miklossy does it work on windows?

**Comment by miklossy** [comment]
Currently I do not have the possibility to check.
@ArneDeutsch Could you try it out on Windows?

**Comment by cdietrich** [comment]
Test is fine one windows

**Comment by cdietrich** [comment]
i have no clue what is happening here.
maybe the test should be done in a completely different way

**Comment by cdietrich** [comment]
have no clue ....

**Comment by cdietrich** [comment]
also fails on windows for me
@nbhusare does it work for you?

**Comment by cdietrich** [comment]
have the feeling it depends which window is is foreground (hands of mouse and keybord, so that does not influence)

**Comment by cdietrich** [comment]
also fails on linix sometimes

**Comment by cdietrich** [comment]
Fixed in 2.26
