### ISSUE TITLE
Give the IProjectCreator.getResult() method a more meaningful name

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1504]
I would suggest to create a new method `IFile getFileToOpen();` in the [IProjectCreator](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/IProjectCreator.java) interface and deprecate the `IFile getResult(); ` method in favor of the new one.

See also the corresponding [javadoc comment](https://github.com/eclipse/xtext-eclipse/blob/955c8c1fe734fdff25e7b12608be91146833eddf/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/IProjectCreator.java#L39-L43) 

@drkstr101 Would be awesome if you could take care of this issue.

**Comment by szarnekow** [comment]
Please keep in mind that this interface exists since 2.4. deprecating the method is probably not sufficient. All call paths in the framework need to honor the fact that clients may have overridden the original getResult method. The change may not carry its own weight.

**Comment by szarnekow** [comment]
The best we can do is probably adding a default method to the interface with the better name and continue using getResult in all implementations but use the new method where we ask for the file from the outside.

**Comment by Yogendra0Sharma** [comment]
@szarnekow can I work on this issue? Please assign it to me. Thanks

**Comment by szarnekow** [comment]
Sure thing, first come first serve :) Sorry @drkstr101, but @Yogendra0Sharma was slightly faster.

**Comment by drkstr101** [comment]
Cheers mate! The early bird gets the worm. :)

**Comment by cdietrich** [comment]
any update here?

**Comment by cdietrich** [comment]
move to 2.26.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
