### ISSUE TITLE
Improve AbstractMultiQuickfixTest separator

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1505]
The Xtext UI test infrastructure for testing multi-quickfixes (class [AbstractMultiQuickfixTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractMultiQuickfixTest.java)) uses the  `----` characters to separate the waring/error messages from the actual DSL file content. Currenly, the length of this separator is dynamically calculated: it has the same length as the longest line in the DSL text (see the [EqualsWithNullMultiQuickfixTest](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend) and the [RemoveUnnecessaryModifiersMultiQuickfixTest](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend) test cases in the Xtend code base).

This approach is hard to maintain (see [feedback](https://github.com/eclipse/xtext-xtend/pull/1085#issuecomment-668594852) from @drkstr101) and need to be improved.

My suggestions would be:
- use fix (e.g. 5) number of the `-` characters as separator
- use another kind of separator (e.g. one or two empty lines)
- do not use any separator at all

@cdietrich @szarnekow @ArneDeutsch @kthoms : Do you have any preference?

@drkstr101 Would be awesome if you could take care of this issue.

**Comment by szarnekow** [comment]
I'm fine with a fixed length delimiter, e.g. `-----` as proposed as option (1).

**Comment by drkstr101** [comment]
@miklossy This is now my current task (starting tomorrow morning). I will do some brainstorming tonight.

Cheers!

**Comment by drkstr101** [comment]
@miklossy I am catching up on OSS commitments the whole rest of this week.  Has this API gone out to the public yet, or is there still time to rework it?

**Comment by miklossy** [comment]
@drkstr101 The [AbstractMultiQuickfixTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractMultiQuickfixTest.java) is part of the public Xtext UI Testing API since Xtext 2.23 (released on 2020-09-01). However, as long as the class is marked as `@Beta`, it can be changed without any risk.

Would be awesome if you could take care of this issue for the Xtext 2.24 release (planned to be released on 2020-12-01).

**Comment by drkstr101** [comment]
Good deal, I will give it a solid effort! The concept itself should be fairly easy to implement once we can pin down what all needs to be changed. 

By tomorrow I should either have either a rough idea of what needs to happen or more likely, some specific questions on point.

**Comment by miklossy** [comment]
> 
> 
> what all needs to be changed
> 

- Change the separator length calculation logic in the [AnnotatedTextToString](https://github.com/eclipse/xtext-eclipse/blob/0a54dd31c3ea2e361a0c4bc4e8912ce92294cc42/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/AnnotatedTextToString.java#L165) class to use  fixed length delimiter: `-----`
- Search for the usage of this class in the Xtext code base to indentify which test cases are affected by this change and adapt those test cases as well.
- Create a PR with your change and observe if it can be built successfully and whether all test are passing.

**Comment by drkstr101** [comment]
You are the best, thanks for the head start! =D

**Comment by drkstr101** [comment]
I apologize, but I seem to be having trouble provisioning the workspace, which fails after the "variables" screen with this:

    ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at
     https://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-jdt-compiler/content.xml.
    javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

I have tried all the options RE git/https+rw/https+ro, but they all led to the same result.

I have 2-factor auth turned on in GitHub with both SSH and GPG keys configured correctly for CLI usage.

Any idea what I did wrong here this time around?

**Comment by miklossy** [comment]
@cdietrich Any idea?

**Comment by drkstr101** [comment]
I think Eclipse didn't like my PGP key or something along those. I noticed I couldn't authenticate with GitHub when pushing to my own repo. However, after generating a new one from within Eclipse and adding it to GitHub I was. I think this is now in the secure store for all Eclipse, so I will attempt to provision again and see if that made any difference.

**Comment by cdietrich** [comment]
Please use older or newer oomph or replace the vm arg in oomphs eclipse ini
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567050

**Comment by drkstr101** [comment]
Thank you!! I also happened to be using a brand new 2FA enabled auth identity and a new machine to boot, so I couldn't pinpoint it down out of the many things that could be wrong with that setup.

I'll take another stab at this first thing in the morning. Cheers, all!

**Comment by cdietrich** [comment]
removed milestone

**Comment by cdietrich** [comment]
@miklossy is this fixed now?

**Comment by miklossy** [comment]
There is also adjusments needed in the Xtend repository. I am just about to create a corresponding PR.

**Comment by cdietrich** [comment]
fixed in 2.25
thx for the fix @miklossy
