### ISSUE TITLE
Replace the hard-coded \t (tab) character with o.e.x.formatting.IIndentationInformation in the XtextGrammarQuickfixProvider

### ISSUE THREAD

**Issue by nbhusare** [eclipse/xtext-eclipse#1527]
PS - https://github.com/eclipse/xtext-eclipse/pull/1507#discussion_r475400146

**Comment by nbhusare** [comment]
@miklossy I'll work on this issue as I had made the original fix.

**Comment by cdietrich** [comment]
@nbhusare is this done now?

**Comment by nbhusare** [comment]
@cdietrich Yes, its done.

**Comment by cdietrich** [comment]
Fixed in 2.24
