### ISSUE TITLE
Avoid the quickfix to create a terminal fragment where the fragment usage would be illegal

### ISSUE THREAD

**Issue by nbhusare** [eclipse/xtext-eclipse#1528]
PS - https://github.com/eclipse/xtext-eclipse/pull/1507#discussion_r475397673

**Comment by nbhusare** [comment]
@miklossy I'll work on this issue as I had made the original fix.

**Comment by cdietrich** [comment]
@nbhusare is there anything left

**Comment by nbhusare** [comment]
@cdietrich nothing is left in this PR

**Comment by cdietrich** [comment]
fixed in 2.24
