### ISSUE TITLE
IWorkbench Nullable in GlobalURIEditorOpener

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#153]
`GlobalURIEditorOpener` contains following code

```
	@Inject(optional=true) 
	/* @Nullable */
	private IWorkbench workbench;
``` 

this will not work if `IWorkbench` is provided as null at runtime.

guice will allow null if any `@Nullable` annotation is present at the class. 

thus: would it be possible to annotate our own Nullable annotation there (and potential other places as well - at least those needed to start a eclipse without a workbench / headless)

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=437425 as well

**Comment by cdietrich** [comment]
@svenefftinge @spoenemann what do you think?

**Comment by cdietrich** [comment]
see https://github.com/google/guice/wiki/UseNullable for an explanation

**Comment by spoenemann** [comment]
I'm fine with adding a `@Nullable`, but only for the cases where it affects the semantics of Guice injection like here. We should avoid to apply the annotation arbitrarily.

**Comment by cdietrich** [comment]
👍

**Comment by cdietrich** [comment]
would the `org.eclipse.xtext.util.internal` package be ok for that?

**Comment by spoenemann** [comment]
Sounds good to me. Please add some Javadoc to the annotation explaining for which cases it should be used.
