### ISSUE TITLE
Deprecate classes in .xbase.junit in favor of .xbase.testing

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-eclipse#155]
I seem to understand that .xbase.testing should replace .xbase.junit (just like .xtext.testing is replacing .xtext.junit4), thus the classes in .xbase.junit should be deprecated.

However, before doing that, there are some classes that should be moved to .xbase.testing like org.eclipse.xtext.xbase.junit.evaluation.AbstractXbaseEvaluationTest and org.eclipse.xtext.xbase.junit.typesystem.TypeSystemSmokeTester.

But what about org.eclipse.xtext.xbase.junit.ui.AbstractXbaseContentAssistTest? That's related to Eclipse so I think it cannot be moved into .xbase.testing

**Comment by LorenzoBettini** [comment]
Related to https://github.com/eclipse/xtext-eclipse/issues/156

**Comment by LorenzoBettini** [comment]
Blocked by https://github.com/eclipse/xtext-extras/issues/100

**Comment by svenefftinge** [comment]
should go into 2.11 together with https://github.com/eclipse/xtext-extras/pull/103

**Comment by LorenzoBettini** [comment]
Fixed by https://github.com/eclipse/xtext-eclipse/pull/165
