### ISSUE TITLE
Not localizable hint for rename refactoring

### ISSUE THREAD

**Issue by masofcon** [eclipse/xtext-eclipse#1555]
Rename refactoring hint is hardcoded, see
https://github.com/eclipse/xtext-eclipse/blob/3cc3e8cfbfc2669de731ee742783aff57ded076c/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameRefactoringPopup.java#L237

Which makes it impossible to localize

**Comment by cdietrich** [comment]
@masofcon could you please provide a PR fixing the issue.

**Comment by masofcon** [comment]
@cdietrich yes, with pleasure

**Comment by cdietrich** [comment]
fixed in 2.24
