### ISSUE TITLE
Provide .xtext.ui.testing and .xbase.ui.testing plugins (?)

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-eclipse#156]
Since classes in .xtext.junit4 and .xbase.junit are being deprecated in favor of .xtext.testing and .xbase.testing, respectively, how will the classes for UI test in .xtext.junit4 and .xbase.junit be provided? Of course they cannot be copied in .xtext.testing and .xbase.testing since these are independent from Eclipse. Then, shouldn't we provide .xtext.ui.testing and .xbase.ui.testing where we copy the classes related to UI testing from the deprecated packages?

**Comment by cdietrich** [comment]
@LorenzoBettini is anything left on this?

**Comment by LorenzoBettini** [comment]
It has to be completely implemented... I waited for 2.11 to be released, then I can start working on that for the next releases
