### ISSUE TITLE
XAssignment not inherit from XAbstractFeatureCall, the xbase trick me a little

### ISSUE THREAD

**Issue by glandon** [eclipse/xtext-eclipse#1599]
I'm a little confused， why my XJAssignment not inherit from XAbstractFeatureCall????

**The follows from xbase and jbase:**

 * @see org.eclipse.xtext.xbase.XbasePackage#getXAssignment()
 * @model
 * @generated
 */
public interface XAssignment extends XAbstractFeatureCall

-----------------------------------------------------------------------------
@Override 
XAssignment returns XExpression :
	=>({XJAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] 
		'[' indexes+=XExpression ']'('[' indexes+=XExpression ']')*
		OpSingleAssign) value=XAssignment |	
	=>({XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] 
		OpSingleAssign) value=XAssignment |	
	XOrExpression (
		=>({XJConditionalExpression.if=current} '?') then=XExpression ':' else=XExpression
		|
		=>({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign]) rightOperand=XAssignment
	)?;

**Comment by cdietrich** [comment]
XJAssignment != XAssignment.
Don’t see in your grammar where
You make XJAssignment as subclass of XAssignment or XAbstractFeaturr call.

P.s. i would prefermifmyou use the forum or stackoverflow for questions

**Comment by glandon** [comment]
Thanks, maybe i also need manual modify the metamodel file, will have a try. 
I want make a python like feature for JNumpy, work hard on this.

**Comment by cdietrich** [comment]
you can also try to add an uncalled rule

```
XJAssignment returns XAssignment:
 {XJAssignment};
```

**Comment by glandon** [comment]
Could i implement Numpy NDArray set feature:  **a[i]=n -> a.set(i, n)** with binaryOperation?

@Override 
XAssignment returns XExpression :
	=>({XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] 
		OpSingleAssign) value=XAssignment |	
	XOrExpression (
		=>({XJConditionalExpression.if=current} '?') then=XExpression ':' else=XExpression
		|
		=>({XJArrayOperation.leftOperand=current} '[' indexes+=XExpression feature=[types::JvmIdentifiableElement|']=']) rightOperand=XAssignment
		|
		=>({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign]) rightOperand=XAssignment
	)?;

XJArrayOperation returns XBinaryOperation:
 {XJArrayOperation};

-------------------------------------------------
@SuppressWarnings("deprecation")
public class XJArrayOperationImpl extends XExpressionImpl implements XJArrayOperation

------------------------------------------------
Not worked.

**Comment by cdietrich** [comment]
public interface XJArrayOperation extends XExpression, XBinaryOperation
{

works perfectly fine for me

**Comment by glandon** [comment]
Now, below code worked well, i will try imp array set featur with binaryOp, that's possible?

`python`
var a = np.arange(12).reshape(3,4)
var b = 1+a[0:-2]
b.dump()

var c = np.ones(3,4)
var d = a+c/2
d.dump
			
var f = a<4
f.dump()

shape=(1, 4)
array=
array([[1, 2, 3, 4]])


shape=(3, 4)
array=
array([[0.5 , 1.5 , 2.5 , 3.5 ]
       [4.5 , 5.5 , 6.5 , 7.5 ]
       [8.5 , 9.5 , 10.5, 11.5]])


shape=(3, 4)
array=
array([[true , true , true , true ]
       [false, false, false, false]
       [false, false, false, false]])

**Comment by cdietrich** [comment]
sry. i dont have the time to work on this.

**Comment by glandon** [comment]
I setup the opensouce Java Numpy, and i want it can be used easily in future.
https://github.com/jdeepro/dl4j

**Comment by glandon** [comment]
Thank you, worked.
public interface XJArrayOperation extends XExpression, XBinaryOperation
