### ISSUE TITLE
org.eclipse.xtext.testlanguages vs org.eclipse.xtext.testlanguages.ui

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#16]
org.eclipse.xtext.testlanguages.ui is in xtext-eclipse the rest is not. it would be nice to ave a solution for that

**Comment by spoenemann** [comment]
What problem would you like to solve? Has testlanguages.ui been generated from the testlanguages that are now in xtext-core?

**Comment by cdietrich** [comment]
I don't know. I just want it to be checked that it works and nothing gets lost or stale

**Comment by spoenemann** [comment]
Let's reopen this when we face a problem with the current setup.
