### ISSUE TITLE
XtextEditor.init throws unwarranted PartInitException

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-eclipse#1627]
Judging from the implementations of other well-behaved editors, init should not check the editor input for `#exists`. The PartInitException will lead to an error editor whereas the default behaviour is more pleasant for the user. 

The change to the XtextEditor from https://github.com/eclipse/xtext-eclipse/commit/2663f3e423e2fe7346058315f70a43318a677172 should probably be reverted.

**Comment by cdietrich** [comment]
@szarnekow will you provide a patch next week or should we move to 2.26?
