### ISSUE TITLE
Content assist in EmbeddedEditor behaves unexpectedly

### ISSUE THREAD

**Issue by uruuru** [eclipse/xtext-eclipse#166]
There seems to be an issue with the ``EmbeddedEditor`` and content assist.

Consider the following grammar: 
```
ElkNode returns ElkNode:
    identifier=ID ('{'
        properties+=Property*
    '}')?;
Property returns ElkPropertyToValueMapEntry:
    {ElkPropertyToValueMapEntry}
    key=PropertyKey ':' (value=STRING | value=QualifiedId | value=Boolean | value=SIGNED_INT | value=FLOAT);
[...]
```

And the following method of the proposal provider:
```
override completeProperty_Value(EObject model, Assignment assignment, 
        ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        [...]
}
```

Let the file extension of the grammar be `lc`. When I create a file `dummy.lc`, open it in the regular xtext editor, and trigger content assist after the colon, 
the `model` element passed to the `completeProperty_Value`
method is of type `ElkPropertyToValueMapEntryImpl`, as one would expect. 
As soon as I trigger content assist within the embedded editor however, an `ElkNode` is passed as `model`.

**Comment by cdietrich** [comment]
@uruuru  i am getting ElkPropertyToValueMapEntryImpl in embedded editor as well. can you please provide a complete reproducible example? (e.g. a view)

**Comment by uruuru** [comment]
@cdietrich I think I found the issue. There was a call to the standalone setup in the resource provider (see below). I have no idea why it has been there, but it looks like it didn't cause any issues with older xtext versions, nor with the "default" editor. 
Sorry for that.

```
    /** Resource Provider for the embedded editor. */
    private IEditedResourceProvider resourceProvider = new IEditedResourceProvider() {
        public XtextResource createResource() {
            try {
                LayoutConfigStandaloneSetup.doSetup();
                ResourceSet resourceSet = new SynchronizedXtextResourceSet();
                resource = resourceSet.createResource(URI.createURI("dummy.lc"));
                return (XtextResource) resource;
```

**Comment by spoenemann** [comment]
> LayoutConfigStandaloneSetup.doSetup();

StandaloneSetup must *never* be called in an Eclipse context.

So the content assist works properly if you remove that line? In that case, please close this issue?
