### ISSUE TITLE
In case of IBuildFlag.RECOVERY_BUILD the default BuildScheduler only discards the build state but does not rebuild

### ISSUE THREAD

**Issue by rytina** [eclipse/xtext-eclipse#1676]
The reason for this is the following if condition which checks if the scheduler is equal to the default implementation (BuildScheduler.class.equals(getClass())) besides checking the build flags length and after discarding the build state it returns immediately without retriggering a build:

if (BuildScheduler.class.equals(getClass()) && buildFlags != null && buildFlags.length == 1) {
  if (builderStateDiscarder.forgetLastBuildState(toUpdate, toBuilderArguments(buildFlags))) {
    return;
  }
}

A workaround for this is customizing the scheduler, so it will not go into this check and will schedule a BuildJob(Messages.BuildScheduler_JobName, scheduleUs) in the successive code. @cdietrich and @szarnekow could you please comment on this. Thank you.

**Comment by cdietrich** [comment]
i assume it is this way forever and the code is there for backwards compatibility

**Comment by rytina** [comment]
No I don't know sorry. With the workaround I described above we can live for now, but it would be great if this gets fixed in Xtext. Thank you very  much!

**Comment by cdietrich** [comment]
i assume it is done the way it is done for a good reason.
lets wait what @szarnekow remembers

**Comment by rytina** [comment]
No problem, its not urgent :-)

**Comment by szarnekow** [comment]
I think what you are seeing is the same thing that is being fixed via https://github.com/eclipse/xtext-eclipse/pull/1671

**Comment by cdietrich** [comment]
@rytina could you downport and test that one?

**Comment by rytina** [comment]
Oh yes, that sounds exactly like #1671
So I would then close this as duplicate, ok?

**Comment by rytina** [comment]
>could you downport and test that one?

Yes I try, thank you :-)

**Comment by rytina** [comment]
Duplicates #1671
