### ISSUE TITLE
XtextGrammarRefactoringIntegrationTest does not run on jenkins

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#17]
investigate why XtextGrammarRefactoringIntegrationTest fails on jekins all the time

**Comment by spoenemann** [comment]
What's the state here?

**Comment by cdietrich** [comment]
Did not work on it for 4 weeks

**Comment by cdietrich** [comment]
unfortunately i cannot reproduce this on Mac nor on Linux Mint (Oracle JDK and OpenJDK)
so i am wondering whats special on our Jenkins environment

**Comment by cdietrich** [comment]
seems to work now

**Comment by cdietrich** [comment]
fixed in 2.13
