### ISSUE TITLE
Use atomic marker API

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/xtext-eclipse#1714]
Seen once during automated tests (and probably very hard to reproduce, since this depends on removing a project in parallel to running validation asynchronously on it):
```
org.eclipse.core.internal.resources.ResourceException: Marker id 6985 not found.
at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:83)
at org.eclipse.core.internal.resources.Marker.setAttribute(Marker.java:280)
at org.eclipse.xtext.ui.editor.validation.MarkerCreator.setMarkerAttributes(MarkerCreator.java:51)
at org.eclipse.xtext.ui.editor.validation.MarkerCreator.createMarker(MarkerCreator.java:32)
```
This can only be fixed easily when Xtext requires Eclipse platform 4.19, since there is new API for creating markers atomically in that version: https://www.eclipse.org/eclipse/news/4.19/platform_isv.php#marker-create-api

I'm also fine with the issue being closed (and later reopened, when 4.19 is a requirement).

**Comment by szarnekow** [comment]
Might be worthwhile to use reflection.

**Comment by cdietrich** [comment]
@Bananeweizen  see https://github.com/eclipse/xtext/issues/2500

**Comment by Bananeweizen** [comment]
Okay, closing as duplicate then, even though my main concern was the atomicity, not the performance. :) As said before, I don't expect normal users to run into this asynchronous issue at all (and I can fix this specifically for tests by avoiding the async execution there).

**Comment by cdietrich** [comment]
our integ test actually see the atomicity problem too
