### ISSUE TITLE
Quick Assist Change icon

### ISSUE THREAD

**Issue by v703612** [eclipse/xtext-eclipse#1750]
Hi,

We are trying to change the icon in the quick assist for our model language. What is the best way of doing this? We want different icon for quick assist for model and name. Is this in the Proposalprovider or is there easier way of doing this?
![image](https://user-images.githubusercontent.com/26733848/137719980-2dbd8728-31e1-490c-980f-62dcb87401a6.png)

Model:
	'model' '{' 'name' name=MODEL_ID

**Comment by cdietrich** [comment]
ping @v703612

**Comment by v703612** [comment]
thank you for the help
