### ISSUE TITLE
IgnoreBuildDirContribution looses buildDirs after Restart

### ISSUE THREAD

**Issue by rasifix** [eclipse/xtext-eclipse#1760]
We have observed by chance that XtextBuilder is building the DSL files in the Gradle "build" folder. When debugging I have come across the IgnoreBuildDirContribution. The "buildDirs" are properly initialized with a "Refresh Gradle Project". However, after a restart, the buildDirs are empty. Shouldn't those buildDirs be persisted somehow?

@cdietrich asked me to create an issue after my post on the Xtext forum and asked me to mention you, @oehme. Any ideas?

My current Xtext version is 2.25.0.v20210301-1429. The buildship version is 3.1.5.v20210113-0929 and we are currently on Eclipse 2021-09.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-eclipse/blob/ce395d6e9a6804dbae088aaf6a6a9d0cafd60dfb/org.eclipse.xtext.buildship/src/org/eclipse/xtext/buildship/IgnoreBuildDirContribution.java#L61

**Comment by szarnekow** [comment]
Good point. The maps could probably be replaced by a persistent property on the IFolder (see IFolder.setPersistentProperty)

**Comment by cdietrich** [comment]
@rasifix do you have a hint on how to best test/reproduce this?

**Comment by cdietrich** [comment]
@szarnekow  i assume we have the map so that we can easily remove all stuff from a project.
so would you store the dirs per project as a persistent property on the project?

**Comment by szarnekow** [comment]
@cdietrich exactly. Also the project may have been closed or deleted in which case the folder structure could not be navigated anymore. Yes, I'd attempt to store the dirs encoded as strings as a persistent property on the project.
On first access of the map, I'd read from the persistent property is nothing is in the map yet. On sync from gradle, the persistent prop would be added.

**Comment by cdietrich** [comment]
we right now know only one dir per property.
i will do a first draft to discuss

**Comment by cdietrich** [comment]
@rasifix would it be possible you give the patch a try?

**Comment by rasifix** [comment]
I would have to go through setting up Eclipse as described in https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md, right?

**Comment by cdietrich** [comment]
@rasifix simply import the buildship plugin as source from the plug-ins view any copy the patch over should be sufficient to test.
then start a runtime eclipse and test your usecase there.

**Comment by cdietrich** [comment]
@rasifix you also can find a repo containing the fix at 
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_issue1760/lastSuccessfulBuild/artifact/build/p2-repository/

**Comment by rasifix** [comment]
sorry it took me so long. I have finally tested it and it works perfectly fine. Thanks for the fix!

**Comment by cdietrich** [comment]
@rasifix thanks for testing

**Comment by cdietrich** [comment]
done
