### ISSUE TITLE
The info quickfix icon is slightly different from the warning and error quickfix icons

### ISSUE THREAD

**Issue by LGoossens** [eclipse/xtext-eclipse#1764]
This concerns the `quickfix_error_obj.gif`, `quickfix_warning_obj.gif` and `quickfix_info_obj.png` files under `org.eclipse.xtext.ui/icons/obj16/`.
  
The three icons:
![quickfix_icons](https://user-images.githubusercontent.com/54268882/144456861-3e186118-67b5-468a-abb9-b3cd416a8a21.gif)

**Comment by cdietrich** [comment]
@szarnekow do we considered checked in image files as api or can they safely be deleted?

**Comment by cdietrich** [comment]
@LGoossens can you please give https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_issue1764/lastSuccessfulBuild/artifact/build/p2-repository/ a try

**Comment by szarnekow** [comment]
>  image files as api ?

The names / paths of the images are API. Apart from that, improving the icons is ok and appreciated.

**Comment by cdietrich** [comment]
@szarnekow so keeping the old gifs?

**Comment by szarnekow** [comment]
> @szarnekow so keeping the old gifs?

Gut feeling: Unfortunately yes. The PluginImageHelper has the option to refer to images from other plugins, so we cannot be sure that no other code refers to the gifs.

**Comment by cdietrich** [comment]
fixed in 2.26.0
