### ISSUE TITLE
Fix broken Example Projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#177]
Fix broken Example Projects after xtext.ui.testing and xbase.ui.testing are done

**Comment by LorenzoBettini** [comment]
which example projects are broken? can they be fixed independently from the forthcoming .ui.testing bundles?

**Comment by cdietrich** [comment]
i have compile error in aritmetics and domain model ui tests

**Comment by cdietrich** [comment]
i assume they used to use the junit4 dep and no longer do

**Comment by LorenzoBettini** [comment]
You mean in the development workspace or when you import them as examples? In the latter case, I don't have any error...

**Comment by cdietrich** [comment]
i mean in the development workspace. this is how they will later look like

**Comment by LorenzoBettini** [comment]
I'm having a look...

**Comment by LorenzoBettini** [comment]
what do you mean by "this is how they will later look like"?

**Comment by cdietrich** [comment]
i mean you will create e.g. a autoedittest
=> there should be a dependency to the ui testing plugins
and it should use the classes from there?

**Comment by LorenzoBettini** [comment]
but there are no .ui.testing plugins yet (or am I missed something)? for UI testing the old .xtext.junit4 and .xbase.junit are still valid

**Comment by cdietrich** [comment]
yes i am/was not sure in which order we should fix these both problems
