### ISSUE TITLE
Replace log4j with log4j2 instead of reload4j

### ISSUE THREAD

**Issue by anschwar** [eclipse/xtext-eclipse#1811]
Hi,

as I didn't find any issue regarding log4j1 I decided to create one.

I read somewhere that the logging of xtext will be changed to reload4j which is a revived project descending from the original log4j which is end of life since 2015.

Are there any plans to migrate to log4j2 to get rid of the log4j1 dependency in eclipse RCP applications that use xtext?

Best regards

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/issues/2028 and https://github.com/eclipse/xtext-core/issues/1363

**Comment by szarnekow** [comment]
Hey @anschwar 
I'll close this ticket referring to the discussion that Christian linked here.
If - for some reason - you strictly need log4j2 as the logging backend, I'd recommend to use slf4j with its log4j facade in the frontend and log4j2 in the backend.
