### ISSUE TITLE
Have better explanation in logging

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/xtext-eclipse#1890]
https://github.com/eclipse/xtext-eclipse/blob/92c5dc5cbace37540d513e33dd3efccf946716c6/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/Activator.java#L87

Seeing this message let me search for a Guice problem. Changing the log level of "com.google.inject" without results.
Later I noticed the logger name and found the source and then understood the reason.

Would be nice if the logging message explains it directly.
Proposal:

    xtext.ui.shared: Multiple contributions to extension point 'org.eclipse.xtext.ui.shared.overridingGuiceModule'. Will use them in unspecified order.

Or even better if it would list the plugins from the contributions in the message. That would even more simplify the analysis.

**Comment by cdietrich** [comment]
Can you please open pr
