### ISSUE TITLE
Performance of EclipseResourceFileSystemAccess2.hasContentsChanged(IFile,Inputstream)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1911]
With Java 17 we see a 300% performance decrease in `EclipseResourceFileSystemAccess2.hasContentsChanged(IFile,Inputstream)`
it looks like FileInputStream (ususally used by `IFile.getContents`) does no longer work together with `BufferedInputStream` as it did before. (Measurements taken on Linux)

- does windows and mac have the same problem?
- do other places that use the same pattern have the same problem?

for us it looks like using a buffer and then compare the buffers (`Arrays.equals`) shows better performance, also on Java 11 compared to the current used bytewise compare

**Comment by cdietrich** [comment]
possible patch using Arrays.equals with indices wont work in J8

**Comment by iloveeclipse** [comment]
> it looks like FileInputStream (ususally used by IFile.getContents) does no longer work together with BufferedInputStream as it did before

Actually this is about using synchronized method in a loop which is now 3x slower thanks to disabled biased locking
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8231265

But nevertheless, even without this flag the old code was performing very poor compared with block wise array compare we have now, the difference is 10-15x faster with the patch also on Java 11.

**Comment by iloveeclipse** [comment]
> possible patch using Arrays.equals with indices wont work in J8

:-(

One can use hand written array compare loop on Java 8...

**Comment by iloveeclipse** [comment]
> possible patch using Arrays.equals with indices wont work in J8
> @szarnekow any idea how to circumvent this? reflective guard?

Now with your announcement in https://www.eclipse.org/lists/cross-project-issues-dev/msg19411.html we shouldn't care about Java 8 anymore, right?

**Comment by cdietrich** [comment]
yes but the comment by sebastian applies to both

**Comment by cdietrich** [comment]
fixed in 2.30
