### ISSUE TITLE
Remembered decision to add Xtext nature is irreversible

### ISSUE THREAD

**Issue by autumoswitzerland** [eclipse/xtext-eclipse#1921]
Remembered decision to add Xtext nature for a Gradle-Java-FX project when opening a CSS file is not reversible.

The function "Clear All 'Remember my decision' settings and show all hidden dialogs again" in "Preferences/Xtext" doesn't work either.

The project nature is always added to the project when a CSS is opened. File associations "tricks" don't work either it seems, everything is locked by e(fx)clipse.

MacOS: 10.14.6
Eclipse: Version: 2022-09 (4.25.0) / Build id: 20220908-1902

See attachment below for Xtext version (2.28).

![Bildschirmfoto 2022-11-03 um 23 26 40](https://user-images.githubusercontent.com/100039855/200018625-57c7f8ba-9c67-455a-9ca8-0f6f18324b66.png)

**Comment by cdietrich** [comment]
@tivervac any idea what broke here?

**Comment by tivervac** [comment]
@cdietrich Nope, no idea. Been too long since I touched the code to actually remember how it's supposed to work as well :/

**Comment by autumoswitzerland** [comment]
@cdietrich Not sure what you mean. I tried to change things for a CSS file in "File Associations" and "Content Types" in the eclipse Preferences. But nothing worked so far. It seems the decision is made on a project, not file and finally.

**Comment by autumoswitzerland** [comment]
See above.
