### ISSUE TITLE
CodeMining Problem

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1947]
I have experienced the following Code Mining problem.

Steps to reproduce (based on the Domainmodel example shipped with the Xtext framework):
1. Replace the the `DomainmodelCodeMiningProvider.java` file with the following content: 
```java
public class DomainmodelCodeMiningProvider extends AbstractXtextCodeMiningProvider {

    @Override
    protected void createCodeMinings(IDocument document, XtextResource resource, CancelIndicator indicator,
            IAcceptor<? super ICodeMining> acceptor) throws BadLocationException {
        
        if (resource.getContents().isEmpty()) {
            return;
        }
        
        // get all entities in the open document
        List<Entity> allEntities = EcoreUtil2.eAllOfType(resource.getContents().get(0), Entity.class);
        for (Entity e : allEntities) {

            // create code mining right after the entity name
            List<INode> nodes = NodeModelUtils.findNodesForFeature(e, DomainmodelPackage.Literals.ABSTRACT_ELEMENT__NAME);
            if (nodes == null || nodes.isEmpty()) {
                continue;
            }

            INode lastNode = nodes.get(nodes.size() - 1);
            int annotationOffset = lastNode.getEndOffset() + 1;

            acceptor.accept(createNewLineContentCodeMining(annotationOffset, "CodeMiningText"));
        }
    }
}
```
2. I would like to write the CodeMiningText right after the entity name. It works if the curly brace is in the same line as the entity name, but there is some problem if the curly brace is in the next line:
![screenshot](https://user-images.githubusercontent.com/20393472/204549803-a2fbba21-201b-4022-852f-7db6b87da493.png)

**Comment by cdietrich** [comment]
you should ask platform.

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=540448

**Comment by cdietrich** [comment]
please report upstream: https://github.com/eclipse-platform/eclipse.platform.text/issues

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2380
