### ISSUE TITLE
Jenkins OOMS for Java 17 + Eclipse 4.27

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1959]
Jenkins OOMS for Java 17 + Eclipse 4.27
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/3214/console

```
12:00:36  testCamelCase_03(org.eclipse.xtext.xbase.ui.tests.editor.ContentAssistReturnTest2)  Time elapsed: 0.081 s
12:00:36  Running org.eclipse.xtext.xbase.ui.tests.editor.ContentAssistFinallyTest
12:01:23  Exception in thread "Active Thread: Equinox Container: 9a2421ac-9094-44c9-88c2-23556f9abd43" java.lang.OutOfMemoryError: Java heap space
12:01:27  Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
12:01:45  Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
12:03:21  
12:03:21  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Java indexing"
12:04:08  
12:04:08  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-3-thread-3"
12:05:04  
12:05:04  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-4"
12:05:16  
12:05:16  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-3-thread-1"
12:06:13  
12:06:13  Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-5"
12:06:39  Tests run: 74, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 355.228 s <<< FAILURE! - in org.eclipse.xtext.xbase.ui.tests.editor.ContentAssistFinallyTest
```

`.log` file is here https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/3214/artifact/org.eclipse.xtext.xbase.ui.tests/target/work/data/.metadata/.log

**Comment by cdietrich** [comment]
TODO:
- can this be reproduced locally
- can we obtain a heapdump
- is this a regression in platform?

**Comment by cdietrich** [comment]
<img width="1755" alt="Bildschirmfoto 2022-12-06 um 12 53 02" src="https://user-images.githubusercontent.com/238736/205904851-419a36a7-2736-4ad9-a23a-e4a283f52d82.png">

have the feeling closing the editors does not longer work

**Comment by cdietrich** [comment]
no the document seems to leak somewhere else

**Comment by cdietrich** [comment]
@szarnekow do you have any platform change in mind that could cause this?

**Comment by iloveeclipse** [comment]
Since which IBuild is it? There were few PR's for platform text merged recently.
- https://github.com/eclipse-platform/eclipse.platform.text/pull/118
- https://github.com/eclipse-platform/eclipse.platform.text/pull/115

I haven't checked what is inside, but they seem to be big enough to introduce a leak somewhere.

**Comment by cdietrich** [comment]
the first time i observed it is today. need to check older logs

**Comment by iloveeclipse** [comment]
Regarding JDT: jdt.core tests run with 1 GB heap, and that was a good memory leak detector in the past, and there were no significant changes in JDT UI AFAIK

**Comment by szarnekow** [comment]
Looks like the jobmanager keeps a reference around?

**Comment by cdietrich** [comment]
dump can be found at 
https://drive.google.com/file/d/1qnFc-upkSQzK09sl68DOY3JWiWhGHa1-/view?usp=share_link

**Comment by cdietrich** [comment]
to me it looks like the pending jobs dont really reduce. but i also dont see a difference to older versions.

**Comment by cdietrich** [comment]
and of course i cannot oomph against older target :(

**Comment by cdietrich** [comment]
now it gets funny. i see the job list also grow in 2022-03. will take a snapshot there too

**Comment by cdietrich** [comment]
stacktrace where the job infos are created

```
JobInfo.<init>(Job) line: 57	
ProgressManager.lambda$14(Job) line: 613	
0x0000000800f77580.apply(Object) line: not available	
HashMap<K,V>.computeIfAbsent(K, Function<? super K,? extends V>) line: 1220	
ProgressManager.progressFor(Job) line: 613	
ProgressManager$1.updateFor(IJobChangeEvent) line: 502	
ProgressManager$1.scheduled(IJobChangeEvent) line: 474	
0x0000000800db9138.notify(IJobChangeListener, IJobChangeEvent) line: not available	
JobListeners.sendEvent(JobChangeEvent) line: 131	
JobListeners.sendEventsAsync(InternalJob) line: 118	
JobListeners.waitAndSendEvents(InternalJob, boolean) line: 78	
JobManager.withWriteLock(J, Function<J,T>) line: 524	
JobManager.schedule(InternalJob, long) line: 1373	
XtextReconciler(InternalJob).schedule(long) line: 396	
XtextReconciler(Job).schedule(long) line: 684	
XtextReconciler.resume() line: 345	
XtextReconciler$DocumentListener.assistSessionEnded(ContentAssistEvent) line: 180	
ContentAssistant.lambda$12(IContentAssistProcessor) line: 2521	
0x000000080188dd20.accept(Object) line: not available	
Collections$SingletonSet<E>.forEach(Consumer<? super E>) line: 4905	
ContentAssistant.fireSessionEndEvent() line: 2518	
CompletionProposalPopup.hide() line: 1110	
ContentAssistant.hide() line: 2267	
ContentAssistant.uninstall() line: 1609	
XtextSourceViewer(SourceViewer).uninstallTextViewer() line: 1346	
XtextSourceViewer(SourceViewer).unconfigure() line: 729	
XtextSourceViewer(SourceViewer).handleDispose() line: 789	
XtextSourceViewer(ProjectionViewer).handleDispose() line: 1303	
XtextSourceViewer(TextViewer).lambda$1(DisposeEvent) line: 1741	

```

**Comment by cdietrich** [comment]
on older versions
1st: org.eclipse.jface.text.contentassist.ContentAssistant.removeCompletionListener(ICompletionListener)
2nd : org.eclipse.jface.text.contentassist.ContentAssistant.fireSessionEndEvent()

on latest the remove seems not come before the fire

**Comment by cdietrich** [comment]
<img width="1374" alt="Bildschirmfoto 2022-12-06 um 18 08 58" src="https://user-images.githubusercontent.com/238736/205977043-b501efed-42d7-4065-b4ef-ccb2317d29c6.png">
<img width="1335" alt="Bildschirmfoto 2022-12-06 um 18 08 36" src="https://user-images.githubusercontent.com/238736/205977068-8ea1830a-4b9f-4a98-ab05-7a7a0b0987f7.png">
<img width="1742" alt="Bildschirmfoto 2022-12-06 um 18 10 17" src="https://user-images.githubusercontent.com/238736/205977323-5533745e-f52e-42dd-b304-9fc774804f69.png">


bingo: the old code removes the reconciler first, content assistant 2nd
the new does remove the content assistant first.

@iloveeclipse @angelozerr is this an intentional change with
https://github.com/eclipse-platform/eclipse.platform.text/commit/81a446557dd3f8f354a272de447fe787881dbe1f

**Comment by cdietrich** [comment]
@iloveeclipse @angelozerr should this be a linked hashset in platform instead?

**Comment by cdietrich** [comment]
i will have a look later. 

@szarnekow can you also check if there is something bogus with our reaction to the content assistant uninstall?

**Comment by szarnekow** [comment]
> I think it can be a good idea, is it working better with linked hash map?

I'd rather use a list and walk it backwards during uninstall.

**Comment by angelozerr** [comment]
> I'd rather use a list and walk it backwards during uninstall.

I created a PR https://github.com/eclipse-platform/eclipse.platform.text/pull/121

**Comment by cdietrich** [comment]
pr looks good
