### ISSUE TITLE
Oomph does not work with 202203 as target

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1960]
Oomph does not work with 202203 as target

```
 ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1670338921389
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1670338921389 requires 'org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 0.0.0' but it could not be found
```

@merks any idea where to start debugging?
is there a change in oomph that no longer makes this implicitely available?

**Comment by cdietrich** [comment]
<img width="415" alt="Bildschirmfoto 2022-12-06 um 16 12 42" src="https://user-images.githubusercontent.com/238736/205949934-36aefe2f-b806-48d1-80fa-deec784b9d39.png">

**Comment by cdietrich** [comment]
added the eclipse update site explicitely seems to help.

**Comment by merks** [comment]
Yes, because the necessary 2022-03 changes will not be committed until tomorrow morning.  Until then, you will be missing the platform's 4.26 repository.  It's really annoying this gap before the release day.  :-(

**Comment by cdietrich** [comment]
@merks it is "2022" not "2023"

**Comment by merks** [comment]
Sorry, for my confusion.  When I try that it does list the repo for that:

![image](https://user-images.githubusercontent.com/208716/205959014-f99ce7d3-a776-43a7-a39d-282cbb634767.png)

**Comment by cdietrich** [comment]
there do i find this?

**Comment by cdietrich** [comment]
@merks yes but e.g. here i dont see eclipse 2022-09
we dont have it explicitely anywhere and it seemed to have worked before but now no longer does

<img width="554" alt="Bildschirmfoto 2022-12-06 um 17 15 09" src="https://user-images.githubusercontent.com/238736/205964849-eed1a80f-49c5-4c3f-add5-bfa26e2f295d.png">

**Comment by merks** [comment]
Now you show  2022-09 but the issue mentions 202203.  The above does not appear to be a preview as I described but something else.  You will not find this explicitly listed because its inherited from the project catalog.  Hence the need to show me a preview.  Or maybe describe the step that I can follow to reproduce a problem, which I can look at tomorrow because now it's late.

**Comment by cdietrich** [comment]
@merks steps are
- start oomph
- select 2012 + ide for committers + java 17
- on 2nd page select all xtexts.
- in the xtext var page select 2022-03 as target platform
- creating the target platform  will fail

**Comment by cdietrich** [comment]
of course(tm) i see this on my main machine / mac only. on windows i dont have the problem.
i wonder if there is something messed up with caches.

**Comment by merks** [comment]
It works for me too and it looks correct of course:

![image](https://user-images.githubusercontent.com/208716/206111829-d1d9fe35-3334-43b7-b402-6c33bf3a51e8.png)

I'm not sure how a messed up thing would end up in the cache, but you could delete `~.eclipse/org.eclipse.oomph.setup/cache`

**Comment by cdietrich** [comment]
will try on a cleaned . dirs

**Comment by cdietrich** [comment]
does not help :( are there more cache places to look at?

**Comment by merks** [comment]
Can you show the screenshot that I show above with that same task selected in your scenario?

**Comment by cdietrich** [comment]
on the 2nd try it shows up now. but on the first it failed

**Comment by cdietrich** [comment]
it works now again. no idea why ...
