### ISSUE TITLE
Oomph: Xtend and Repo list

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1979]
The repo list for Xtend seems unmaintained
=> setup wont work if xtext-xtend only is selected

@merks is there an option that 
- the xtext-eclipse project is automatically selected if xtext-xtend is 
- we can reference repo lists from xtext-eclipse part https://github.com/eclipse/xtext-eclipse/blob/dce8fd1c30ef07bb1081089903a5c6134c493d0a/releng/org.eclipse.xtext.contributor/Xtext.setup#L827 inside the xtext-xtend part of the setup https://github.com/eclipse/xtext-eclipse/blob/dce8fd1c30ef07bb1081089903a5c6134c493d0a/releng/org.eclipse.xtext.contributor/Xtext.setup#L1400

**Comment by merks** [comment]
Attached is a modified version.

[Xtext.setup.txt](https://github.com/eclipse/xtext-eclipse/files/10244364/Xtext.setup.txt)

Here I created a modular target task with only repositories listed in the root container project:

![image](https://user-images.githubusercontent.com/208716/208065163-7f549845-e50f-4c72-9ae8-57e2cf638a93.png)

Then I removed the repository lists from all the other modular target tasks, each of which will inherit the shared/common targlet from the containing project setup.  When a modular target task has no requirements in any of its targlets, it will not perform so this common modular target task kicks in only for those two projects with targlets containing requirements.

**Comment by cdietrich** [comment]
@merks so the inheritance is automatic cause it is defines in the parent.
does this mean the common modular target will also be used for xtext-core?

**Comment by cdietrich** [comment]
of course xtext-core needs parts of the tp too.
e.g. emf.

**Comment by merks** [comment]
Yes, everything in the containers is "inherited" by all the contained projects and streams.

**Comment by cdietrich** [comment]
fixed. thx for your help @merks
