### ISSUE TITLE
Unstable ordering of markers in AnnotatedTextToString

### ISSUE THREAD

**Issue by eliericha** [eclipse/xtext-eclipse#1987]
Markers are currently sorted by region start only. So when multiple markers have the same region start, they are ordered undeterministically among each other. That makes it difficult to use in some test scenarios as we can't compare to a fixed reference.

I'll try to make a submission to fix this.

**Comment by cdietrich** [comment]
hi, what is your proposed fix?

**Comment by eliericha** [comment]
I suggest that after ordering by region start, we order markers with the same region start by their message. That way we should get a deterministic outcome.

**Comment by cdietrich** [comment]
so the end/stop you wont consider?

**Comment by eliericha** [comment]
Ah that's a good point. Indeed we could sort by end, and then by message. From the looks of the code it's easy to chain comparators.

**Comment by cdietrich** [comment]
can you provide a pr

**Comment by eliericha** [comment]
Yes. I also have a minor fix that avoid a NPE elsewhere. Should I submit in the same PR or open a different issue?

**Comment by eliericha** [comment]
I opted to include the minor NPE fix, but let me know if you'd rather proceed otherwise.

**Comment by cdietrich** [comment]
thx for the fix @eliericha
