### ISSUE TITLE
Maven build fails out of the box

### ISSUE THREAD

**Issue by eliericha** [eclipse/xtext-eclipse#1989]
Hello,

Following the build instructions at the root of the repository, I ran `mvn clean verify` and got the following error:

```
bundleLocation not found: /Users/richa/.m2/repository/org/eclipse/orbit/bundles/com.ibm.icu/67.1.0-SNAPSHOT/com.ibm.icu-67.1.0-SNAPSHOT.jar
```

According to [this Tycho issue](https://github.com/eclipse-tycho/tycho/issues/725), this occurs when using Tycho 2.6.0 and 2.7.0+ over the same ~/.m2 Maven repository.

After digging in the Xtext POMs I found that Tycho 2.6.0 is being used because the default profile is `r202203`, and indeed I am using newer versions of Tycho in other projects. So to get a working build/test I had to run `mvn -P latest clean verify` to get Tycho 2.7.5 to be used.

I think I understand that we can't move away from Tycho 2.6.0 yet because of #1931.

Should this be documented in the build instructions for newcomers? Or is the plan to bump the default profile soon and the problem goes away?

Thanks.

**Comment by cdietrich** [comment]
can you run with -Dmaven.repo.local=somedir?

**Comment by eliericha** [comment]
That works, but it's a bulky solution. In any case even if that was the solution, I suggest to document it in case other people run into the same issue.

**Comment by cdietrich** [comment]
PR welcome

**Comment by cdietrich** [comment]
docu was updated
