### ISSUE TITLE
Give up on slicer and migrate domain model example to planner

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1994]
Give up on slicer and migrate domain model example to planner

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/842

Cc @LorenzoBettini

**Comment by cdietrich** [comment]
See also https://github.com/eclipse/xtext-eclipse/pull/1687

**Comment by LorenzoBettini** [comment]
@cdietrich sorry I forgot to answer.
I had already created the PR in that respect.
Should we use that PR?

**Comment by cdietrich** [comment]
i assume it needs heavy rebasing.

**Comment by LorenzoBettini** [comment]
I should have resolved the conflicts

**Comment by LorenzoBettini** [comment]
I have to check whether it builds fine, and let you know

**Comment by LorenzoBettini** [comment]
OK it runs fine both from Eclipse and from Maven

**Comment by cdietrich** [comment]
done
