### ISSUE TITLE
Xtext editor doesn't notice changes of a file outside workspace

### ISSUE THREAD

**Issue by sprigogin** [eclipse/xtext-eclipse#209]
To reproduce:
1. Open a file outside Eclipse workspace using an xtext-based editor.
2. Type something in the editor, but don't save the file
2. Change the file outside Eclipse, for example, by appending a blank line to it
3. Move the focus back to Eclipse

The editor doesn't notice that the file has changed.

Now repeat the same procedure with a file with .txt extension. The editor displays the dialog: "The file 'filename.txt' has been changed on the file system. Do you want to replace the editor contents with these changes?". This is the desired behavior.

This issue is a clone of http://bugs.eclipse.org/490414

**Comment by sprigogin** [comment]
Please review and merge the proposed fix.

**Comment by cdietrich** [comment]
@sprigogin i had to change your code to work with the luna target platform. can you please test if it still fixes your problem

**Comment by cdietrich** [comment]
fixed in 2.12
