### ISSUE TITLE
Make sure Documentation is published to Oxygen (Was Missing in Neon)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#214]
Make sure the Xtext + Xtend docs get to help.eclipse.org (was missing in neon, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=499408)

**Comment by cdietrich** [comment]
@dhuebner do you have any information in this one?

**Comment by dhuebner** [comment]
@cdietrich You can add a documentation after or right before (quiet week). For the neon it should still possible. https://bugs.eclipse.org/bugs/show_bug.cgi?id=500938
You need to add a documentation jar path to the corresponding bugzilla reports.

**Comment by cdietrich** [comment]
so we would have to update our doc jars first for oxygen?

**Comment by dhuebner** [comment]
@cdietrich
You can not add documentation to Oxygen yet.
For Neon you can add documentation if you want to. 
Or what was the question?

**Comment by cdietrich** [comment]
no i jsut want to make sue we get this done for oxygen

**Comment by dhuebner** [comment]
@cdietrich Do we need a label "eclipse-release" or similar, to mark issues we need to solve before Eclipse release.

**Comment by cdietrich** [comment]
i set all tasks needed to the 2.12 milestone

**Comment by cdietrich** [comment]
looks good now
