### ISSUE TITLE
[prefs] Add info severity to the Errors/Warning preference page

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#222]
Compared to eclipse Neon java preferences:
![bildschirmfoto 2017-03-31 um 15 59 42](https://cloud.githubusercontent.com/assets/454322/24553654/2c304a98-162b-11e7-9006-a872356b42e0.png)

**Comment by cdietrich** [comment]
Needs to be fixed in Xtend, Xbase and Xtext(Grammar)

**Comment by cdietrich** [comment]
possibly related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=478936
