### ISSUE TITLE
Xtext nature icon can not be superseded

### ISSUE THREAD

**Issue by simonmoosbrugger** [eclipse/xtext-eclipse#229]
Yet there is no possibility to supersede the Xtext nature icon because it is defined in the "org.eclipse.ui.decorators" extension point. If it would be implemented via the "org.eclipse.ui.ide.projectNatureImages" extension point we would gather the chance to influence the order of the decoraters by the order of the project natures in the ".project" file.

see
[https://bugs.eclipse.org/bugs/show_bug.cgi?id=456114](url)

**Comment by cdietrich** [comment]
fixed in 2.12
