### ISSUE TITLE
[wizard] Change eclipse update site to most recent neon

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#242]
Wizard generates target file which points to:
http://download.eclipse.org/releases/neon/201606221000/

Use Neon 3 instead:
http://download.eclipse.org/releases/neon/201703231000/

**Comment by LorenzoBettini** [comment]
wouldn't it be better to simply point to the composite update site? for Neon this should not impact performance that much (at least, that's what I always do in my target platforms), since there are not so many child repos.

**Comment by kthoms** [comment]
I think it is OK to use the latest child URL for best performance. It became better with Neon, right. Still I think it is a valid issue.
We should rather think about automating the update process in the future. Not only for this.

**Comment by cdietrich** [comment]
yes this should use ogygen with the release  ?!?

**Comment by kthoms** [comment]
Hm, this would be the reason to use the composite. We don't know the concrete timestamp child repo URL yet.
