### ISSUE TITLE
Get rid of EGit workaround in XtextBuilder.MAKE_EGIT_JOB_SYSTEM

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#251]
XtextBuilder.MAKE_EGIT_JOB_SYSTEM 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=459525 has a workaround that should be no longer be needed.
we rarely run into this trace

1 unexpected error(s) found in the log. Messages: [Problems occurred when invoking code from plug-in: "org.eclipse.xtext.builder".]. First error: Problems occurred when invoking code from plug-in: "org.eclipse.xtext.builder".. Stack:java.lang.LinkageError: org.eclipse.core.runtime.jobs.IJobChangeEvent at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.lockClassName(ClasspathManager.java:525) at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLoadedClass(ClasspathManager.java:475) at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:462) at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216) at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395) at org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePackage.java:35) at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.xtext.builder.impl.XtextBuilder$1.scheduled(XtextBuilder.java:100) at org.eclipse.core.internal.jobs.JobListeners$5.notify(JobListeners.java:49) at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:96) at org.eclipse.core.internal.jobs.JobListeners.scheduled(JobListeners.java:162) at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1123) at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:430) at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:462) at org.eclipse.core.internal.events.NotificationManager.requestNotify(NotificationManager.java:206) at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1511) at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54) Caused by: java.lang.InterruptedException at java.lang.Object.wait(Native Method) at java.lang.Object.wait(Object.java:502) at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.lockClassName(ClasspathManager.java:521) ... 21 more 

junit.framework.AssertionFailedError: 1 unexpected error(s) found in the log. Messages: [Problems occurred when invoking code from plug-in: "org.eclipse.xtext.builder".]. First error: Problems occurred when invoking code from plug-in: "org.eclipse.xtext.builder".. Stack:java.lang.LinkageError: org.eclipse.core.runtime.jobs.IJobChangeEvent at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.lockClassName(ClasspathManager.java:525)	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLoadedClass(ClasspathManager.java:475)	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:462)	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)	at org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePackage.java:35)	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)	at org.eclipse.xtext.builder.impl.XtextBuilder$1.scheduled(XtextBuilder.java:100)	at org.eclipse.core.internal.jobs.JobListeners$5.notify(JobListeners.java:49)	at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:96)	at org.eclipse.core.internal.jobs.JobListeners.scheduled(JobListeners.java:162)	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1123)	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:430)	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:462)	at org.eclipse.core.internal.events.NotificationManager.requestNotify(NotificationManager.java:206)	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1511)	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45)	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)Caused by: java.lang.InterruptedException	at ........
org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)	at org.eclipse.equinox.launcher.Main.run(Main.java:1438) at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by cdietrich** [comment]
@iloveeclipse the behaviour in egit was changed with mars, correct?

**Comment by iloveeclipse** [comment]
EGit doesn't ships with the platform, you can install different versions to different platforms. The particular issue was shipped with EGit 4.1, released 28.09.2015

See
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=474003
- https://wiki.eclipse.org/EGit/New_and_Noteworthy

**Comment by rosczja** [comment]
I am afraid that this is still an issue. Not with EGit, but with webtools/dali. I have the JEE Version of Eclipse from 2018-12 running and Xtext 2.16.

Sometimes Xtext build loops indefinitly due to some Jobs triggered by the "JPA Change Event Handler".

**Comment by cdietrich** [comment]
@rosczja do you have more details?

**Comment by rosczja** [comment]
@cdietrich What details do you need?

Debugging the XtextBuilder I found the class JobCommandJob to be in the way, because it has a lower priority and thus interrupted the Xtext build. The class J2EEComponentClasspathUpdater has two more internal classes that derive from Job. Maybe they could also cause problems.

**Comment by kthoms** [comment]
Since we are on Oxygen at minimum, we should be able to remove the EGit workaround now. This would resolve also internal Job API access.

**Comment by cdietrich** [comment]
@szarnekow what do you think?

**Comment by cdietrich** [comment]
@kthoms please add a sentence to the release notes. then can be closed

**Comment by kthoms** [comment]
Done.
