### ISSUE TITLE
[ContentAssist] Content assist proposes classes instead of interfaces when extending an interface

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#258]
`Foo.java`
```
package myPackage;

public interface Foo extends It<|> {
}
```
Offers `Iterable`, `Iterator`, etc...

`Bar.xtend`
```
package myPackage

interface Bar extends It<|> {
}
```
Offers classes but no interfaces at all.

`<|>` represents the cursor position in the editor. 
Version: 2.11.0.v20170201-0242

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=403025 as well
