### ISSUE TITLE
Analyze configuration errors and provide better feedback

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#260]
Some of the most frequently occuring problems are caused by misconfigurations. The resulting error messages are not helpful to the users or developers. Some of these problems arise while getting a UI plugins injector.

There could be several reasons:
- UI Activtor was not started. This results in NPEs when calling the EEF's getBundle and getInjector methods, since the bundle instance was not assigned in the Activator. Reason could be a missing dependency or when developers do no specify to start the bundle on class load. See [Bug#462906](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462906)
- DSL was developed with a more recently Xtext version and deployed on an older version. This could result in a NCDFE for new API classes. See [Bug#479381](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479381)
- A dependency is optional by default, but actually required by the DSL (e.g. Xbase, JDT). See [Bug#475049](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475059)
- A newer Xtext runtime is used together with an older UI. See [Bug#475431](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475431)

Xtext cannot solve these issues, but detect and analyse them to give better hints about the configuration problem.

**Comment by kthoms** [comment]
- eclipse/xtext-eclipse#295
- eclipse/xtext-eclipse#297

**Comment by cdietrich** [comment]
@kthoms is there anything left on this issue?

**Comment by kthoms** [comment]
I have to provide new generated code for the existing languages.

**Comment by cdietrich** [comment]
@kthoms are you still working on this issue?

**Comment by kthoms** [comment]
For 2.13 improvements are applied. If we later find that we can do more, we'll open a separate ticket.
