### ISSUE TITLE
Provide a TextFileDocumentProvider based XtextDocument

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#264]
We should Provide  a TextFileDocumentProvider based XtextDocument.

e.g.as long as a build is running i cannot open a Xtext Based editor.
Opening the editor is blocked by `org.eclipse.ui.editors.text.FileDocumentProvider.refreshFile(IFile, IProgressMonitor)`.

**Comment by iloveeclipse** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=329657

**Comment by qtran-n4** [comment]
I have experienced this behavior as well:
https://www.eclipse.org/forums/index.php/m/1773488/#msg_1773488

**Comment by iloveeclipse** [comment]
I've created this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546920

**Comment by miklossy** [comment]
> e.g.as long as a build is running i cannot open a Xtext Based editor.

See also https://www.eclipse.org/forums/index.php/t/1104936/

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
