### ISSUE TITLE
[language-server] No results for hover and documentSymbol

### ISSUE THREAD

**Issue by vladdu** [eclipse/xtext-eclipse#271]
I'm not sure if it's something I do wrong or a bug, as I just managed to port my Xtext languages to the LSP variant. 

When hovering or when using Ctrl-Shift-O in vscode for listing all symbols, the server doesn't respond, so nothing happens (actually, hover displays "loading...")

Is there something more that I have to implement to make it work? I developed the language support with 2.9, so maybe there are new APIs? The documentation seems a bit outdated in that regard (for example, the generator is now implementing IGenerator2, not IGenerator) and doesn't seem to say anything about any new stuff. 

How do I know what I need to implement myself, until the Eclipse specific functionality gets a generic counterpart?

**Comment by cdietrich** [comment]
no that should work find. at least in my hello world it does. btw the correct place for lsp is xtext-core

**Comment by cdietrich** [comment]
maybe there is some exception flowing around that kills the server. or sends it to a wait loop. ....

**Comment by cdietrich** [comment]
<img width="1025" alt="bildschirmfoto 2017-05-24 um 12 31 46" src="https://cloud.githubusercontent.com/assets/238736/26399384/04ecc53e-407d-11e7-836a-1f7b52d3db63.png">

**Comment by vladdu** [comment]
Oh, sorry, should I move the issue there?

The server keeps going after getting the cancel message for those requests, so it doesn't crashes completely. There is no error message displayed or printed.

**Comment by cdietrich** [comment]
does not matter for now

**Comment by cdietrich** [comment]
hmm my lang server does not start after i did a clean. have to look

**Comment by vladdu** [comment]
Hmm, after a while no functionality returned anything, so I had to restart and it looks okay now, including hover and symbols. I will close this and open a new one if I find out what could have happened. Can I run the server with debugging?

**Comment by cdietrich** [comment]
depends on how you start the server (launch script, main from eclipse, ...) and how you extension communicates (socket, process io, ....)

**Comment by vladdu** [comment]
I'm using vscode and start using the script, and I think the default is to talk via process io.

**Comment by cdietrich** [comment]
then you need to fix the script to start with debugging and make sure you debug silent `quiet=y` (otherwise it will spam sysout which is bad)

**Comment by vladdu** [comment]
ok, thanks, will try it.
