### ISSUE TITLE
OutlineView flickers on every Keystroke

### ISSUE THREAD

**Issue by HBuender** [eclipse/xtext-eclipse#278]
The OutlineView flickers whenever it is updated by the OutlineRefreshJob. The behavior can be reproduced even with a small instance of the DomainModel sample. The flickering can be cirumvented by setting 
`getTreeViewer().getTree().setRedraw(false);` before the refresh in `protected void refreshViewer(final IOutlineNode rootNode, final Collection<IOutlineNode> nodesToBeExpanded,	final Collection<IOutlineNode> selectedNodes)`is executed. Afterwards redraw should be set back to true.

**Comment by szarnekow** [comment]
Could you please create a pull request?

**Comment by HBuender** [comment]
Yes, just have to update my environment ;)

**Comment by cdietrich** [comment]
fixed in 2.13
