### ISSUE TITLE
Bogus behaviour of mixing xtext and non xtext projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#281]
assume you have a java project a (no xtext nature)
and a java project b with xtext nature
b has dependency to a

if you change something in a, b will not rebuild the xtend stuff and so
i see only the errors copied from java to xtend

and if there are unstructural changes from non xtext projects in the queue,
xtext will allways tell the builder infrastructure "needsRebuild"
which then will call all builders up to 10 times

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/issues/2429 as well

**Comment by cdietrich** [comment]
reason is that the "toBeBuilt" is empty. `org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(IResourceDelta, IProgressMonitor)`

**Comment by cdietrich** [comment]
caused by `org.eclipse.xtext.builder.impl.javasupport.JdtQueuedBuildData.doNeedRebuild(JavaBuilderState, (UnconfirmedStructuralChangesDelta)=>void)` having a project guard.

**Comment by szarnekow** [comment]
Fixed
