### ISSUE TITLE
[refactoring] Rename refactoring only works with path URI fragments

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-eclipse#284]
If you refer to Xtext form other XMI-based models, it may be a good idea to encode FQ names in the URI fragments, in order to get some independence of the ordering of elements. As soon as you do that, rename refactoring will stop working.

The reason is that we use these fragments as well in the _IReferenceDescriptions_ for the references to be updated during rename. There we try to recover the referring element using this fragment *after* applying the name change. So if the name of the renamed element is included in the fragment, this will fail.

Rename refactoring kind of freezes the models, so it should be safe to use EMF's default path fragments at least for the _IReferenceDescriptions_ needed during refactoring.

Unfortunately, _IReferenceDescriptions_ are instantiated as _DefaultReferenceDescriptions_ directly using the constructor in a number of places. My initial assumption, that all of these would delegate to the _IResourceDescriptionManager#createReferenceDescription_ turned out to be wrong. 

Into the bargain, we cannot easily create the path fragments, as the _XtextResource#fragmentProviderFallback_ is private.

**Comment by JanKoehnlein** [comment]
As this won't either work with ID attributes in the EMF model, we should extract the fragment path algorithm and use it where applicable.

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463443 as well

**Comment by JanKoehnlein** [comment]
Fix merged
