### ISSUE TITLE
EmbeddedEditorFactory.Builder API extension to set the embedded editor SWT style.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#292]
Currently, the EmbeddedEditorFactory creates an embedded editor using the `SWT.BORDER | SWT.V_SCROLL | SWT.H_SCROLL` SWT style. This style is hardly customizable for use cases when creating a single-line embedded editor is desired (e.g.  https://www.eclipse.org/forums/index.php/t/1076254/  https://www.eclipse.org/forums/index.php/m/1746440/ ).

Therefore, the EmbeddedEditorFactory.Builder API should be extended to be able to configure the SWT style of the embedded editor.

I will create a PR to this issue soon.

**Comment by cdietrich** [comment]
fixed in 2.13
