### ISSUE TITLE
[wizard] Create executable language server uber jar

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#299]
To build DSL language servers usually an executable Jar with the DSL's runtime & .ide project and all transitive dependencies is created. For both build systems Maven & Gradle are appropriate plugins available (Maven Shade Plugin, Gradle ShadowJar Plugin).

The wizard should allow the option to build a Language Server. This implies:
- Generic IDE support is enabled
- Eclipse Plugin is disabled
- A build system is selected

Eclipse piugin must be disabled since the Maven Shade Plugin does not work in a Tycho environment.

The wizard has to create the appropriate additions to the .ide project.

**Comment by cdietrich** [comment]
@kthoms is there anything left for this task?

**Comment by kthoms** [comment]
No this is finished
