### ISSUE TITLE
deadlock between LanguageSpecificURIeditorOpener and OutlinePage

### ISSUE THREAD

**Issue by yoosiba** [eclipse/xtext-eclipse#3]
The deadlock happens between LanguageSpecificURIeditorOpener and OutlinePage. 
So far I could reproduce it on Linux in 100% cases. Does not happen on Windows, nor OSX. 

I have used:
 - Linux (Lubuntu 15.04 and Xubuntu 16.04)
 - Java 8u92
 - N4JS master (so Xtext 2.10, eclipse Mars 4.5.2), see https://github.com/NumberFour/n4js

To reproduce:
1. Launch N4JS ide in a way that Outline is open and no editor is open. (or close all editors, open outline view and re-launch ide).
 2. Trigger OpenType view.
 3. Open any type from search history (or type some name, e.g. StorageInMemory from N4JS example project, and select found type)
 4. No editor is opened, outline is not populated. Click recklessly to irritate your OS
![busy](https://cloud.githubusercontent.com/assets/944287/16260592/6691bac4-3868-11e6-8cf5-6c0b4a7eb7bb.png)

Stacktraces show that main thread that opens Editor and other thread that populates Outline are locking each other on drawing to the screen and reading the resource:
![blockedthreads](https://cloud.githubusercontent.com/assets/944287/16260628/8f91acb8-3868-11e6-9d96-d68ff38ebc13.png)

Full traces copied from JConsole:

[main.txt](https://github.com/eclipse/xtext-eclipse/files/327346/main.txt)

[worker0.txt](https://github.com/eclipse/xtext-eclipse/files/327348/worker0.txt)

**Comment by yoosiba** [comment]
Talked with @meysholdt who said 
_According to your stack trace, this is caused by
org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider.createRoot(IXtextDocument)
calling org.eclipse.jface.viewers.ILabelProvider.getImage(Object)
Instead, org.eclipse.xtext.ui.label.ILabelProviderImageDescriptorExtension.getImageDescriptor(Object) should be called._

I wanted to point out that deadlock happens when Outline needs image that have not been yet loaded. So it will calculate ImageDescriptor from the document. This will lead to PluginImageHelper creating image from descriptor, which leads to URLImageDescriptor calling ```return new Image(device, path);```.
This ends up in native lock via ```org.eclipse.swt.internal.gtk.OS#.g_utf16_to_utf8```

**Comment by stadlerb** [comment]
Which N4JS Git commit were you using? I'm not able to get a version where both N4JS and the example project compile correctly.

**Comment by yoosiba** [comment]
It was some revision of master, at the moment I don't remember which one.

But, did you use our [Oomph setup](https://github.com/NumberFour/n4js#eclipse-installer) ? With it, you should get things in correct versions - no compile errors should be present. If that is not true, we need to solve it in the first place.

Or have you used manual installation?

**Comment by torstenkraemer** [comment]
Basically by changing the base class of ```N4JSOutlineTreeProvider``` from ```DefaultOutlineTreeProvider``` to ```org.eclipse.xtext.ui.editor.outline.impl.BackgroundOutlineTreeProvider``` solved the problem. 

This issue can be closed.

**Comment by spoenemann** [comment]
Ok. Please reopen when necessary.
