### ISSUE TITLE
Missleading warning when refactoring

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#317]
given the grammar

```
Model:
	imports+=Import*
	packages+=XPackage
;

XPackage:
	"package" name=ID "{"
	elements+=Element*
	"}"
;

Element:
	AElement | BElement | Reference
;

AElement:
	"a" name=ID
;

BElement:
	"b" name=ID
;

Reference: "ref" a=[AElement];
	
Import:
	"import" importedNamespace=FQNWC
;

FQNWC:
	ID ("." ID)* (".*")?
;
```

and test model

```
package p {
	a a1
	ref a1
}
```
i get follwing warning when refactoring a1

"Misconfigured language: New reference text has invalid syntax."

![warning](https://user-images.githubusercontent.com/238736/28825442-8a81a33e-76c6-11e7-9360-aaff38ca4259.png)

this is coming from "org.eclipse.xtext.ui.refactoring.impl.RefactoringCrossReferenceSerializer.getCrossRefText(EObject, CrossReference, EObject, RefTextEvaluator, ITextRegion, StatusWrapper)"

when converting the qualified name

**Comment by cdietrich** [comment]
does anybody have a hint how to fix that? if there are multiple names inside the scope and only the simple name fits (which is the case at all import based languages) what is the expected "language configuration" to avoid this error message cc @JanKoehnlein @meysholdt

**Comment by JanKoehnlein** [comment]
We should only issue that warning if no element in the loop of `IEObjectDescriptions` matches.

**Comment by cdietrich** [comment]
fixed in 2.13

**Comment by cdietrich** [comment]
fix breaks xtend tests

**Comment by cdietrich** [comment]
adaped the fix
