### ISSUE TITLE
DirtyStateEditorSupport.announceDirtyState() does not Start Managing an Unmanaged Dirty Resource

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/xtext-eclipse#326]
I came across a case in which DirtyStateEditorSupport.announceDirtyState() does not start managing an unmanaged dirty resource.

When an editor is saved, DirtyStateEditorSupport.markEditorClean() discards the dirty state and sets the state to State.SHOULD_UPDATE. However, when the state is SHOULD_UPDATE and the dirty state manager no longer is managing the resource, a call to announceDirtyState() call does not start managing the dirty state. dirtyStateManager.announceDirtyStateChanged() is called which only replaces the managed resource rather than adding it. manageDirtyState() is only called when the state is CLEAN.

This can occur in practice if a user saves and editor and then executes a GUI command which calls IXtextDocument.modify(). The modify() will trigger a reconciliation and the dirty state will not be updated. The editor is refreshed with the updated contents but any operations which rely on live resources could use the incorrect resource.

Adding the following test case in DirtyStateEditorSupportTest reproduces the issue.
```
	@Test public void testMarkEditorClean_04() {
		assertFalse(dirtyStateManager.hasContent(resourceURI));
		dirtyStateSupport.initializeDirtyStateSupport(this);
		dirtyStateSupport.isEditingPossible(this);
		assertTrue(dirtyStateManager.hasContent(resourceURI));
		dirtyStateSupport.markEditorClean(this);
		assertFalse(dirtyStateManager.hasContent(resourceURI));
		assertNotNull(verifyListener);
		dirtyStateSupport.announceDirtyState(resource);
		assertTrue(dirtyStateManager.hasContent(resourceURI));
	}
```

**Comment by cdietrich** [comment]
@szarnekow do you remember why that guard in `org.eclipse.xtext.ui.editor.DirtyStateManager.announceDirtyStateChanged(IDirtyResource)` was introduced? do we miss a case here?

**Comment by JanKoehnlein** [comment]
I don't remember why, but looking at the implementation it seems to be correct to call `manageDirtyState` again as described in the initial description.

**Comment by cdietrich** [comment]
[export-xxx.zip](https://github.com/eclipse/xtext-eclipse/files/1399193/export-xxx.zip)
reproducing example

**Comment by philip-alldredge** [comment]
Is there any hope for this issue to be resolved?

**Comment by szarnekow** [comment]
There is always hope.
But I don't think this is something we actually want to change. It is important, that clients get the chance for taking some sort of ownership for the dirty state they are managing. Otherwise arbitrary clients could override a previously contributed dirty state by accident which could lead to all sorts of interesting effects.
Well behaved clients keep track of the dirty state they started to manage successfully.
Your GUI action is likely triggered on some editor. You should probably use org.eclipse.xtext.ui.editor.XtextEditor.validateEditorInputState() to ensure that your user interaction is allowed.

**Comment by philip-alldredge** [comment]
Thanks for the quick explanation and pointing me to the `org.eclipse.xtext.ui.editor.XtextEditor.validateEditorInputState()` method. It sounds like it is intended behavior so I'll close.
