### ISSUE TITLE
Build loop by TaskMarkerContributor

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#348]
Today I observed a build loop in a customer project. After saving a DSL file the XtextBuilder was called recurrent with a resource delta for the changed resource.

After debugging a while it turned out that the resource change was occurring while recreation of task markers during a refresh.

To solve this issue TaskMarkerContributor should only delete and create markers when there is actual a change to the existing markers.

**Comment by cdietrich** [comment]
why is this a resource change?

**Comment by cdietrich** [comment]
is it possible you listen to `org.eclipse.core.resources.IResourceDelta.MARKERS` changes accidentally

**Comment by kthoms** [comment]
I could not imagine where. At least we don't do this in our code.

**Comment by kthoms** [comment]
I also don't know how to reproduce it, it happened sproadically. I asked the customer to enable remote debugging and call me when it was happening. This is what came out. But I cannot tell why it is happening, only where it is caused and how it is resolved.

**Comment by cdietrich** [comment]
still have no idea how to reproduce this. ok with closing  @kthoms ?
