### ISSUE TITLE
p2-repository should include source bundle/feature

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-eclipse#35]
to get the build working at a time when the upstream repos did not ship source artifacts, including source had explicitly been disabled in 

    /xtext-eclipse/releng/org.eclipse.xtext.tycho.parent/pom.xml

**Comment by meysholdt** [comment]
Requirement: After a user has installed Xtext into his/her target platform from [p2-repository](http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/lastSuccessfulBuild/artifact/build/p2-repository/), Eclipse should find the source for for all plugins that came from that p2-repository.

This should be straight forward for the plugins from xtext-eclipse, but it needs to be considered that this p2-repository also includes plugins from xtext-core, lib and extras. Those plugins need to have their source bundle created by their gradle build in lib, code, or extra. Then, the tycho build form xtext-eclipse needs to pick up those source bundles.

**Comment by meysholdt** [comment]
fixed. Source-Bundles are created and included into our standard Eclipse Features.
Source Features are not being created.

**Comment by spoenemann** [comment]
Let's keep it like this for now and reopen if we find problems related to the modified structure of the features.
