### ISSUE TITLE
b3 is dead but Xtext.setup uses it

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#370]
do we still need b3 or can we /dev/null our tooling dependency in Xtext.setup

**Comment by kthoms** [comment]
FMPOV, we can drop the dependency.

**Comment by cdietrich** [comment]
new uri is http://download.eclipse.org/cbi/updates/aggregator/ide/4.4/?d but id still like to get rid of b3 since i never use it and i dont know how uses it and what for

**Comment by cdietrich** [comment]
Fixed in 2.13
