### ISSUE TITLE
Contribute org.eclipse.core.contenttype.contentTypes extension

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#379]
A text search can result in blocking behavior when trying to determine if a file has binary content. In `org.eclipse.search.internal.core.text.TextSearchVisitor.hasBinaryContent(CharSequence, IFile)` it is first tried to get a content description for a file. If there is none, the file's beginning is read to detect \0.

The following screenshot shows that `TextSearchVisitor.hasBinaryContent` is quite heavy weight and blocked in the synchronized method `java.nio.charset.CoderResult.Cache.get(int)`.

For Xtext DSLs this can be improved by contributing a content description.

![screenshot 47](https://user-images.githubusercontent.com/265597/30829718-e545f8c8-a241-11e7-891f-7652b519015b.png)

**Comment by cdietrich** [comment]
am missing a commit for existing dsl like xtext xbase purexbase xtend etc

**Comment by kthoms** [comment]
ok, will contribute

**Comment by kthoms** [comment]
Done.
