### ISSUE TITLE
AbstractResourceRelocationTest is not a Test

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#390]
AbstractResourceRelocationTest is not a test and thus fails

**Comment by cdietrich** [comment]
@JanKoehnlein @meysholdt please have a look

**Comment by cdietrich** [comment]
fixed with e7e0bb1936ae3fff44b88285b0cc331c95424e9d

**Comment by JanKoehnlein** [comment]
Thx
