### ISSUE TITLE
Photon: JavaProject.computePackageFragmentRoots api change

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#393]
JavaProject.computePackageFragmentRoots signature changs with photon.
https://github.com/eclipse/eclipse.jdt.core/commit/0201874afdd1b68acce876105bbdf3cc69d05ccc

another issue is at removed org.eclipse.xtext.xbase.compiler.OnTheFlyJavaCompiler.PatchedFileSystem.findType(char[][], boolean)
 plus tons of new methods in filesystem

**Comment by cdietrich** [comment]
breaks org.eclipse.xtext.common.types.access.jdt.JdtTypeProvider.collectSourcePackageFragmentRoots(JavaProject, HashSet<String>, IClasspathEntry, ObjectVector)

**Comment by cdietrich** [comment]
@szarnekow what is the intention of that code

**Comment by cdietrich** [comment]
another issue is at org.eclipse.xtext.xbase.compiler.OnTheFlyJavaCompiler.PatchedFileSystem.findType(char[][], boolean)

**Comment by cdietrich** [comment]
Options for TypeProviderIssue

(a) reflection

```
case IClasspathEntry.CPE_SOURCE:
					try {
						Method declaredMethod = JavaProject.class.getDeclaredMethod("computePackageFragmentRoots", IClasspathEntry.class, ObjectVector.class, HashSet.class,IClasspathEntry.class, boolean.class, Map.class);
						declaredMethod.invoke(javaProject, entry,
							result,
							rootIDs,
							referringEntry,
							true,
							null);
					} catch (NoSuchMethodException e) {
						try {
						Method declaredMethod = JavaProject.class.getDeclaredMethod("computePackageFragmentRoots", IClasspathEntry.class, ObjectVector.class, HashSet.class,IClasspathEntry.class, boolean.class, boolean.class, Map.class);
						declaredMethod.invoke(javaProject, entry,
							result,
							rootIDs,
							referringEntry,
							true,
							true,
							null);
						} catch (NoSuchMethodException e2) {
							LOG.error("did not find any 'computePackageFragmentRoots' method", e2);
						} catch (IllegalAccessException e2) {
							LOG.error("could not invoke 'computePackageFragmentRoots' method", e2);
						} catch (IllegalArgumentException e2) {
							LOG.error("could not invoke 'computePackageFragmentRoots' method", e2);
						} catch (InvocationTargetException e2) {
							LOG.error("could not invoke 'computePackageFragmentRoots' method", e2);
						}
					} catch (IllegalAccessException e) {
						LOG.error("could not invoke 'computePackageFragmentRoots' method", e);
					} catch (IllegalArgumentException e) {
						LOG.error("could not invoke 'computePackageFragmentRoots' method", e);
					} catch (InvocationTargetException e) {
						LOG.error("could not invoke 'computePackageFragmentRoots' method", e);
					}
					break;
``` 

(b) inline the code

**Comment by cdietrich** [comment]
seems this is done on maintenance as well
https://github.com/eclipse/eclipse.jdt.core/commit/0201874afdd1b68acce876105bbdf3cc69d05ccc#diff-c1da82ed737689b0aeddf1126c08e061
so i think we should fix this in 2.13

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=525462

**Comment by svenefftinge** [comment]
thanks, it would best if jdt adds a compatible signature

**Comment by cdietrich** [comment]
added two proposals for a fix of the type provider proble(1 reflective, 1 inline)
the onthegfly problem is still open. wonder if we need the subclass anyway (class is dprecated)

**Comment by cdietrich** [comment]
discussion on jdt dev https://dev.eclipse.org/mhonarc/lists/jdt-dev/msg00909.html

**Comment by svenefftinge** [comment]
The change in https://github.com/eclipse/xtext-eclipse/commit/14a3ea033685e95a7bbf1fa2f771e0b028687727 looks good to me. I don't remember any concrete performance issues we had. Have you compared your version on a reasonably sized workspace?

Could you share what the concrete issue with the jdt change is, since it seems to be binary compatible and the documentation of the changed parameter looks compatible, too.

**Comment by cdietrich** [comment]
did not have time to test this e.g. with a bigger ws yet. jenkins build times are to instable to take into account i think. what do you think of a solution for the second problem. would it be ok for you to throw out patchedfilesystem?

**Comment by cdietrich** [comment]
Fixed in Xtext 2.13

**Comment by cdietrich** [comment]
TBD: cherrypick and create 2.12.1 release?

**Comment by svenefftinge** [comment]
Yesterday, you told me it was not so easy because there are issues with Tycho and Gradle. Also, The RC phase just has passed. AFAIU, our last chance for a contribution was Tuesday.

**Comment by cdietrich** [comment]
Well I am not sure cause I have no idea how the magic build a release branch works that micro did so I cannot create a 2.12.1 branch to test. The current seems to draw any dependencies so the build fails at extras. So I could not test eclipse maven and xtend .

**Comment by svenefftinge** [comment]
Given the effort to get a working build for 2.12.1. We decided to live with 10 days of incompatibility with the latest JDT. We should have a good RC out by the time Oxygen 1a is released.
