### ISSUE TITLE
Fix Oomph Setup

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-eclipse#4]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=496683

**Comment by LorenzoBettini** [comment]
for the moment which is the best way to have a working workspace?

**Comment by spoenemann** [comment]
Use the "Gradle Project" import wizard for xtext-lib, xtext-core, xtext-extras, xtext-idea, and xtext-web. The Maven projects probably need to be imported manually.

**Comment by LorenzoBettini** [comment]
And concerning the Eclipse distribution and plug-ins?

**Comment by spoenemann** [comment]
Not sure, but as said before I think currently they have to be imported manually into the workspace, which includes setting the target platform manually.

**Comment by LorenzoBettini** [comment]
I actually meant the plugins you have to install into Eclipse :)

**Comment by spoenemann** [comment]
I am using a standard Eclipse package where I installed Xtext 2.10.

**Comment by spoenemann** [comment]
> Should STS Gradle be replaced by Buildship?

Yes

> Should this be handled in a separate issue?

I'm not sure what there is to be done for that. Currently I'm evaluating checking in the project meta data for projects imported with Buildship.

> Is upgrade to Java-8 OK? (https://bugs.eclipse.org/bugs/show_bug.cgi?id=457927)

Yes, we already switched to Java 8 for all projects.

> Should the setup be splitted into several subprojects, and Git Clone Tasks relative to the Subproject?

Do you mean several Oomph projects? That could be useful for people who want to work on a subset of Xtext.

> Should the Target Platform be set by the Core project?

No, the target platform is needed only by the Eclipse plugins, so it's defined in xtext-eclipse.

> Is it assumed that the Core project is always selected?

Not necessarily. The Gradle and Maven IDE integrations should use snapshot versions for projects that are not in the workspace.

**Comment by kthoms** [comment]
> I'm not sure what there is to be done for that. Currently I'm evaluating checking in the project meta data for projects imported with Buildship.
I'm doing the same right now. The Project Import fails when the buildship settings file is missing, and Oomph Setup refuses to continue then. Not a nice behavior.

I have some progress on the Xtext.setup already. It would be best if you check in the Buildship metadata and delete the .settings/gradle directories.

**Comment by kthoms** [comment]
PR created
https://github.com/eclipse/xtext-eclipse/pull/15

**Comment by kthoms** [comment]
Change for Oomph requested: https://bugs.eclipse.org/bugs/show_bug.cgi?id=497606

**Comment by LorenzoBettini** [comment]
@svenefftinge @kthoms The setup works, but there were a few things left to be done, please have a look at https://github.com/eclipse/xtext-eclipse/pull/18

**Comment by LorenzoBettini** [comment]
@kthoms @spoenemann I think we should update the README file of one of the subprojects (which one?) with the instructions along the lines of the old instructions https://github.com/eclipse/xtext/blob/754a35adc8fb870d15e5f0f0d8e86efde95b6af2/README.md what do you think?

**Comment by spoenemann** [comment]
Let's put the description to xtext-eclipse and refer to it from the other repos.

**Comment by kthoms** [comment]
Shall we treat updating the contribution guide in a separate issue or in this one?

**Comment by kthoms** [comment]
The CONTRIBUTING.md file was adjusted and the setup is fixed regarding the repository restructuring. I think further changes should be tracked in separate issues and this one should be closed.

**Comment by kthoms** [comment]
Can this be closed now? I cannot change the state.
