### ISSUE TITLE
[oomph] Enable option "Insert Signed-off-by" Footer

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#41]
When committing to Xtext it is mandatory to insert the Signed-off-by Footer. Sometimes I forget that, fail at a PR, reset the commit and re-commit it. EGit UI allows to automatically insert the option for a commit, so this cannot be forgotten. The Xtext.setup should set this preference.

**Comment by meysholdt** [comment]
@kthoms this issue has been resolved, hasn't it?

**Comment by kthoms** [comment]
Yes, fixed
