### ISSUE TITLE
Java9: Investigate slow performance

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#424]
https://www.eclipse.org/forums/index.php/t/1089419/

**Comment by cdietrich** [comment]
can reproduce the horrible performance.

**Comment by cdietrich** [comment]
<img width="1153" alt="bildschirmfoto 2017-10-18 um 09 14 13" src="https://user-images.githubusercontent.com/238736/31705215-c2bba190-b3e4-11e7-8d48-90ad1c97d999.png">
<img width="1151" alt="bildschirmfoto 2017-10-18 um 09 13 39" src="https://user-images.githubusercontent.com/238736/31705216-c2e5caba-b3e4-11e7-9c37-bfb60e870f0f.png">

**Comment by cdietrich** [comment]
@stephan-herrmann do you know anything about this inside jdt? do we have to use a different api?

**Comment by cdietrich** [comment]
yourkit snapshot: https://drive.google.com/file/d/0B7rqwXB52fUOSnJfWHN4Unh6dHM/view?usp=sharing

**Comment by svenefftinge** [comment]
Outch! Good, you are looking into it. AFAIU it is not related to the recent change, you did, but related to a change in JDT?

**Comment by cdietrich** [comment]
no its not inside the typeprovider searching for source folders, it afterwards when we resolve bindings. => with my change rolled back the performance is that very same bad one

**Comment by cdietrich** [comment]
and its "really bad" only for java 9 projects. java 8 project are sightly better

**Comment by cdietrich** [comment]
imho org.eclipse.jdt.internal.core.NameLookup.getModuleDescription(IPackageFragmentRoot, Map<IPackageFragmentRoot, IModuleDescription>, Function<IPackageFragmentRoot, IClasspathEntry>) should cache null results.

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=526209

**Comment by cdietrich** [comment]
<img width="1435" alt="bildschirmfoto 2017-10-18 um 12 28 30" src="https://user-images.githubusercontent.com/238736/31713839-e2cbc4cc-b3ff-11e7-9131-4c1f54a6b80d.png">

with a patched jdt it looks better, but still way not perfect

**Comment by cdietrich** [comment]
here is the link to the snapshot after the change https://drive.google.com/file/d/0B7rqwXB52fUOM1prTkRpWFJQV00/view
have no idea on what to make better.

performance is still 3-4 times worse that compared to neon + xtext 2.12

**Comment by nloke** [comment]
I upgraded oxygen + xtext 2.12 to 2020-06 + xtext2.22 and I noticed this 3 times performance issue also with java8.

Is this issue still valid since it has been more than 3 years?

**Comment by cdietrich** [comment]
This cannot be judged.
You should always measure your individual problem
