### ISSUE TITLE
Builder: Improve Progress Reporting

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#433]
we should consider improoving the progress reporting in eclipse during build.
maybe we can facilitate new features in more recent versions once we moved tp to oxygen 

e.g. Progress Monitor shows "refeshing" although refreshing has finished before
The Progress Monitor changes its label to "Refreshing" at the places where we call `IResource.refreshLocal` and keeps that label even after finishing the refresh.
this gives the user the wrong impression all the time is spent on "refreshing"

**Comment by cdietrich** [comment]
to be checked: is this an issue with platform and is the behaviout still there with oxygen

**Comment by cdietrich** [comment]
![progressmonitor](https://user-images.githubusercontent.com/238736/31887229-d4bdfef8-b7f7-11e7-8cb3-aa5e0f82873d.png)

**Comment by cdietrich** [comment]
cc @iloveeclipse

**Comment by iloveeclipse** [comment]
Christian, I would guess that someone in the call chain of refresh code uses monitor in a wrong way. If this would be a platform bug, we would have more clients complaining.

**Comment by cdietrich** [comment]
that is the "correct" way of calling?

**Comment by iloveeclipse** [comment]
Let say after refresh no one opens new task and the old one is not finished

**Comment by cdietrich** [comment]
so its not intended to call refresh within a block of other stuff

**Comment by iloveeclipse** [comment]
See examples how to use API at https://github.com/iloveeclipse/ece2016-progressmonitors.git

**Comment by iloveeclipse** [comment]
> so its not intended to call refresh within a block of other stuff

One must inspect the code to answer this

**Comment by holgerschill** [comment]
Fixed in 2.15
