### ISSUE TITLE
[example] DomainModel-Example is based on an old xtext version

### ISSUE THREAD

**Issue by djetzen** [eclipse/xtext-eclipse#44]
The DomainModel-Example is still based on an old Xtext version. This means, that for example the validator is written in Java and not Xtend, there is still the previous project layout and so on.

**Comment by meysholdt** [comment]
contributions are very welcome :)

The work to be done is to to migrate [GenerateDomainmodel.mwe2](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/GenerateDomainmodel.mwe2) to the new generator infrastructure.
