### ISSUE TITLE
[Xbase] Changes to private api of Java Classes leads to rebuild of xbase files

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#442]
Changes to private api of Java Classes leads to rebuild of xbase files

**Comment by szarnekow** [comment]
This is necessary since we'd produce different error markers for 'method not visible' vs 'method does not exist'

**Comment by cdietrich** [comment]
hmmmm ok, but this makes it hard to edit java code that is used in 500 xbase files

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
