### ISSUE TITLE
Cancel reconciler when uninstalling?

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-eclipse#446]
In a product still based on Xtext 2.8.3 I noticed that closing the editor for big input documents would sometimes freeze the UI for a few seconds. The reason was that the reconciler was still running when the UI thread was in `XtextDocument#disposeInput()`. As a solution I added a call to `cancel()` to `XtextReconciler#uninstall()` (at line 257 in the snippet included below).

I have not yet verified if this would be a problem with the current Xtext release, so I report this issue so that it can be verified.

https://github.com/eclipse/xtext-eclipse/blob/b166c5f6306b0fe26a2b94f71f8aecda073d403c/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextReconciler.java#L244-L258

**Comment by cdietrich** [comment]
@knutwannheden how can you close the editor? if i touch something in the editor i cannot close it while reconciler for touch is running

**Comment by cdietrich** [comment]
ok i can test it with 2 editors and dirty state reconciliation

**Comment by cdietrich** [comment]
Fixed in 2.14

**Comment by knutwannheden** [comment]
Christian: Thanks for looking into this and for fixing it!

In the customer's product all I did was to just open the editor and then close it again. That already triggered the reconciler. In another test I also just made some dummy edits and then closed the editor without saving. In both cases the reconciler was still running when the UI thread wanted to close the editor.
