### ISSUE TITLE
[oomph/gradle] IDEA projects are broken after setup

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#454]
When choosing IDEA support in the setup, the projects are not compilable after import on a fresh machine. Reason is that IDEA is not downloaded automatically, and the project's dependencies are not properly initialized then.

The IDEA should be downloaded to
   `~/.gradle/ideaSDK/145.972.3`

![screenshot 171](https://user-images.githubusercontent.com/265597/32835347-01d464c0-ca06-11e7-89c1-230c2cd7e51b.png)

Expected is that all projects from the IDEA working set are compiled properly after import.

**Comment by cdietrich** [comment]
@kthoms code is now all on xtext-idea

**Comment by kthoms** [comment]
well, this lowers the severity.

**Comment by cdietrich** [comment]
todo call the launch config you created and see if that helps

**Comment by cdietrich** [comment]
still open ....

**Comment by cdietrich** [comment]
wontfix
