### ISSUE TITLE
[tycho] Put all build target definitions below org.eclipse.xtext.target

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#457]
At the moment targets are distributed into separate subprojects:
- org.eclipse.xtext.target
- org.eclipse.xtext.oxygen.target
- org.eclipse.xtext.photon.target

This does not scale for more targets. Instead all targets should be put into org.eclipse.xtext.target and the build should pick them all. The used target for the build should be selectable through a profile.

This article is a good reference for this approach: http://blog.vogella.com/2013/01/03/tycho-advanced/

**Comment by cdietrich** [comment]
solution need to be applied to xtext-xtend as well.
