### ISSUE TITLE
TraceEditor should allow copying the text

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#464]
open a (hidden) trace file.
you have no chance to copy the text in the bottom of the editor

**Comment by cdietrich** [comment]
looks like org.eclipse.emf.edit.command.CopyToClipboardCommand is used instead of the default swt copy&paste

**Comment by ArneDeutsch** [comment]
The TraceEditor is quite hacky, just a small add-hock-addon for the ecore editor. The way it is implemented it is a bit tricky to extend it in clean way. The provided patch is in that way hacky, too. ut very local and in some way fits to the implementation ;).

It basically sets the selection of the editor to the selected text (via an ISelectionListener), such that CTRL+C is working. In addition it creates a manual context menu with a Copy-Command to highlight the fact, that copy is possible.

The way it is done does not interfere with the selection mechanism of the Ecore editor (selection of nodes in the tree).
