### ISSUE TITLE
Widget is disposed on hover setFocus

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-eclipse#467]
Hover over something with a quickfix and then click the hover box (to call `org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover.setFocus`) to reproduce the error (check your Error Log). This `setFocus` will focus the `fFocusControl` and is called from the last line of the if statement in `org.eclipse.jface.text.AbstractInformationControlManager.replaceInformationControl(boolean)`. After the focus has been set, the next line in `replaceInformationControl(boolean)` is called: `hideInformationControl()` which will call dispore on the previous `AnnotationWithQuickFixesHover`. This then causes a Widget is disposed when trying to redraw the hover box.

**Comment by kthoms** [comment]
Thanks for your observation. Unfortunately I cannot reproduce it. What I did:

Create a dmodel file (for Domainmodel language example) with content
```
entity foo { }
```
This will offer a quickfix for "foo" to capitalize it. The hover box appears and I click on it. From your description I would assume that an exception is raised/logged, but nothing happens.

Could you provide more details?

**Comment by cdietrich** [comment]
cannot reproduce this neither. are you sure there is not something else that steals the focus?

**Comment by tivervac** [comment]
I will do some more in depth research when I find the time for it. Thanks for your initial analysis.

**Comment by tivervac** [comment]
Can't reproduce it now myself, sorry for the trouble.
