### ISSUE TITLE
[examples] Add build metadata

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#501]
The example projects do not contain build files. The examples should be extended by that metadata. It would be better to restructure the projects so that each of them is moved into a sub directory. The packaging scripts have to be adjusted.

**Comment by cdietrich** [comment]
ae we sure everybody has maven or gradle?

**Comment by kthoms** [comment]
Does this really matter? The examples all have Eclipse UI, thus the projects have to be build with Maven anyway. If they have not Maven, the examples have just appropriate examples with them and do not harm. Otherwise you would be glad that you have a reference already in the examples.

**Comment by cdietrich** [comment]
i wonder hat happens if projects have maven nature and stuff but no maven installed

**Comment by kthoms** [comment]
They won't have a Maven nature, that's not necessary. They will just have pom.xml files and additional projects for parent and target.

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by kthoms** [comment]
Status: Done for Domainmodel, open for the others.

**Comment by cdietrich** [comment]
since we have support for build in domainmodel.
do we really want to clutter other samples with that as well?

**Comment by cdietrich** [comment]
cc @kthoms @szarnekow

**Comment by kthoms** [comment]
I'm fine with having just Domainmodel so. I'll close this one. If someone objects please reopen.
