### ISSUE TITLE
Integrate Photon Code Mining API

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#520]
[Photon] Investigate if we can offer Support for the new CodeLens feature
here is the lsp4e bug for that https://bugs.eclipse.org/bugs/show_bug.cgi?id=508458

**Comment by cdietrich** [comment]
@szarnekow how did we introduce support for stuff that is not in the oldest target platform in the past? do we have a pattern for that

**Comment by szarnekow** [comment]
There is no pattern yet. We could use Proxy.newInstance combined with a Class.forName and delegate to our own internal methods. So a bunch of reflective code along with the required extension points.

Maybe it's worthwhile to investigate plugin fragments for that purpose.

**Comment by kthoms** [comment]
We are working on a draft. Looks promising so far.

**Comment by cdietrich** [comment]
:+1:

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by kthoms** [comment]
We have now Code Mining integration, but would like to offer an adapter to Code Lens.

**Comment by kthoms** [comment]
Created follow-up issue eclipse/xtext#2468, so we can close the general integration now.
