### ISSUE TITLE
[Photon+] Support for source folder separation

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#521]
[Photon] Investigate how we behave with the source folder separation

and if we have to / want to do anything about it
https://twitter.com/fbricon/status/952944923732426752

cc @kthoms @szarnekow 

for Xtext 2.15+:

we should have support for source folders that can and cannot see each other (e.g. models in test folder cannot be seen by models in source folder) in our container management infrastructure

**Comment by szarnekow** [comment]
If we are lucky, JDT will handle this for us when the bindings are created. In the worst case, we'd need to introduce the necessary abstractions, too.

In any case, the Java error markers will be propagated to Xtend and the user experience should not suffer too much from the new feature in the JDT.

**Comment by ArneDeutsch** [comment]
Have had a first look about this. Found one issue.

For Xtend it is only possible to specify exactly one output folder for source files (default "xtext-gen" can be configured in project properties under "Xtend -> Compiler". In result generated java files from xtend from production code and from test code resides in the same source folder and generated class files in same output folder. It is possible to work with Xtend by marking the "xtend-gen" source folder as output folder that contains test sources. But then it is of course possible to reference generated test classes from production code, working around the JDT test source folder feature. To solve this issue we would have to support multiple java source output folders based on multiple xtend source folders.

**Comment by cdietrich** [comment]
hmm this is currently only possible if you have maven style layout
e.g.

/src/main/java
/src/main/xtend-gen
/src/test/java
/src/test/xtend-gen

**Comment by ArneDeutsch** [comment]
And that does not play with eclipse plugins (don't know why). Seems we should solve this together. Enable seperation of source xtend folders for simple layout and enable maven layout for eclipse plugins (if possible).

**Comment by cdietrich** [comment]
there is org.eclipse.xtext.builder.EclipseOutputConfigurationProvider.getOutputForSourceFolder(IPreferenceStore, OutputConfiguration, String)

but the  frontend is kind a hidden.

<img width="627" alt="bildschirmfoto 2018-04-26 um 09 47 11" src="https://user-images.githubusercontent.com/238736/39292582-e3a8cfc6-4936-11e8-865b-8b1adef5ac21.png">


see as an example:

```
outlet.DEFAULT_OUTPUT.sourceFolder.src.directory=xtend-gen
outlet.DEFAULT_OUTPUT.sourceFolder.src.ignore=
outlet.DEFAULT_OUTPUT.sourceFolder.test.directory=xtend-test-gen
outlet.DEFAULT_OUTPUT.sourceFolder.test.ignore=
outlet.DEFAULT_OUTPUT.sourceFolder.xtend-gen.directory=
outlet.DEFAULT_OUTPUT.sourceFolder.xtend-gen.ignore=
outlet.DEFAULT_OUTPUT.userOutputPerSourceFolder=true
```

[output.zip](https://github.com/eclipse/xtext-eclipse/files/1950195/output.zip)

**Comment by ArneDeutsch** [comment]
With that UI it works. It is not so easy to configure but in fact it is possible to configure the project in a way that Xtend sources and tests can be seperated. And after the configuration the behaviour is what I would expect.

Anyway we should check if we can enhance the UI a bit. At least we should not hide but only disable the table ... and probably some other UI enhancements come to mind when looking closer.

**Comment by cdietrich** [comment]
i more thought of that our container management (javaprojectstate) should be able to have reduced visibility between source folders

(IContainer.Manager.getVisibleContainers)

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-eclipse/issues/677

**Comment by szarnekow** [comment]
A proper solution will require a major rework of the type lookup API since it is currently using no context information of the requestor. Without knowledge about the classpath entry of the requesting resource, it is not possible to figure which types should really be visible.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
