### ISSUE TITLE
XtextGrammarRefactoringIntegrationTest/XtextGrammarQuickfixProviderTest/Bug486584Test is flaky

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#522]

**Comment by cdietrich** [comment]
have no clue what could cause this.

**Comment by szarnekow** [comment]
Is it still flaky even with the Flaky rule in use?

**Comment by cdietrich** [comment]
did not test that. we could add it to try that.

**Comment by szarnekow** [comment]
I see that the Refactoring test does undeed use the `@Flaky` stuff. Maybe `org.eclipse.xtext.ui.testing.AbstractEditorTest.openEditor(IFile)` should wait for the reconciler?

**Comment by cdietrich** [comment]
shouldnt the explicit `waitForReconciler` calls do that

**Comment by szarnekow** [comment]
But they happen after the invocation of `doRefactor` I can spot a `waitForDisplay` though. Maybe there's something wrong with the overall approach and we should use swt bot tests...

**Comment by cdietrich** [comment]
they are flaky too see https://github.com/eclipse/xtext/issues/2277

**Comment by cdietrich** [comment]
i propose to set the tests to ignore. any other ideas?

**Comment by cdietrich** [comment]
TODO investigate if order is different when fails

**Comment by ArneDeutsch** [comment]
That the tests are flaky is not reproducible locally. Anyway there are two issues fixed in the test. The IResourceChangeListener were not removed, hence are executed way to often even after creating test case has been finished. The listeners are now removed after test case has been finished. Second the IProject was each time the same instance, leading the == test inside the resource change listener to result in true even for projects from different test case. To decouple test cases a new project name is invented for each test case.

**Comment by cdietrich** [comment]
Fixed XtextGrammarQuickfixProviderTest

**Comment by cdietrich** [comment]
@ArneDeutsch can you provide a pr for Bug486584Test

**Comment by cdietrich** [comment]
saw Bug486584Test again: http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/cd_XtextGrammarRefactoringIntegrationTest2/4/

**Comment by cdietrich** [comment]
@ArneDeutsch i can reproduce this if i do a change to BuilderScheduler and schedule with a delay of 10 ms.

=> maybe we need to wait for auto build family (IResSetUtil.reallywait....)

**Comment by cdietrich** [comment]
@szarnekow maybe you can have a quick look too.

**Comment by ArneDeutsch** [comment]
For me this is not reproducable even with a delay of 100ms. Larger values seem not reasonable as the latch is waiting 300ms and will timeout if we wait to long.

**Comment by cdietrich** [comment]
but what if it is is really 1s cause virtualization foo?

**Comment by cdietrich** [comment]
Fixed in 2.14
