### ISSUE TITLE
[J9] Investigate failing domain model tests (and pot. others in samples)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#528]

**Comment by cdietrich** [comment]
i assume this is due missing asm 6 in tp (any meybe other)
and possibly all-system in surefire config

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-core/issues/623 as well

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
Domainmodel is the only example with Tycho build so far. When other examples might be extended, we just follow the example. Can close this now.
