### ISSUE TITLE
EclipseOutputConfigurationProvider.getOutputConfigurations(project) is inefficient

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#535]
EclipseOutputConfigurationProvider.getOutputConfigurations(project) calls createAndOverlayOutputConfiguration over and over again. should not be done if preferences dont change

**Comment by cdietrich** [comment]
@szarnekow @svenefftinge  do know why this is not cached uring the build lifecycle of the (Parallel) Builder Participent

**Comment by svenefftinge** [comment]
I don't know, sorry.

**Comment by szarnekow** [comment]
I'd assume it's "just" an oversight.
