### ISSUE TITLE
[question][quick-fix] Customizing the UI in the quick fix pop-up dialogs

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#542]
Currently, I was unable to customize the label in the quick fix pop-up dialog. If one would like to have something else on the UI but `x quick fixes available` then the entire logic has to be copied over and customized in the downstream projects. See [here](https://github.com/eclipse/xtext-eclipse/blob/b824522b4fbec17ae0428781f9a92448e50552e7/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AnnotationWithQuickFixesHover.java#L322).

The question is; would it make sense to adjust the Xtext code a bit, so that it becomes more flexible and customizable? If so, I can make a contribution here, if no, I just copy it over and change it in the downstream project.

Please note, this point, I do not yet have a clear idea what and how to make it, I just thought it worth an upfront question here, before I start further investigating it. Thanks!

**Comment by cdietrich** [comment]
the question would we what kind of changes you want to do? simply make the methods protected?

**Comment by kittaakos** [comment]
> simply make the methods/types protected

That would be a good start.

> internal so that it can be changed from outside

Internal API would be fine. I assume it is private because there was no real need to expose it yet.

Perhaps the straightforward way would be the following: 
 - We close this issue now.
 - I just copy the private visibility code to the downstream project.
 - I adjust it to the client's requirement, and if it turns out that it is super useful and configurable and others just cannot wait to use it (which I doubt), then we can apply the same changes in Xtext too.

Would that make sense?

**Comment by dhuebner** [comment]
@kittaakos I like your suggestion

**Comment by cdietrich** [comment]
:+1:

**Comment by JanKoehnlein** [comment]
@kittaakos If you came up with a concrete PR, it'd be a bit easier to discuss.
In  the past, we had that "everything is API" approach and did not use _private_ other than by hazard. So changing it to _protected_ was generally not a problem. We changed that a bit recently. Acceptance of such a change would likely depend on our feeling whether there are clients that have gone the same way and copied the private method (these are the ones we'd break).

**Comment by kittaakos** [comment]
OK. Let's close this issue for now. If something useful comes out of my changes, I will open another ticket. Thank you for your feedback!
