### ISSUE TITLE
Examples vs Java 9

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#557]
EMF generation and compilability differs when opening the example projects (e.g. arithmetics)
with a java 9 as only jdk (and thus used for bree)

(compile errors cause Module is a reseved keyword)

so i wonder which versions we should check in

**Comment by cdietrich** [comment]
I propose to regenerate against emf 2.14 and ship that version

**Comment by kthoms** [comment]
Does this mean that EMF 2.14 is the new target?

**Comment by cdietrich** [comment]
no.

**Comment by cdietrich** [comment]
but is has the java 9 fix

**Comment by cdietrich** [comment]
other solutions are welcome too

**Comment by cdietrich** [comment]
e.g. changing the example and replace module with something else.
