### ISSUE TITLE
Evaluate Impact of "Parallel Build of Independent Projects" in Platform

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#558]
Evaluate Impact of "Parallel Build of Independent Projects" in Platform

https://bugs.eclipse.org/bugs/show_bug.cgi?id=530649

**Comment by cdietrich** [comment]
i propose this as "wont fix" for now. @kthoms @szarnekow what do you think?

**Comment by kthoms** [comment]
Yes, AFAIK we are not affected yet. This is opt in and there are no builders for parallel builds enabled yet.

**Comment by szarnekow** [comment]
True
