### ISSUE TITLE
[examples] Refactor test bundle dependency

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#56]
The examples still use the old org.eclipse.xtext.junit4 bundle. This has to be replaced by a dependency on org.eclipse.xtext.testing.

**Comment by kthoms** [comment]
The test classes depend on some framework classes from org.eclipse.xtext.junit4, which are not available in org.eclipse.xtext.testing yet.

Examples:
org.eclipse.xtext.junit4.ui.AbstractOutlineTest
org.eclipse.xtext.junit4.TemporaryFolder

**Comment by cdietrich** [comment]
please note: there some copies of TemporaryFolder at other test projects. these should be consolidated as well

**Comment by meysholdt** [comment]
yes, see eclipse/xtext#1072

**Comment by cdietrich** [comment]
@kthoms @LorenzoBettini is here anything left?
