### ISSUE TITLE
Allow editor to veto adding Xtext nature on open

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-eclipse#568]
When opening a file with an Xtext editor for a project that has no Xtext nature a dialog is opened asking the user if the nature should be added. While this is nice for many use cases it is annoying for a few where the nature is actually not needed (e.g. https://github.com/itemis/jbc/issues/6). Because of this it would be nice if one has a chance to NOT open the dialog for specific cases.

The code that actually opens the editor is inside `org.eclipse.xtext.builder.nature.NatureAddingEditorCallback`. It looks like this:

```
@Override
public void afterCreatePartControl(XtextEditor editor) {
	IResource resource = editor.getResource();
	if (resource != null && !toggleNature.hasNature(resource.getProject()) && resource.getProject().isAccessible()
			&& !resource.getProject().isHidden()) {
```

Proposal would be ta add a method `boolean isXtextNatureRequired()` to the `XtextEditor` with a default implementation to return `true`. One would then be able to override this method to return `false` for specific editors that do not need the nature.

**Comment by kthoms** [comment]
The Xtext nature is usually required when cross-references are used and the language has to support multiple resources. It might be considered to make this not an option to the editor, but more a language config which the editor evaluates. Not sure yet where this could be made, but you might take this as an idea to consider.

**Comment by cdietrich** [comment]
since NatureAddingEditorCallback is editor specific you can simply replace it ?!?

**Comment by ArneDeutsch** [comment]
Works like a charm, thank you! This ticket can be closed then.
