### ISSUE TITLE
Create UI Injector with language's IdeModule

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#576]
The UI injectors are missing the languages IDE module in their merged module. For languages that provide bindings in their IDE module the injector has to be considered in the merged module.

It has to be considered that IDE modules and thus their base class DefaultIdeModule only exist in Xtext >= 2.11. It could be possible that a language has been built with a newer Xtext version, but is installed on an older Xtext platform. Then the platform will not contain the org.eclipse.xtext.ide bundle, which can be checked.

Currently the language specific IDE bundles also do not export the main package of the bundle. This is necessary to use the IDE module classes.

The generated activator class thus should create the language's IdeModule and include it in the merged module if the platform supports org.eclipse.xtext.ide.

Affects all languages, examples and test languages.

**Comment by tomaswolf** [comment]
Does this mean that one now _needs_ lsp4e? The binding at [RefactorNameElementFragment2](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/refactoring/RefactorElementNameFragment2.xtend#L194) would then be active in UI, and thus an installed UI bundle will require lsp4e to be installed, too. Or am I missing something?

**Comment by cdietrich** [comment]
you mean lsp4j correct. @kthoms did you look at that?

**Comment by tomaswolf** [comment]
Yeah, lsp4j, of course. I constantly mistype one for the other.

**Comment by kthoms** [comment]
Yes, I'm aware of that. Any problem with that? IMHO not.

**Comment by cdietrich** [comment]
Lsp is usually not installed / optional

**Comment by kthoms** [comment]
The ICodeLensService has also this dependency, which will be used to implement code mining. However, this dependency is optional until a service implementation is provided.
lsp4j is just a small runtime dependency. Would this be a problem?

**Comment by cdietrich** [comment]
i mean it is e.g. not provided by our update site etc.

**Comment by cdietrich** [comment]
And for code lense I would have expected a interface that is agnostic of eclipse and lsp and there are two adapters to lsp and eclipse similar as it is done for proposals

for me it looks like this was not taken care of in the first draft of the interface 
(AFAIK it’s not even api yet)

**Comment by cdietrich** [comment]
And I am totally unsure how realistic these breaking scenarios are

- jit binding in ui Module and explicit binding in ide
- ide overriding explicit binding in runtime module

**Comment by szarnekow** [comment]
I totally share Christians and Thomas concerns here. This change would be prone to many subtle bugs and changed behavior. It does not carry its own weight and we should rather proceed with the current architecture / injector hierarchy.

**Comment by kthoms** [comment]
We decided to not implement this.
