### ISSUE TITLE
XtextDocument.readOnly[] hands null resources to IUnitOfWork

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-eclipse#587]
From time to time we've been seeing stacktraces from clients that show that the Resource that is passed to `XtextDocument.readOnly[]` is `null`. The `readOnly` function is used in a lot of places in our code but we don't have any null checks in those places. Should we really be adding a null check everytime?

Having a look at the code I would rather suggest to add a null check around [here](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java#L506).
However, the OutdatedStateManager [appears to be ok with a resource being null](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/resource/OutdatedStateManager.xtend#L64). This makes me think that allowing null resources is intentional.

**Comment by tivervac** [comment]
@szarnekow Would like your input on this matter

**Comment by szarnekow** [comment]
Hey @tivervac - the resource can indeed be null in some rare situations (usually when eclipse is restarted with open editors when files have been removed from disk in the meantime, IIRC). I don't have a strong preference, but readOnly sometimes is supposed to return a primitive. If we simply skip the call for null resources, we still need to return something from the readOnly call... Do you have an idea what you would do about this? In general I do agree, that it's nasty to get a null resource, though.

**Comment by tivervac** [comment]
I guess the best way to go about it without breaking backwards compatibility, would be to return a default value and add a new method `<T> T readOnlyOrDefault(IUnitOfWork<T,P> work, T default);` in `org.eclipse.xtext.util.concurrent.IReadAccess<P>` to override said default.

**Comment by szarnekow** [comment]
Yes, a default impl there would do. Still you’d need to adjust all call sites.

**Comment by szarnekow** [comment]
Would the default be the result in case of null or in case of exceptions, too?

**Comment by tivervac** [comment]
In the [current implementation](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java#L498) exceptions are wrapped and rethrown so I would keep that as is.

**Comment by tivervac** [comment]
Call sites should probably be updated to make sure they are using the correct default. However, things should be better than they were before, even without edits, as there are no more NPE's. For the few examples I checked in Xtext code, there are no null checks in place for the callsites.

**Comment by szarnekow** [comment]
Are you planning to provide a patch?

**Comment by tivervac** [comment]
Yes I am

**Comment by tivervac** [comment]
Fixed by #622 and https://github.com/eclipse/xtext-core/pull/682
