### ISSUE TITLE
New DSL File Wizard

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-eclipse#599]
Creating new files for a DSL currently requires the user to use the standard "New File Wizard" from eclipse. We should implement an wizard for a DSL that is generated and creates files based on templates that are defined by the DSL developer. Such templates might look similar to the project templates developed in https://github.com/eclipse/xtext/issues/1154 . If only one template is provided no selection page should be displayed.

**Comment by ArneDeutsch** [comment]
The wizard presents a text field with browse botton for the folder and a text box for a name togetehr with all parameters on one page.

The wizard is able to create any number of files from teh template.

If multiple templates are provided through the extension point the wizards renders a combobox to select the template and provides a second page to select configure the selected template.

Most code for template configuration is reused from the template based new project wizard.

**Comment by cdietrich** [comment]
@ArneDeutsch anything left for this issue?

**Comment by ArneDeutsch** [comment]
Just found a bug in the way the internationalization is genereated from the templates when BOTH, the NewFileWizard and NewProjectWizard are generated. Need to investigate.

**Comment by ArneDeutsch** [comment]
The previews three comits fix the race condition between the annotation processors. They achieve this by synchronize against each other. In addition it is necessary, that the read operations of ParallelFileSystemSupport wait for all the write operations in the queue to be executed. Please review with extra care!

**Comment by ArneDeutsch** [comment]
I think we can close this issue. Possible future refactorings are handled in seperate ticket: https://github.com/eclipse/xtext-core/issues/709

**Comment by ArneDeutsch** [comment]
Just realize that https://github.com/eclipse/xtext-eclipse/pull/635 is not yet merged. Without this change the generation of the internationalization files does not work correctly in all cases.

**Comment by cdietrich** [comment]
Shipped with 2.14
