### ISSUE TITLE
Slow autocompletion because of CompletionPrefixProvider.getLastCompleteNodeByOffset

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-eclipse#616]
The current implementation of `CompletionPrefixProvider.getLastCompleteNodeByOffset` has linear complexity. The algorithm does a depth first traversal from start to the current offset and remembers the last leaf node with specific properties. In effect all leaf nodes before the current offset are visited. For large files this can be a significant overhead when executing autocompletion (I have large example files from customer where this takes 100-300ms). This can be reduced dramatically my utilising the tree structure of the node model.

Proposed algorithm: Do a depth first traversal the node model in reversed direction and stop at the first found node before the current offset with specific properties. This way complete composite nodes can be skipped. This changes the algorithm complexity from `n` to `log(n)` in most cases (degenerated case ... flat node model) and in my experiments reduces the times from 100-300ms to <10ms.

**Comment by cdietrich** [comment]
fixed in 2.14
