### ISSUE TITLE
API-Diff Job on JIP fails cause of code mining

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#624]
https://ci.eclipse.org/xtext/view/Xtext-Xtend/job/xtext-xtend-api-diff/1520/console

**Comment by cdietrich** [comment]
@kthoms is it possible a photon update site has to be added/used in the config?
@dhuebner can this somehow be executed locally?

**Comment by kthoms** [comment]
Using a Photon M6 SDK as basis now. I ran into similar exceptions due to missing classes afterwards. This was solved by installing Xtext SDK and some of its dependencies (lsp4j, m2e.core) with the p2 director.

Fixed with https://ci.eclipse.org/xtext/job/xtext-xtend-api-diff/1543/
