### ISSUE TITLE
Simrel tests job fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#625]
https://ci.eclipse.org/xtext/view/Simrel/job/simrel-tests/

have no idea what this job does and why it fails
https://ci.eclipse.org/xtext/view/Simrel/job/simrel-tests/

**Comment by cdietrich** [comment]
@dhuebner any idea?

**Comment by cdietrich** [comment]
and you @dhuebner ?
can this be reproduced locally somehow.
if i click on the files that cannot be found by the build it seems to work

**Comment by dhuebner** [comment]
@cdietrich This job tests that a p2 repository is ready to be contributed to an eclipse common repository. Some of the test are for example a valid signature test, valid version pattern,  valid bundle/provider name test and so on. See https://ci.eclipse.org/xtext/job/simrel-tests/lastSuccessfulBuild/artifact/build-result/reporeports/reports/

**Comment by cdietrich** [comment]
but why does it fail?

**Comment by dhuebner** [comment]
I suppose because it can not create a tmp file, but I'm not sure. Earlier the tmp folder was a linked folder to an another volume, may be it's full?
I also noticed that @kthoms created all the new jobs in jenkins it now takes around 119GB hard drive space maybe it also somehow depends. 


```
Compiled 2018-04-03-13:30:02

Projects exceeding 80G of disk space on HIPP/JIPPs:
===================================================
844G /jobs/genie.packaging
310G /jobs/genie.openj9
176G /jobs/genie.capella
156G /jobs/genie.kitalpha
119G /jobs/genie.xtext
92G /jobs/genie.platform
89G /jobs/genie.app4mc
87G /jobs/genie.osee
82G /jobs/genie.ice
===================================================

If you find your project's name in the above list, please check
your Hudson/Jenkins configuration and try to lower the disk usage.

```

**Comment by cdietrich** [comment]
what is inside /tmp/xtext?

**Comment by kthoms** [comment]
Nothing inside. I look further.

**Comment by kthoms** [comment]
Failure [pack200data.txt](https://ci.eclipse.org/xtext/view/Simrel/job/simrel-tests/lastSuccessfulBuild/artifact/build-result/reporeports/reports/pack200data.txt):

```

   Directory checked: /home/hudson/genie.xtext/.jenkins/jobs/simrel-tests/workspace/build-result/p2.repository/plugins

 Check of packed and not packed bundles.
   Number of jar files 113
   Number of pack.gz files 54
   Difference, number of jar files to check: 59
   Checked 59 of 59.
   Errors found: 6
org.antlr.runtime_3.2.0.v201101311130.jar contains java but is not packed
org.apache.commons.lang_2.6.0.v201404270220.jar contains java but is not packed
org.apache.log4j_1.2.15.v201012070815.jar contains java but is not packed
org.junit_4.12.0.v201504281640.jar contains java but is not packed
org.objectweb.asm.tree_6.0.0.v20180116-1719.jar contains java but is not packed
org.objectweb.asm_6.0.0.v20180116-1719.jar contains java but is not packed
```

**Comment by cdietrich** [comment]
TODO might be obsolete by https://github.com/eclipse/xtext/issues/1264

**Comment by cdietrich** [comment]
since pack200 is deprecated we will remove it from the build anyway.
=> wontfix

**Comment by cdietrich** [comment]
TODO: remove/invert pack200 test

**Comment by cdietrich** [comment]
Is Fixed
