### ISSUE TITLE
JavaProjectFactory#enhanceProject adding wrong classpath entries

### ISSUE THREAD

**Issue by nloke** [eclipse/xtext-eclipse#626]
In the enhanceProject I believe it should be using

`for (final IProject referencedProject : project.getReferencedProjects()) {`

instead of

`for (final IProject referencedProject : project.getReferencingProjects()) {`

This is causing cyclic dependency for my implementation which will eventually bring the other dependency through maven.

**Comment by cdietrich** [comment]
@szarnekow @kthoms  this looks like a bug to me

**Comment by cdietrich** [comment]
fixed in 2.14

**Comment by cdietrich** [comment]
How do you use that code?

**Comment by nloke** [comment]
We have a proprietary project nature. When we import from git or import as a maven project, we have a custom project factory the extends PluginProjectFactory that converts the normal/maven project to our project nature. 

We overridden the enhanceProject method and still calling the super enhanceProject  in PluginProjectFactory which eventually calls the JavaProjectFactory

**Comment by cdietrich** [comment]
i always write big fat FIXME TODO for all workarounds i have in place in customer projects. and usually a issue with the update and a list ;)
