### ISSUE TITLE
Xtext Examples - Java classes starting with lower case letters are generated

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#631]
The Xtext Homeautomation and the Xtext State-Machine Example generates Java classes starting with lower case letters:
![screenshot](https://user-images.githubusercontent.com/20393472/38421236-bffb0a8e-39a6-11e8-8457-88def5229632.png)

The generators of these examples should be improved to generate java files/java classes with upper case letters.

**Comment by cdietrich** [comment]
fixed in 2.14. thx @miklossy
