### ISSUE TITLE
[JIPP] commons-deploy (mwe2) fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#646]
https://ci.eclipse.org/xtext/job/common-deploy/10401/

Started by upstream project "nightly-deploy" build number 1645
originally caused by:
 Started by timer
Building in workspace /home/hudson/genie.xtext/.jenkins/jobs/common-deploy/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Script returned: #10401 (mwe2)
[workspace] $ /bin/sh -xe /tmp/genie.xtext/jenkins4350267239501804177.sh
+ groups
signers modeling.emf.mwe modeling.tmf.xtext modeling.emf.emf modeling.m2t.xpand
Unable to access upstream artifacts area /home/hudson/genie.xtext/.jenkins/jobs/mwe2/builds/107/archive. Does source project archive artifacts?
ERROR: Failed to copy artifacts from mwe2 with filter: build-result/**
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

@kthoms is here something configured wrongly?
looks like https://ci.eclipse.org/xtext/view/MWE/job/mwe2/ does not archive anything

**Comment by cdietrich** [comment]
<img width="1115" alt="bildschirmfoto 2018-04-22 um 09 42 58" src="https://user-images.githubusercontent.com/238736/39092590-9d9a1a26-4611-11e8-86a8-92818c50cec3.png">

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by kthoms** [comment]
Job missed archiving the `build-results` directory content. Fixed job https://ci.eclipse.org/xtext/job/mwe2/
