### ISSUE TITLE
Provide test infrastructure for testing customized DoubleClickStrategyProvider

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#654]
Some Xtext-based languages ([Eclipse Xtend](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/XtendDoubleClickStrategyProvider.java), [Eclipse GEF DOT](https://bugs.eclipse.org/bugs/show_bug.cgi?id=532244)) require a customized DoubleClickStrategyProvider. 

See also https://www.eclipse.org/forums/index.php/t/373244/.

It would be useful to extend the Xtext test infrastructure to enable a comfortable testing of such customized DoubleClickStrategyProvider behaviour.

**Comment by cdietrich** [comment]
Fixed in 2.14
