### ISSUE TITLE
Reset prompt dialog settings has no margin

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/xtext-eclipse#656]
The preference to reset the "Don't ask again" dialogs explicitly sets zero pixels margin. That leads to bad layout: 
![image](https://user-images.githubusercontent.com/406876/39523412-ca310ea8-4e15-11e8-9a9c-fd8efcdcdc2f.png)

Relevant is probably https://github.com/eclipse/xtext-eclipse/blob/581a5c827c4c32860d3bfb2fcc046c6fdd80f578/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/preferences/ResetPromptDialogSettingsField.java#L69 and the following line.

**Comment by cdietrich** [comment]
Fixed in 2.14
