### ISSUE TITLE
Activator.isJUnit5Available() must inspect target platform

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-eclipse#657]
Currently it checks the installation but not the TP. I do have Junit5 deployed in my Eclipse but not in my TP. Thus Junit4 should be the default.

See org.eclipse.xtext.xtext.ui.Activator.isJUnit5Available()

**Comment by cdietrich** [comment]
i think we should go live with junit 4 enabled by default. i thought @kthoms already did change that

**Comment by kthoms** [comment]
Yes, did that but forgot to create the PR for it. Here it is: #658

This issue stays valid, we should detect the state from the target platform if possible. This might introduce a dependency on PDE, which might be undesired.

**Comment by cdietrich** [comment]
Remove check, select JUnit5 by default

**Comment by cdietrich** [comment]
Fixed
