### ISSUE TITLE
[Documentation] Update 3.0.5 Xbase to new Workflow

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#69]
- jvm types requires inheriting from "org.eclipse.xtext.xbase.Xtype" or adaption of the workflow `commonTypesSupport = { onlyEnabledIfGrammarIsUsed = false}`
- the hints on the workflow still uses old style workflow

**Comment by spoenemann** [comment]
I don't understand the issue. Could you explain a bit more?

**Comment by cdietrich** [comment]
Read the chapter and apply it to a non xbase project. You will see that simply importing common types and reference it won't work if you don't inherit from xtype. But the docs suggest so. The examples in the chapter referr to old workflow

**Comment by spoenemann** [comment]
Ah ok. Documentation issues should be reported to https://github.com/eclipse/xtext/issues, since the website is still built from there (maintenance branch).

**Comment by cdietrich** [comment]
well is that a leftover for migration? the code for docs is in xtext-eclipse thus i reported it here?

**Comment by cdietrich** [comment]
@spoenemann i did a lot of doc updates to xtext-eclipse? so these wont be visible?

**Comment by spoenemann** [comment]
You mean `org.eclipse.xtext.doc`? That content has been generated from the website documentation, so we have a singe source. Please contribute your fixes to the maintenance branch in the umbrella repo.

**Comment by spoenemann** [comment]
See https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.doc/gen_eclipse_help.xml

**Comment by cdietrich** [comment]
i mean the project xtext-xtend/org.eclipse.xtend.doc and xtext-eclipse/org.eclipse.xtext.doc

i currently have no time to do this. why where the pull requests reviewed then in the first place? i am sure this is not on mine pull requests only but ones from others as well.

**Comment by cdietrich** [comment]
shouldnt our oomph then clone maintenance umbrella as well?

**Comment by spoenemann** [comment]
> shouldnt our oomph then clone maintenance umbrella as well?

Maybe, but first we should create a new documentation branch on the xtext repo in order to avoid a huge workspace to be checked out. I created eclipse/xtext#1076 for that.

You mean the PRs #43, #45, #52, #54? Yes, it was not good to merge them. Those fixes should be applied to the website and we should invoke the doc generator before the next release.

**Comment by cdietrich** [comment]
yes and more:
the commits 
0a93aafef4b9bffce160c8c9b676f2290a44a763
9ee9b5b8ece176c862aca03ac9aea0c2ebe2a6a5
9b041f2071ceb6629b26b7979d1383e4eb4f5f17
a59532c43aaa5335e519cc9ba312fb40659e5500
ab4474d1eeffe01699209baf904719408f6d14e6
3e33052524b9c443d31321590514ea75cece70ab
here and

 there is https://github.com/eclipse/xtext-xtend/pull/2

**Comment by LorenzoBettini** [comment]
So if we want to update some documentation which files should be edited? Directly the html files in https://github.com/eclipse/xtext-eclipse/tree/master/org.eclipse.xtext.doc/contents ?

**Comment by spoenemann** [comment]
No, the Markdown files in https://github.com/eclipse/xtext/tree/maintenance/xtext-website/documentation

**Comment by cdietrich** [comment]
Fixed on website-published
