### ISSUE TITLE
Contribute the 'Xtext XML Editor Example'

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#690]
I created a simple XML Editor based on Xtext and would like to contribute it to the Xtext framework under org.eclipse.xtext.xtext.ui.examples/projects.

This example is based on a stateful lexer (a.k.a usage of lexer modes), thus represents how to integrate a custom lexer into Xtext-based projects.

**Comment by miklossy** [comment]
The project is available under https://github.com/itemis/xtext-issues/tree/issues/xtext-eclipse/690

**Comment by cdietrich** [comment]
i am not sure about that. what do you think @kthoms @szarnekow

**Comment by kthoms** [comment]
I don't think that we should maintain more Xtext examples in Xtext itself. Maybe we can have another repo collecting such examples, but again, who would take care for maintenance?

I'd prefer some external location.

**Comment by miklossy** [comment]
I think that maintaining an example project is much easier if it is part of the Xtext framework than if it resides in some external location.

**Comment by kthoms** [comment]
For you, yes. For us, no.

**Comment by cdietrich** [comment]
i dont want to take the additional burden of maintenance. thus i will close as wontfix.
