### ISSUE TITLE
[wizard] project wizard creates gradle project with snapshot dependency

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-eclipse#692]
When I create a new Xtext project with generic IDE support, the Gradle build will be configured to use a dependency on 2.14.0-SNAPSHOT, which is obsolete now and likely to be deleted.

Haven't checked for Maven yet.

**Comment by cdietrich** [comment]
are you sure you have the release version installed? i get

```
subprojects {
	ext.xtextVersion = '2.14.0'
```

**Comment by JanKoehnlein** [comment]
OK, my bad.
