### ISSUE TITLE
Improve the Formatter of the Xtext State-Machine Example

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#699]
Currently, the Xtext State-Machine Example Formatter contains only the generated stub based on the AbstractDeclarativeFormatter API. 

- The formatter should be switched to the AbstractFormatter2 API.
- The generated formatter stub should be implemented to improve the statemachine dsl formatting result.

**Comment by cdietrich** [comment]
Fixed in 2.15
