### ISSUE TITLE
Xtext 'Domain-Model Example' failing UI test case.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#755]
When creating a fresh Xtext 'Domain-Model Example' (Xtext Complete SDK	2.15.0.v20180716-0209) into a Photon Workspace on Windows, the ContentAssistTest.testTemplateProposal is failing:

![screenshot](https://user-images.githubusercontent.com/20393472/42862546-43ce7ddc-8a60-11e8-8eea-eeb0accc21e5.png)

Expected line ending: Windows style
Actual line ending: Unix sytle

@ArneDeutsch Could you please execute this test case on Windows and give feedback wheter you can reproduce this issue?

**Comment by cdietrich** [comment]
@miklossy i can confirm the failing test on windows.
i am not even sure if this is a test or a template problem

i think the template contains windows style endings.
but when inserted there is linux style endings so i wonder where
the replacement happens and why. maybe already in template reader.

would be interesting to know how other templates e.g from jdt behave in that regard.
but where are they replaced. maybe the templates are "re-platformized" on insert.

@szarnekow @kthoms what do you think

**Comment by cdietrich** [comment]
p.s. i have a kind a deja-vu on a existng github issue or bugzilla but did not find one on the first glance

**Comment by szarnekow** [comment]
I think it should be possible to customize the apply method of the template proposal. It should make sure that it uses the line delimiter as it is present in the document.

**Comment by szarnekow** [comment]
see org.eclipse.xtext.ui.editor.templates.XtextTemplateProposal.apply(ITextViewer, char, int, int)

**Comment by szarnekow** [comment]
Even better: org.eclipse.xtext.ui.editor.templates.XtextTemplateContext.IndentationAwareTemplateTranslator

**Comment by miklossy** [comment]
I agree with @szarnekow that the template proposal should insert the templates using the line endings that already present in the document, independently of the line ending of the templates.xml file. Currently, the template proposal inserts the entity template of the Domain-Model Example using Unix style endings even if the document has Window style line delimiters:
![screenshot2](https://user-images.githubusercontent.com/20393472/42923072-e5b8b31a-8b23-11e8-8869-314e018d3712.png)

**Comment by holgerschill** [comment]
Looks like this is fixed, right?

**Comment by miklossy** [comment]
No, the problem still exists.

**Comment by cdietrich** [comment]
@miklossy are you working on this issue? if not it would be a good candidate i think

**Comment by ArneDeutsch** [comment]
Observed a similar issue (probably the same with cahnged test name). For me the two test cases `testPackageTemplateProposal` and `testEntityTemplateProposal` are failing.

**Comment by ArneDeutsch** [comment]
I changed the code to use the line delimiter from the first line of the document if presetn. Otherwise use the system line delimiter.

**Comment by ArneDeutsch** [comment]
Fixed.
