### ISSUE TITLE
No Run as Junit Test on XbaseIntegrationTest in Domainmodel Example

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#768]

**Comment by miklossy** [comment]
Could you please give more context on this issue?

**Comment by miklossy** [comment]
Same for

- Homeautomation.FormatterTest
- Homeautomation.ParserTest

All these test cases have inherited (no declared) test methods.

**Comment by cdietrich** [comment]
Yes that is that I mean

**Comment by cdietrich** [comment]
@miklossy  is this fixed now?

**Comment by miklossy** [comment]
Yes, ticket can be closed.

**Comment by cdietrich** [comment]
Fixed in 2.15
