### ISSUE TITLE
[JavaDoc] Cannot link ctor in Xtend files

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#782]
The constructor linking in the Java files work.
```java
/**
 * See {@link A#A(int, int, int) here}.
 * </br>
 * See {@link #A(int, int, int) here}.
 */
public class A {
	A(int a, int b, int c) {}
}
```

But it does not work in Xtend files. (Also works with the generated source.)
```java
/**
 * See {@link B#B(int, int, int) here}.
 * </br>
 * See {@link #B(int, int, int) here}.
 */
class B {
	new(int a, int b, int c) {}
}
```

![javadoc-ctor-link](https://user-images.githubusercontent.com/1405703/43905057-7deafdc8-9bf0-11e8-8081-4a1d8af6dc68.gif)

It works when linking methods.
```java
/**
 * See {@link B#B(int, int, int) here}.
 * </br>
 * See {@link #B(int, int, int) here}.
 */
class B {
	new(int a, int b, int c) {}
	
	def foo() {}
	/**
	 * See {@link B#foo here}.
	 */
	def bar() {}
}
```

![jsdoc-method-link](https://user-images.githubusercontent.com/1405703/43905042-7919a286-9bf0-11e8-8a8d-6d89d8763838.gif)

Should be the same with the `@see #B(int, int, int)` construct.

**Comment by cdietrich** [comment]
Fixed in 2.15
