### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by UdoW** [eclipse/xtext-eclipse#785]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.xtext.util.MergeableManifest (file:/D:/pool/plugins/org.eclipse.xtext.util_2.14.0.v20180522-1821.jar) to field java.util.jar.Manifest.attr
WARNING: Please consider reporting this to the maintainers of org.eclipse.xtext.util.MergeableManifest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

WARNING: Illegal reflective access by org.eclipse.xtext.util.MergeableManifest (file:/D:/pool/plugins/org.eclipse.xtext.util_2.14.0.v20180522-1821.jar) to field java.util.jar.Manifest.attr
WARNING: Illegal reflective access by org.eclipse.xtext.util.MergeableManifest$OrderAwareAttributes (file:/D:/pool/plugins/org.eclipse.xtext.util_2.14.0.v20180522-1821.jar) to field java.util.jar.Attributes.map

I use Java 10.0.2.

**Comment by cdietrich** [comment]
Duplicates https://github.com/eclipse/xtext-core/issues/506
particular issue with MergeableManifest is fixed in 2.15
