### ISSUE TITLE
Investigate failing content assist tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#790]
cc @ArneDeutsch 

http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/106/

do we need to regenerate languages?

@szarnekow shouldnt that work without regen?

**Comment by cdietrich** [comment]
@ArneDeutsch reverting your change to `org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.getPrefix(INode)` seems to solve the problem

**Comment by cdietrich** [comment]
i wonder if you miss a null guard

```
if (nodeBefore != null && nodeBefore.getSyntaxErrorMessage() != null) {
					startingNode = nodeBefore;
				} else {
					break;
				}
```

**Comment by cdietrich** [comment]
does not fix all failing tests

**Comment by cdietrich** [comment]
prefix is `<==` instead of `<=` (two appends to list)

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/cd_eclipse_issue790/2/

**Comment by ArneDeutsch** [comment]
Should be fixed with reverts from https://github.com/eclipse/xtext/issues/2587:
- https://github.com/eclipse/xtext-core/pull/820
- https://github.com/eclipse/xtext-eclipse/pull/791

**Comment by cdietrich** [comment]
tests are green again
