### ISSUE TITLE
ResourceDescriptionUpdaterTest.testIndependentProjects is flaky

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#796]
ResourceDescriptionUpdaterTest.testIndependentProjects is flaky

```
Fehlermeldung

source

Stacktrace

java.lang.AssertionError: source
	at org.eclipse.xtext.builder.impl.ResourceDescriptionUpdaterTest.testIndependentProjects(ResourceDescriptionUpdaterTest.java:61)
```

http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/cd_core_issue822b/lastCompletedBuild/testReport/org.eclipse.xtext.builder.impl/ResourceDescriptionUpdaterTest/testIndependentProjects/
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/cd_issue1266_asm62/6/testReport/junit/org.eclipse.xtext.builder.impl/ResourceDescriptionUpdaterTest/testIndependentProjects/

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/161/testReport/junit/org.eclipse.xtext.builder.impl/ResourceDescriptionUpdaterTest/testIndependentProjects/

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/223/testReport/junit/org.eclipse.xtext.builder.impl/ResourceDescriptionUpdaterTest/testIndependentProjects/

**Comment by ArneDeutsch** [comment]
Guess it is because AbstractParticipatingBuilderTest is not thread safe. Will make it so and hope it will prevent the flakynes.

**Comment by ArneDeutsch** [comment]
Class is now thread safe. Hopefully test is now stable.
