### ISSUE TITLE
Provide automated tests examples

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#813]
Example Wizard Tests with SWTBot or similar technology

- Materialize all Xtext and Xtend examples - no errors or warnings are supposed to appear
  - Regenerate - no changes are supposed to happen
  - Run the unit tests that are part of the example
  - Run cmd line builds - Must succeed
- Xtext Wizard Tests
  - All combinations of build tech and project layout
  - Generate language - No compile errors / warnings
  - Change super language to Xbase
  - Generate - No compile errors / warnings
  - Run sample unit test(s) - Must succeed.

**Comment by cdietrich** [comment]
@ArneDeutsch  this is not working cause the target and parent files are not found.
i would expect that you run against a "fresh" target files that uses the eclipse update site and the built xtext update site only.

**Comment by cdietrich** [comment]
@ArneDeutsch do you see any chance to get this into 2.16. if not please set the milestone to 2.17

**Comment by ArneDeutsch** [comment]
Done. The tests are running on travis (https://travis-ci.org/) against the nightly repo. Tests are maintained here: https://github.com/itemis/xtext-reference-projects/tree/master/integrationtests
