### ISSUE TITLE
xtext ide 2.15+ fails for completion provider.

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/xtext-eclipse#834]
When user tries to get the code completion suggestion using crtl+space the default xtext return the following proposals

CompletionList [
  isIncomplete = true
  items = ArrayList (
    CompletionItem [
      label = "SeverityLevel::DEBUG"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00000"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::DEBUG"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ],
    CompletionItem [
      label = "SeverityLevel::ERROR"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00001"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::ERROR"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ],
    CompletionItem [
      label = "SeverityLevel::FATAL"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00002"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::FATAL"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ],
    CompletionItem [
      label = "SeverityLevel::INFO"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00003"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::INFO"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ],
    CompletionItem [
      label = "SeverityLevel::TRACE"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00004"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::TRACE"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ],
    CompletionItem [
      label = "SeverityLevel::WARN"
      kind = Value
      detail = "EnumerationLiteral"
      documentation = Either [
        left = null
        right = null
      ]
      deprecated = null
      preselect = null
      sortText = "00005"
      filterText = null
      insertText = null
      insertTextFormat = null
      textEdit = TextEdit [
        range = Range [
          start = Position [
            line = 14
            character = 17
          ]
          end = Position [
            line = 14
            character = 32
          ]
        ]
        newText = "SeverityLevel::WARN"
      ]
      additionalTextEdits = null
      commitCharacters = null
      command = null
      data = null
    ]
  )
]

We can see the data 

      documentation = Either [
        left = null
        right = null
      ]

and this is not being accepted by lsp4j  and failed in ReflectiveMessageValidator with following error message

org.eclipse.lsp4j.jsonrpc.MessageIssueException: An Either instance must not be empty. Path: $.result.items[0].documentation

This was working fine with lsp4j version 0.4.0 as this validation was not present in old lsp4j version
Please provide the help on how to fix this issue?

**Comment by kittaakos** [comment]
The default implementation does not create the `Either` type but sets the [`documentation`](https://github.com/eclipse/xtext-core/blob/9e46f302bb7bfd68b61f1a05f1c9bb5d830b7fa1/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/ContentAssistEntry.xtend#L50) string as is.

https://github.com/eclipse/xtext-core/blob/9e46f302bb7bfd68b61f1a05f1c9bb5d830b7fa1/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.xtend#L95

It is either a bug in LSP4J or there is a customized `ContentAssistService` which needs to be adjusted.

**Comment by cdietrich** [comment]
we might be affected by the same "either" problem at other places. so this might even be a "Bug" in lsp4j which should reject (or better redirect) either.forLeft....

**Comment by cdietrich** [comment]
=> pot. workaround would be to set documentation to empty string in content assist service impl

**Comment by cdietrich** [comment]
@kittaakos should i open a lsp4j bug?

**Comment by Rajsmit** [comment]
@cdietrich we don't have any customized creation of completion items.

**Comment by kittaakos** [comment]
> @kittaakos should i open a lsp4j bug?

Yes, please. I am not sure if this is a bug in LSP4J, but I do not see the problem in `xtext-core` itself.

**Comment by cdietrich** [comment]
TODO check other places that might be affected too

**Comment by dhuebner** [comment]
@Rajsmit Fixed in Lsp4J 0.6.0-SNAPSHOT 
Consider to override the ContentAssistService.toCompletionItem(ContentAssistEntry, int, Position, Document) to set the documentation to empty string when `!item.documentation.isLeft && !item.documentation.isRight`

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/issues/893

**Comment by cdietrich** [comment]
example workaround https://github.com/itemis/xtext-languageserver-example/pull/36/commits/5d77f3b2608144024b90dd372e618d1d0459b959

**Comment by cdietrich** [comment]
Fixed with the new LSP
