### ISSUE TITLE
Provide ui test infrastructure for testing Quickfixes.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#839]
It would be useful to extend the Xtext ui test infrastructure to enable the comfortable testing of Quickfixes.
See also https://www.eclipse.org/forums/index.php/t/1066662/

**Comment by kthoms** [comment]
New class AbstractQuickfixTest is introduced

**Comment by miklossy** [comment]
Adding the following QuickfixTest test case to the DomainModel Example
```
	@Test def fix_unused_imports2() {
		'''
			import java.util.Date
			import java.util.List
			
			entity Blog {
				posts : List<Post>
			}
			
			entity Post {}
		'''.testQuickfixesOn(IMPORT_UNUSED,
			new Quickfix(
				"Organize imports",
				"Organizes the whole import section. Removes wildcard imports as well as duplicates and unused ones.",
				'''
					import java.util.List
					
					entity Blog {
						posts : List<Post>
					}
					
					entity Post {}
				'''
			)
		)
	}
```
and execute it results in a test failure.
![screenshot](https://user-images.githubusercontent.com/20393472/48271692-2c2bb500-e43d-11e8-8ee9-e4f44c77e373.png)

There might be a problem in the [AbstractQuickfixTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend) class.
