### ISSUE TITLE
Build against 2018-12 (latest) fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#841]
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'osgi.bundle; org.eclipse.equinox.ds 1.0.0' but it could not be found

Needs to be checked where this dependency came from before and why it is no longer there @kthoms do you have any idea?

**Comment by cdietrich** [comment]
See 
https://github.com/eclipse/rt.equinox.bundles/commit/13571d09f8a1213ae309fc5ac328eaecab7c70c3 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538737

**Comment by cdietrich** [comment]
Xtext-xtend is affected too

**Comment by akurtakov** [comment]
http://download.eclipse.org/eclipse/updates/4.10-I-builds/I20181002-1800/plugins/org.eclipse.equinox.ds_1.5.200.v20180827-1235.jar is still there

**Comment by cdietrich** [comment]
@akurtakov does that mean we need an explicit dependency to the bundle now?
But that won’t be a long term solution if it will completely go
Do you know if the Felix plugin is already there in oxygen, photon and 2018-09

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538729

**Comment by cdietrich** [comment]
@kthoms could you please create a branch without the extra requirement to se what we do need it for

**Comment by cdietrich** [comment]
same problem with tycho 1.3.0-SNAPSHOT
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/cd_issue841/6/console
i wonder if there is something wrong with our setup/tests/baseclasses

**Comment by cdietrich** [comment]
Fixed by using and autostarting apache.felix.scr
