### ISSUE TITLE
MouseOver Tooltip's size is wrong

### ISSUE THREAD

**Issue by MarkusAmshove** [eclipse/xtext-eclipse#89]
Heya,

we've stumbled across a problem where the tooltip, when hovering over an EObject with custom description, it doesn't set it's height according to the content.
## Reproduction:

Create new Xtext project with Eclipse and Generic IDE Support.

Take the following grammar:

``` antlr
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
    greetings+=Element*;

Element:
    Greeting | Person;

Greeting:
    'Hello' name=[Person] '!';

Person:
    'Person'
    name=ID
    age=INT
    address=STRING;
```

implement the following class in the *.ui project:

``` xtend
class MyDslObjectDocumentationProvider implements IEObjectDocumentationProvider
{
    override getDocumentation(EObject o)
    {
        return switch o
        {
            Person:
            '''
                The person is «o.name»</br>
                He is «o.age» years old</br>
                He lives at:</br>
                «o.address»
            '''
        }
    }
}
```

and override it in the UiModule:

``` xtend
@FinalFieldsConstructor
class MyDslUiModule extends AbstractMyDslUiModule
{
    def Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider()
    {
        return MyDslObjectDocumentationProvider
    }
}
```
## What happens

The following tooltip is getting rendered when hovering:
![Screenshot](http://fs5.directupload.net/images/160923/owy4hxil.png)

Notice that the box isn't high enough.

I can resize it though:
![Screenshot](http://fs5.directupload.net/images/160923/ch8v64gr.png)

**Comment by spoenemann** [comment]
Contributions are welcome!

**Comment by cdietrich** [comment]
imho this is a bug/flaw in your hover impl.

your strange br impl seems to be accepted by the browser,
but HTML2TextReader does not

=> calculated line count is 2
=> windows is 2 lines high

@MarkusAmshove can you please test with

```
The person is «o.name»<br/>
He is «o.age» years old<br/>
He lives at:<br/>
```

@spoenemann do you think we should open a bug against jface.text ?

**Comment by cdietrich** [comment]
i have created https://bugs.eclipse.org/bugs/show_bug.cgi?id=507017

**Comment by cdietrich** [comment]
@MarkusAmshove any feedback on this?

**Comment by MarkusAmshove** [comment]
I can confirm that <br/> works well @cdietrich 

I feel dumb for using the HTML incorrectly.. I've always used XML and had nothing to do with HTML :-)

**Comment by cdietrich** [comment]
since this is a issue in jface.text i will close it here
