### ISSUE TITLE
Maven build fails in fresh Generated project

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#890]
Using eclipse Version: 2018-12 M2 (4.10.0M2)
Xtext 2.16.0-SNAPSHOT

Create new Xtext project using eclipse wizard

Run maven build:
[ERROR] Failed to resolve target definition Eclipse.app/ws/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target: Could not find "org.objectweb.asm/6.2.1.v20180823-1831" in the repositories of the current location -> [Help 1]

Do we need to update the target platform?

**Comment by cdietrich** [comment]
there is no m2 of xtext. m1 is outdated
current wizard creates usages of asm 7

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/blob/69620fc19a6f6276a8f8dcfbdc8c8efbf1f7defe/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target#L26
