### ISSUE TITLE
Use BinaryResourceImpl OPTION_INTERNAL_BUFFER_CAPACITY

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#899]
Today I had a call with Ed. He is analyzing EMF performance for a customer and reported that the usage of the OPTION_INTERNAL_BUFFER_CAPACITY load/save option has a severe influence on the performance. It has a different effect than the buffered streams that we wrap in `BufferedBinaryResourceFactory`. We should consider to set this option additionally there. Ed is using a 4k buffer.

**Comment by kthoms** [comment]
According to Ed this has an additional effect. Of course the used streams should be buffered streams.

**Comment by cdietrich** [comment]
@szarnekow do you know if we have performance tests for ResourceStorageFacade and EmfBasedPersister?

**Comment by cdietrich** [comment]
EMF Based Persister uses `resourceDescriptionResource.getDefaultSaveOptions().put(BinaryResourceImpl.OPTION_INTERNAL_BUFFER_CAPACITY, 10000);`

**Comment by cdietrich** [comment]
Resource Storage facade uses custom object serialization based on java.io anyway

**Comment by cdietrich** [comment]
so i dont think we have to do anything. @szarnekow what do you think?

**Comment by szarnekow** [comment]
I'm not aware of any places where we would benefit from this. Trace files are serialized in a custom fashion. So are storage facades. The index serialization was already tuned.
