### ISSUE TITLE
Find a clear solution to set the org.eclipse.xtext.common.types.shared dependency.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#909]
The Hover UI Tests of the Xtext (DomainModel, HomeAutomation) Example Projects require the  `org.eclipse.xtext.common.types.shared` plugin to succeed. 

Currently, this dependency is set in the UI Plugin of the Examples, see [commit](https://github.com/eclipse/xtext-eclipse/commit/d556939ccab097a221c5bb5d2cdf405cbbc45d7c).

A clear solution should be found to set this dependency only once in a central place.

**Comment by cdietrich** [comment]
@miklossy could you work on that? (adding the dependency to xbase.ui and see if something breaks?)

**Comment by miklossy** [comment]
Actually that was the original fix, but we decided not to add the `org.eclipse.xtext.common.types.shared` dependency to `xbase.ui`. See also the [comment](https://github.com/eclipse/xtext-eclipse/pull/906#discussion_r236073079) of @szarnekow . @cdietrich It would be awesome if you could work on this issue to get that fixed for 2.17.

**Comment by szarnekow** [comment]
@cdietrich and I discussed this today and came to the conclusion that the original fix would do no harm.

**Comment by miklossy** [comment]
Super! thx for the clarification. Than I would create a PR with the original fix soon.

**Comment by miklossy** [comment]
Fixed in 2.17
