### ISSUE TITLE
[example] Cannot generate the `Xtext Domain-Model Example`

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-eclipse#915]
Eclipse SDK
Version: Oxygen.3a (4.7.3a)
Build id: M20180330-0640

 - Xtend IDE: 2.16.0.v20181126-0210 - org.eclipse.xtend.sdk.feature.group - Eclipse Xtend
 - Xtext Complete SDK: 2.16.0.v20181126-0210 - org.eclipse.xtext.sdk.feature.group - Eclipse Xtext

`New` > `Other...` > `Xtext` > `Examples` > `Xtext Domain-Model Example` > `Next` > `Finish`

No error in the logs.

![screen shot 2018-12-03 at 11 58 06](https://user-images.githubusercontent.com/1405703/49369929-ee941200-f6f2-11e8-944f-16b2acbfaf80.jpg)

----

Note, it used to generate the examples (with compiler errors) with:
 - Xtend IDE: 2.16.0.v20180924-0209
 - Xtext Complete SDK: 2.16.0.v20180924-0209

**Comment by cdietrich** [comment]
duplicates https://github.com/eclipse/xtext-eclipse/issues/907

**Comment by kittaakos** [comment]
> duplicates #907

I do not understand. https://github.com/eclipse/xtext-eclipse/issues/907#issuecomment-441691237 says

> Fixed in 2.16

**Comment by cdietrich** [comment]
yes please test with the latest nightly.

**Comment by kittaakos** [comment]
It "works" with `2.16.0.v20181202-0209` but generates the `/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java` class with compiler errors. Is this a known issue?

**Comment by cdietrich** [comment]
no, this is a known "feature" / accepted missbehaviour
we cannot decide not to have codemining based on the target. 
so we create it on oxygen too.
but codemining requires photon

**Comment by kittaakos** [comment]
When I generate a new Xtext Project with the Hello DSL example and I start an Eclipse with `all workspace and enabled target plug-ins` I get following:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff6128aa1d, pid=17035, tid=0x0000000000000307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libobjc.A.dylib+0x7a1d]  objc_msgSend+0x1d
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/akos.kitta/dev/Eclipse.app/Contents/MacOS/hs_err_pid17035.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Is this a known issue or it's happening only with my local environment. Has anyone reported similar errors recently?

**Comment by cdietrich** [comment]
which environment? debian/ubuntu like?

**Comment by kittaakos** [comment]
It's on macOS.
```
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.1 (18B75)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD

```

I think it is unrelated to Xtext:
 - https://bugs.openjdk.java.net/browse/JDK-8211911
 - https://bugs.eclipse.org/bugs/show_bug.cgi?id=538377

I will update this thread once I found a solution. Right now, I cannot start any Eclipse application after updating the latest Xtext unless I am using an old p2 (`http://download.eclipse.org/releases/kepler/201402280900/`) in my TP.

**Comment by cdietrich** [comment]
=> can you please try with jdk patch level 181 or 191?

**Comment by kittaakos** [comment]
For the record, it is the same with `191`:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x00007fff6128aa29, pid=17576, tid=0x0000000000000307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libobjc.A.dylib+0x7a29]  objc_msgSend+0x29
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/akos.kitta/dev/Eclipse.app/Contents/MacOS/hs_err_pid17576.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by cdietrich** [comment]
are you sure this this not the launch screen bugzilla?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538377

**Comment by kittaakos** [comment]
It is. [Workaround](https://bugs.eclipse.org/bugs/show_bug.cgi?id=538377#c52): add `-nosplash`.

1:
![screen shot 2018-12-03 at 14 03 26](https://user-images.githubusercontent.com/1405703/49375347-530b9d00-f704-11e8-978c-a3783141a491.jpg)

2:
![screen shot 2018-12-03 at 14 03 33](https://user-images.githubusercontent.com/1405703/49375357-5737ba80-f704-11e8-953e-384e3b1c1ef1.jpg)

3:
![screen shot 2018-12-03 at 14 03 43](https://user-images.githubusercontent.com/1405703/49375369-5c950500-f704-11e8-9891-0c3c2635e0aa.jpg)


Thanks for tracking this down, @cdietrich.
