### ISSUE TITLE
Punishing perfectly matching content assist proposals not helpful in some cases

### ISSUE THREAD

**Issue by mor-n4** [eclipse/xtext-eclipse#917]
The default implementation of `IContentProposalPriorities` punishes content assist proposals that match perfectly:

https://github.com/eclipse/xtext-eclipse/blob/f75a21470af2b3f6252a86adb7af74f2af5423d9/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/ContentProposalPriorities.java#L29-L30

(note that `sameTextMultiplier` < 1.0, by default)

This makes sense if the user is aware the prefix perfectly matches a member (so if they were interested in that proposal, they would not fire up content assist in the first place). However, in the following cases the current behavior is slightly irritating:

1. user is unaware the prefix perfectly matches a member (then it is very likely the user will be mostly interested in the perfectly matching member),
2. user triggers content assist not to actually apply a proposal, but only to see API documentation.

This can be reproduced in Xtend. For example:
![untitled](https://user-images.githubusercontent.com/7124687/49433557-a6d4bf80-f7b2-11e8-8f37-5f9497aeadfe.png)

With the default size of the content assist pop-up window, the member "sort" would not even be visible at first glance, and devs might get the false impression there is no sort method that works without a custom comparator.

**Comment by cdietrich** [comment]
@szarnekow do you know why this was designed like this?

**Comment by mor-n4** [comment]
Yeah, I had talked with him about this and he told me to create the ticket.

**Comment by cdietrich** [comment]
Fixed in 2.17
