### ISSUE TITLE
[refactoring] Migrate Xbase Testlanguages to new generator

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#92]
Follow-up for https://github.com/eclipse/xtext-extras/issues/57

Changes to org.eclipse.xtext.xbase.testlanguages.ui and org.eclipse.xtext.xbase.ui.tests

**Comment by cdietrich** [comment]
@kthoms is there anything left?

**Comment by kthoms** [comment]
seems to be done
