### ISSUE TITLE
Example project can't be build after restart

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-eclipse#920]
The Xtend example project `Xtend Active Annotation Examples` can't be build if created in am empty workspace after an eclipse restart. It works well afterwards (e.g. after deleting the projects and create the project again or after a clean build) but fails when done right after restart.

![failing_project_creation](https://user-images.githubusercontent.com/30502733/49446318-363e9a80-f7d4-11e8-9908-e0534246bc98.gif)

[failing-build.txt](https://github.com/eclipse/xtext-eclipse/files/2644213/failing-build.txt)

[successfull-build.txt](https://github.com/eclipse/xtext-eclipse/files/2644216/successfull-build.txt)

**Comment by cdietrich** [comment]
all xtend examples dont contain xtend-gen (not even empty)

**Comment by cdietrich** [comment]
=> we should checkin at least the empty xtend-gen folder or even the generates. dont know why they were removed in the first place

**Comment by cdietrich** [comment]
=> we will check in xtend-gen

**Comment by cdietrich** [comment]
@ArneDeutsch is this fixed now?

**Comment by ArneDeutsch** [comment]
Fixed.
