### ISSUE TITLE
Strange use of member in XtextInformationProvider

### ISSUE THREAD

**Issue by UdoW** [eclipse/xtext-eclipse#977]
In the source org.eclipse.xtext.ui.editor.XtextInformationProvider a IEObjectHoverProvider is injected in the member variable hoverProvider but it is not used anywhere.

In the method getInformationPresenterControlCreator() the hoverProvider is searched via the global service provider and stored in a local variable and used only in this method.

Is this a bug?

**Comment by cdietrich** [comment]
it looks like a bug that the var is there. am not sure if we can remove it for comp. reasons

**Comment by UdoW** [comment]
What is the difference between the injected instance and the one which is found by the service provider?

**Comment by cdietrich** [comment]
eObjectAtOffsetHelper.resolveElementAt(state, offset);

It will be the one of the target language and. It the source Lang if the cross ref points to another dsl

**Comment by holgerschill** [comment]
eObjectAtOffsetHelper is used here: org.eclipse.xtext.ui.editor.XtextInformationProvider.getSubject(ITextViewer, int). 
And the thing with the hoverProvider: As Christian said. It could be another language - so we need to get the impl via resourceServiceProvider. For me it does look ok and I don't see a bug.

**Comment by UdoW** [comment]
I meant hoverProvider not eObjectAtOffsetHelper.

**Comment by holgerschill** [comment]
I see. Yes that is a bug. Since it is protected custom impl may rely on it..... I would suggest to remove it. @cdietrich ok for you?

**Comment by UdoW** [comment]
Still my question: What is the difference between the injected one and the other one from the service provider?

**Comment by holgerschill** [comment]
The injected one it for the language the editor is created for. The resourceServiceProvider is a way to get an impl for other languages. So if you want to hover over an element it may be a crossref that comes from another language and has a special hover that we want to use.

**Comment by UdoW** [comment]
Ok, thanks.

**Comment by cdietrich** [comment]
@UdoW eObjectAtOffsetHelper is used to retrieve the object you hover on. this object is then used as contextObject and the contextObject then as parameter for the IGlobalServiceProvider

**Comment by cdietrich** [comment]
am not sure if we can remove the field api wise. 
https://github.com/search?q=%22extends+XtextInformationProvider%22&type=Code does not give any matches though
@szarnekow what do you think?

**Comment by szarnekow** [comment]
Ok to remove. It’s just confusing to have it.

**Comment by cdietrich** [comment]
Fixed in 2.18
