### ISSUE TITLE
[build] We need an lsapi dependency aggregated in the xtext p2 repository 

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#98]
As long as ls api is not part of the eclipse common repository (Oxygen) we should include requiered parts into the xtext p2 repository.

**Comment by spoenemann** [comment]
I hope we can start using lsp4j before the 2.11.0 release so we don't need to do any extra work to the "old" ls-api.

**Comment by dhuebner** [comment]
Fixed
