### ISSUE TITLE
Investigate tests crashes on typefox jenkins

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#983]
Investigate tests crashes with latest
- problem with tp ?
- problem with changes in platform/jdt/.... ?
- problem with jcenter f**kup ?
- xtend affected as well?
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/41/console
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/39/console
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/40/console

does not seem to happen here:
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/319/console

neither it happens locally

**Comment by cdietrich** [comment]
@meysholdt @dhuebner do you have access to the machines and can check e.g. if the eclipse was killed by oom killer or something like that?

**Comment by dhuebner** [comment]
@cdietrich 
Highly likely the  memory limit exceeded.

**Comment by cdietrich** [comment]
is this a problem that can be solved by rebooting the agents?
the tests run with `-Xmx2G` since ages

**Comment by meysholdt** [comment]
Yesterday I restricted the Jenkins to 5.1GB of RAM. Apparently that's not enough.

**Comment by dhuebner** [comment]
AFAIK xtext starts tests with Xmx 4gb.

**Comment by cdietrich** [comment]
`
INFO] --- tycho-surefire-plugin:1.3.0:test (default-test) @ org.eclipse.xtext.ui.tests ---
[INFO] Expected eclipse log file: /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/target/work/data/.metadata/.log
[INFO] Command line:
	[/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx2G, -Dosgi.clean=true, -jar, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.4.0.v20161219-1356/org.eclipse.equinox.launcher-1.4.0.v20161219-1356.jar, -data, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/target/work/data, -install, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/target/work, -configuration, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/target/surefire.properties, -pluginCustomization, /var/jenkins_home/workspace/xtext-eclipse_master-OX2L6OFRZ75ZC7A3K3BJAQVU3V3QABS2LI4URYKVIRLWPPW5BHSQ/org.eclipse.xtext.ui.tests/../releng/org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini]
[INFO]           
`

**Comment by dhuebner** [comment]
@cdietrich Xtext is fully build and deployed from eclipse jenkins, right?

**Comment by meysholdt** [comment]
I have removed the memory limit again. Please reopen if the problems persist.

**Comment by cdietrich** [comment]
thx @meysholdt 
@dhuebner we are still in preparation to be fully on the new eclipse CBI infrastructure
