### ISSUE TITLE
[build] Clean up the p2-repository folder before build

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#99]
See: 
http://services.typefox.io/open-source/jenkins////job/xtext-xtend/job/master/lastSuccessfulBuild/artifact/build/p2-repository/features/

**Comment by meysholdt** [comment]
fixed in ff349d74276f47400469b9edae0685bc04c2ffb7

**Comment by meysholdt** [comment]
and in https://github.com/eclipse/xtext-xtend/commit/5cfbba4b185845a06be88fee5a5e5ec030a6a5e5
