### ISSUE TITLE
Duplicated entries in the DomainModel Example Releng/pom.xml file

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#991]
The [org.eclipse.xtext.example.domainmodel.releng/pom.xml](https://github.com/eclipse/xtext-eclipse/blob/7d111a4a4a56583e0a764dfd56e031e2764763a8/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml#L142-L148) file contains duplicated entries: 
![screenshot](https://user-images.githubusercontent.com/20393472/53242560-63993700-36a5-11e9-98eb-8959001a9cad.png)

I think defining the entry only once should be sufficient.

**Comment by cdietrich** [comment]
Fixed in 2.18

**Comment by miklossy** [comment]
Thx @cdietrich !
