### ISSUE TITLE
[Quickfix] Add quickfix for empty keywords

### ISSUE THREAD

**Issue by loradd** [eclipse/xtext-eclipse#994]
A rule

`Model: '' a=ID;`

produces the error

`A keyword can not be empty`

Two separate quickfixes could be provided to: 

- a) remove the keyword
- b) set the keyword content from its containing rule name

See discussion in [/pull/989].

**Comment by miklossy** [comment]
I have just tested this features with the latest Xtext nightly build and the quickfix works as expected.
@kthoms I think the issue is solved and can be closed.

**Comment by kthoms** [comment]
Thanks @miklossy for checking that!
